### ISSUE TITLE
Change position of loading bar

### ISSUE THREAD

**Issue by khullah** [FredrikNoren/ungit#1001]
Specifically, I think it would be nice in the top of the page.

If not, then at least it should be corrected to be visible always, because right now it just stays below the visible screen. I can only see it if I scroll the page. But still, it makes more sense to me if it were on top.

**Comment by codingtwinky** [comment]
You mean the page load bar?  I do agree that it's position is unreliable.  If we were to do something like youtube esque loading bar would that be sufficient for you?

**Comment by khullah** [comment]
Yes, the one that sits at the bottom most.
I'm sorry, what is a "esque loading bar"?

**Comment by codingtwinky** [comment]
Sorry I meant, "youtube-esque"

Which is something like this: https://codepen.io/ozzysong/pen/vlIhx

**Comment by khullah** [comment]
Lol should have known that!!
Yes, the style could be like that, sure, as long as on top (the link shows
any position).

**Comment by codingtwinky** [comment]
Now I'm thinking maybe we should do for all api calls....

**Comment by khullah** [comment]
yes, it would be great! I've already caught myself waiting for something to happen and not sure it is doing anything.

It could be the same bar or a simple spinner (infinite/progress unknown)

**Comment by codingtwinky** [comment]
Yeah I think I would agree, it is being worked on at #1003.
