### ISSUE TITLE
Donation link on the GitHub?

### ISSUE THREAD

**Issue by ARDivekar** [FredrikNoren/ungit#1004]
I wouldn't mind donating something, but I can't see a donation link on the GitHub page. I definitely wouldn't like to see it while using the ungit app itself.

**Comment by codingtwinky** [comment]
Thanks for this suggestion!

In lieu of recent attempt, I would personally like to put more thought into approaching this issue and I'm sure @FredrikNoren will agree as well.

However, I personally agree 100% that app itself should not be a carrier of any ads or donation links.

**Comment by FredrikNoren** [comment]
Yeah I agree with both of you. Maybe the easiest thing is to just add patreon links next to the maintainers in the README (for those who want?). Or maybe there's a service that will pool donations and distribute to multiple maintainers?

**Comment by FredrikNoren** [comment]
Ehh.. I added my patreon link there but it feels really weird. I feel like if anyone should have a link there it's @jung-kim . Maybe the system could be; maintainers can have a link and we order maintainers on how active they are?

**Comment by jung-kim** [comment]
I've added my patreon as well and will close this for now.

Thanks,
