### ISSUE TITLE
Missing UI feedback when push failed

### ISSUE THREAD

**Issue by chriswue** [FredrikNoren/ungit#1018]
Using ungit 1.4.7 on Chrome Version 63.0.3239.132 (Official Build) (64-bit)

I tried to push a local commit and it failed because someone else had pushed to origin in the meantime. The console shows the problem but there is no UI feedback I could see apart form that the push obviously didn't work. 

Seems related to https://github.com/FredrikNoren/ungit/issues/88 which has a PR attached which seems like it should pop-up a warning but it didn't in my case.

The console output is (somewhat anonymised):

`{"isGitError":true,"errorCode":"unknown","command":"-c color.ui=false -c core.quotepath=false -c core.pager=cat -c credential.helper=/usr/local/lib/node_modules/ungit/bin/credentials-helper 0 8448 push origin 4f8c41027d99f3ca4f4c276b94877cde6d54fb30:master","workingDirectory":"XXXXXXXXXXX","error":"To XXXXXXXXXXX\n ! [rejected]        4f8c41027d99f3ca4f4c276b94877cde6d54fb30 -> master (fetch first)\nerror: failed to push some refs to 'XXXXXXXXXXXXXX'\nhint: Updates were rejected because the remote contains work that you do\nhint: not have locally. This is usually caused by another repository pushing\nhint: to the same ref. You may want to first integrate the remote changes\nhint: (e.g., 'git pull ...') before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.\n","message":"To XXXXXXXXXXXXXXX","stderr":"To XXXXXXXXXXXXXXX\n ! [rejected]        4f8c41027d99f3ca4f4c276b94877cde6d54fb30 -> master (fetch first)\nerror: failed to push some refs to 'XXXXXXXXXXXXXXX'\nhint: Updates were rejected because the remote contains work that you do\nhint: not have locally. This is usually caused by another repository pushing\nhint: to the same ref. You may want to first integrate the remote changes\nhint: (e.g., 'git pull ...') before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.\n","stdout":""}`

**Comment by CurtisHumphrey** [comment]
I think this is related (or the same root issue) as #1017

**Comment by jung-kim** [comment]
When we implemented #1023, there were some promises that were not properly handled and it was fixed via introduction of below line.

https://github.com/FredrikNoren/ungit/blob/a580b0d054947335e13e16ada040c296595a21fa/components/graph/git-ref.js#L144
