### ISSUE TITLE
Doesn't show the tree if no remotes

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1027]
Ungit doesn't show the project tree if there is no remote

ungit --version: 1.4.7

Steps to reproduce:

```
mkdir test
cd test
git init
git commit --alow-empty -m 'test'
ungit
```

**Comment by ylecuyer** [comment]
That was because of ublock origin...
Maybe the log endpoint name should be renamed or a warning may be displayed if the log endpoint isn't reachable

**Comment by campersau** [comment]
A warning should be shown https://github.com/FredrikNoren/ungit/pull/909
Did you get it?

**Comment by ylecuyer** [comment]
@campersau no I didn't get it
