### ISSUE TITLE
Add button for empty-commits

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1028]
Useful for triggering CI

**Comment by campersau** [comment]
You can `amend` the previous commit with no additional changes from the UI.

**Comment by ylecuyer** [comment]
Yes but it is not an empty commit

**Comment by jung-kim** [comment]
Isn't ability to re trigger CI should be a fix in CI side not the git source side?

**Comment by ylecuyer** [comment]
Well it's a git command so I expect to have it available in my git client.

(fwiw with the CI we are currently using (drone) if you restart the CI while a build is running, it's not possible to cancel/restart the build from the interface. You must create a new commit to newly trigger the CI)

**Comment by jung-kim** [comment]
I understand the problem but I feel like that should be the fixes on drone side not ungit

I think empty commit is fine but I hope it doesn't bring too much complications
