### ISSUE TITLE
Add cancel button next to commit (amend, empty-commit)

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1029]
Add a cancel button next to the commit button in the staging view.
Currently, when you're amending a commit or committing an empty commit you have to refresh to cancel.

**Comment by jung-kim** [comment]
I don't understand the concept of canceling commit.  A commit should be final, and if you want to go back you can go back to the commit before and rework.

**Comment by campersau** [comment]
If there is nothing to commit you see this:
![image](https://user-images.githubusercontent.com/4009570/35485420-d0a8b57e-045f-11e8-87df-f9729f578bb7.png)
In #1030 a second link will appear and it is not possible to go back to this view after you clicked on one of the links without refreshing the page.

**Comment by jung-kim** [comment]
Am I understanding correctly that we are adding #1028 and that implementation, #1030, now needs cancel button?
