### ISSUE TITLE
Add a commit & push button

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1038]
I often find myself doing the combo commit & push.

I think it may be useful to have a commit & push button next to the existing commit button

**Comment by campersau** [comment]
Just to clarify: this should push to the currently active remote right?

Visual Studio uses this design:
![7838 image_042e259b](https://user-images.githubusercontent.com/4009570/35727789-92d6a49c-0809-11e8-95c3-58029c810691.png)

**Comment by ylecuyer** [comment]
Right. What does commit and sync does ?

**Comment by campersau** [comment]
> Commit and Sync does three things. First, it will commit. Second, it will perform a pull (grabs the updated information from the remote repo). Finally, it will push.

https://stackoverflow.com/a/30039179

**Comment by jung-kim** [comment]
Should one implement this, can we make this feature a simple flag that alters behavior of the commit button rather than have it as new button?  I think that would be better

**Comment by ylecuyer** [comment]
I think it would be better to have a drop down button as in campersau
screenshot.

**Comment by jung-kim** [comment]
So when `commit and push` is clicked does `commit` button switch to `commit and push` button and state is managed that way?  or when you want o do `commit and push` do you have to do two clicks all the time?

Honestly as long state is sticky I'm for it

**Comment by campersau** [comment]
In Visual studio it is not a sticky button but I am not sure if it should be. @jung-kim what is your definition of sticky? Sticky per session? Per repository? Global?
Two clicks are at least one click less than now 😄 

Also one interesting thing is that if there is no remote Visual Studio still shows the commit and push option and displays a screen where you can add a remote after the commit.

**Comment by jung-kim** [comment]
I was thinking per browser should be sufficient.

oh thats nice, we can do that as well.

**Comment by campersau** [comment]
fixed with #1046
