### ISSUE TITLE
Login in remote issue

### ISSUE THREAD

**Issue by nacho-milanese** [FredrikNoren/ungit#1044]
I'm experiencing an issue in which a remote github repository fails with authentication error without asking for credentials (is it any kind of know issue?)
Don't have too much information on version and such as it is happening in a Datalab instance in Gcloud (can have a look though if help me out where to look)

Thanks!

**Comment by ylecuyer** [comment]
It didn't ask for the credentials in the UI but did it ask for the credentials in the console where you started ungit ?

**Comment by nacho-milanese** [comment]
It didn't ask for the credentials at all and crashes. The instance is started by default inside a docker provided by google in Datalab, perhaps I have to ask them, but I tried here as it may have been a known error

**Comment by jung-kim** [comment]
FYI, #1041 has not been published yet.  It will be published with #1024 and ungit@1.4.10 will now have it.

**Comment by dayaftereh** [comment]
Have you set the `--rootPath`, maybe this is the issue #1060.

**Comment by lchrajkumar** [comment]
This issue is still not fixed yet?

**Comment by jung-kim** [comment]
it should be fixed now but feel free to open a new ticket if it is still broken.
