### ISSUE TITLE
Stash pop and delete

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1048]
I would be great to have a button which does stash pop and delete

**Comment by jung-kim** [comment]
This was the previous behavior of the stash operation.

However, we changed it so that applying stash wouldn't pop it off as delete is one click away.

**Comment by campersau** [comment]
See https://github.com/FredrikNoren/ungit/issues/919 and https://github.com/FredrikNoren/ungit/pull/939 for reference
