### ISSUE TITLE
%U is null when launchBrowser is false and launchCommand is set

### ISSUE THREAD

**Issue by cgty** [FredrikNoren/ungit#1065]
I used to use the following `.ungitrc` to start ungit server and launch chromium without the browser toolbars.

```
{
  "debug": true,
  "launchCommand": "chromium-browser --app=%U",
  "launchBrowser": false
}
```

It was working in the previous versions of ungit (I can't recall the exact version I used before).

With the latest version, when I run `ungit` within a git repository, the output is as follows:

```
## Ungit started ##

Took 635ms to start server.
Running custom launch command: chromium-browser --app=null
```

And an empty chromium window (with toolbars) is launched.

If I set `launchBrowser` to `true`, `%U` is correctly set and chromium is launched with the correct configuration. But the default browser is also launched _-as expected-_, which makes it an unusable workaround.

I think adding `|| config.launchCommand` to this line might fix this issue, but I haven't tested it myself.

https://github.com/FredrikNoren/ungit/blob/b86452903db91c1828a1882abfe794f2fd96fa1b/bin/ungit#L32

I can test & verify it locally and send a PR if my approach is right.

_versions_
ungit: 1.4.13
node: v8.9.4
npm: 5.6.0
os: linux

**Comment by ylecuyer** [comment]
:+1:
