### ISSUE TITLE
Cannot remote-login from GUI

### ISSUE THREAD

**Issue by hitochan777** [FredrikNoren/ungit#1076]
I am having an issue with remote login with GUI.
Below is how to reproduce the issue.

# Environment
OS: Ubuntu 16.04
Node.js: v9.3.0
NPM: 5.8.9
Ungit: [master as of writing this issue](https://github.com/FredrikNoren/ungit/commit/43ca39e7d6a10af33a046e3d6312580593b462ec)

# How to reproduce

1. (In ungit )Run ungit with `npm start -- --authentication`, list of usern ame and password is stored in `~/.ungitrc`. 
2. (In ungit) Clone a public repository that I have a write access to in GitHub vie https.
3. (In some editor) Make some modification to the code in the repository from 3.
4. (In ungit) Commit and push.
5. Then a popup appears asking username and password in GitHub. I type my username and password but nothing happens. But when I looked at the console, it is still asking me username and password.

**Comment by hitochan777** [comment]
After some debugging, I found credential-helper is emitting an error, complaining it couldn't get any response from the server.

Log from credential-helper
```
{"message":"Error getting credentials, couldn't query server","stack":"Error: socket hang up\n    at createHangUpError (_http_client.js:330:15)\n    at Socket.socketOnEnd (_http_client.js:423:23)\n    at
Socket.emit (events.js:164:20)\n    at endReadableNT (_stream_readable.js:1062:12)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","code":"ECONNRESET","level":"error","timestamp":"2018-04-15T09:01:42.188Z"}
```

**Comment by jung-kim** [comment]
Thanks for the detailed bug report.  However, when I did testing on my own ubuntu box against a private git repo and it worked for me.  I might be missing something.

When git credentials is needed, you are absolutely right that it spawns `bin/credentials-helper.js`.  It would then hit `source/git-api.js - /credentials` end point.  

`/credentials` endpoint checks for local loop backs and valid socket.  do you see any of those error messages?

**Comment by jung-kim** [comment]
Also, are you using `rootPath` option?

**Comment by hitochan777** [comment]
No.

**Comment by hitochan777** [comment]
> When git credentials is needed, you are absolutely right that it spawns bin/credentials-helper.js. It would then hit source/git-api.js - /credentials end point.

I checked the log and am sure about this.

> /credentials endpoint checks for local loop backs and valid socket. do you see any of those error messages?
I will check and let you know!

I don't use `rootPath`. I ran ungit with `-- --authentication`  and `--users` only.

**Comment by hitochan777** [comment]
@jung-kim I submitted a PR for this.
