### ISSUE TITLE
pass args in git operations

### ISSUE THREAD

**Issue by pabloazurduy** [FredrikNoren/ungit#1080]
Hi !
a question..
¿ Its there a way to pass some arguments or mask/define the default commands that ungit is using for `clone`, `fetch` `push` and `pull` ?. for example `--recurse-submodules` and that way support submodules  `git clone --recurse-submodules `

maybe configuring the git client that ungit is using masking the clone function to include `--recurse-submodules` by default. 

[example](https://stackoverflow.com/a/33632042/5318634)

thanks !

**Comment by pabloazurduy** [comment]
[this might work](https://stackoverflow.com/a/24266749/5318634)

**Comment by jung-kim** [comment]
Oh, we can definitely add a toggle on clone to add `--recurse-submodules` and expose that option on UI.

Will fix that soon once I come back from vacation
