### ISSUE TITLE
Error when remote are not available

### ISSUE THREAD

**Issue by chok** [FredrikNoren/ungit#1081]
Hi !

I'm using Gitlab and the access has been suspended on gitlab remote. Then, I have error message in ungit : 
```
fatal: 'origin' does not appear to be a git repository
fatal: Impossilble de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
```

So I can't access the gui without remove the remote even the access to this remote is not very important and maybe shouldn't be an issue to access the gui.

**Comment by jung-kim** [comment]
Ah, will add better remote fetch error handling.  

Also, ungit will not work correctly with the none English git responses as Ungit uses them to detect git states.  So that might cause additional problems for you
