### ISSUE TITLE
"$ is not defined" when clicking magnifying glass

### ISSUE THREAD

**Issue by StevenGBrown** [FredrikNoren/ungit#1086]
Click on the magnifying glass to the right of a branch name:
<img width="413" alt="screen shot 2018-05-05 at 3 33 54 pm" src="https://user-images.githubusercontent.com/304031/39660840-c7bd3348-5079-11e8-9fc9-0893526216a8.png">

An error message is displayed:
<img width="481" alt="screen shot 2018-05-05 at 3 35 53 pm" src="https://user-images.githubusercontent.com/304031/39660855-1174409e-507a-11e8-963d-fc944efc9efc.png">

This appears in the browser console:
```
Uncaught ReferenceError: $ is not defined
    at GitNodeViewModel.showRefSearchForm (git-node.js:166)
    at HTMLButtonElement.<anonymous> (knockout:99)
    at HTMLButtonElement.dispatch (jquery:5183)
    at HTMLButtonElement.elemData.handle (jquery:4991)
    at HTMLButtonElement.d (raven.js:438)
```

No errors displayed in the CLI output.

Can reproduce with:
* Version 1.4.21 installed with npm and
* 671dd02d, started with instructions on CONTRIBUTING page.

Environment:
* node 9.4.0
* npm 6.0.0
* macOS High Sierra

**Comment by campersau** [comment]
Yes a `require('jquery')` is missing and jquery ui is not correctly setup because each widget must be [required individually](https://jqueryui.com/upgrade-guide/1.12/#official-package-on-npm).

I can provide a fix in the next few hours.

**Comment by StevenGBrown** [comment]
The error is no longer displayed and I'm looking forward to spending more time with ungit.

Thank you @campersau, @jung-kim.
