### ISSUE TITLE
Not compatible with Ubuntu 18 04

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1092]
I have juste installed Ubuntu 18 04 today from scratch and ungit doesn't seem to be compatible.

There is a git error while doing the rev-parse --show-toplevel

I'm not sure if it is because of node or the updated git. The fact is that it tries to run the command with the parent folder which is not a git folder. I tried back to pre 1.0.0 version and none work.

I will update this bug report tomorrow with more information

**Comment by ylecuyer** [comment]
More precisely it is not compatible with latest git version at least git v2.17.0

In this version those error message doesn't have upcased letters: https://github.com/FredrikNoren/ungit/blob/f270860d1e5ed5646a90dc6749ac0daa9c5e6752/source/git-promise.js#L123

**Comment by capaj** [comment]
I am using ungit 1.4.10 without any issue on ubuntu 18.04. This must be something else.

**Comment by jung-kim** [comment]
Thanks for looking into this, and that edit is bit annoying...  Now that we have to support both string formats...

**Comment by ylecuyer** [comment]
Seems the main error was du to ublock being activated and the warning inside ungit for adblocker didn't work.
Nevertheless error messages changed and it fills the error log now

**Comment by capaj** [comment]
@jung-kim it would be nice if ungit could give some kind of message to the user warning them to turn off the adblocker. This problem is very common with first time users of ungit.

**Comment by ylecuyer** [comment]
There is already an adblocker detection it is just that it doesn't work...
The easiest move would be to rename the `/api/log` route which gets always blocked.

**Comment by jung-kim** [comment]
Keeping it open as adblcoker is detection issue is brought up.

Detecting adblocker or any other 3rd party addons are challenging and I was originally against changing `/api/log` route to something else but I may have to give that up
