### ISSUE TITLE
ungit has no way of resolving a rebase conflict with no files

### ISSUE THREAD

**Issue by capaj** [FredrikNoren/ungit#1097]
![image](https://user-images.githubusercontent.com/1305378/40669597-9503eb94-6367-11e8-963b-0f303e2a9643.png)

From time to time when I am doing rebase I can get into this situation where git has an empty conflict. The only way to resolve it is to drop to git CLI and run `git rebase --skip`.
It would be nice if ungit had a button for doing this.

**Comment by jung-kim** [comment]
Yeah saw this before myself but couldn't replicate so I wasn't sure if it was due to my buggy dev version of ungit or if it was an actual problem.

Will try to add some empty diff check or see if I can replicate.

If you have simple replication step, please do share.

**Comment by capaj** [comment]
[typegql.zip](https://github.com/FredrikNoren/ungit/files/2066516/typegql.zip)

I ran into it just now with an OSS repo. I was rebasing-there was one conflict, resolved it and then the bug occured. I've zipped the all the files in the folder except node_modules, so it should be trivial to reproduce. GL!

**Comment by jung-kim** [comment]
This should be fixed via #1103 as logic has changed
