### ISSUE TITLE
Keeps failing on disconnected remotes

### ISSUE THREAD

**Issue by Sereglaith** [FredrikNoren/ungit#1098]
I will often work disconnected from the internet while traveling.  Unfortunately, any remotes that I have will continually fail ssh authentication, since they are no longer present.  This failure will continually add error messages to the ungit workspace and push the tree further and further down.  If there was a way to stop automatic queries on remotes, or stop queries after the first failure, this issue would go away.  Issue #1083 is similar to this problem.  Obviously, a  UI element would be needed to reactivate auto queries on remotes.  I would be open to other ideas that solve the issue of closing "infinite" failure messages.

My current workaround is to remove the remotes and re-add them later when I need them.  Needless to say, this is equally annoying.

**Comment by jung-kim** [comment]
I think this is also related to #1014.  Will try to push out the fix soon.

**Comment by Sereglaith** [comment]
Perfect! Thanks! Your efforts are appreciated!
