### ISSUE TITLE
still showing me the notification of the update

### ISSUE THREAD

**Issue by annymosse** [FredrikNoren/ungit#1102]
im have `ubuntu 18.04` and using  the last vesrion `vscode` and the latest version of `npm` and `node` too
,but the addon in my vscode still showing me the update notification even i have the updates of everythings `(node,npm,vscode,ungit cli,ungit ext)`
`git version 2.17.1`
```
terminal>node -v
v8.11.1
terminal>sudo node -v
v8.10.0
termina>ungit -v
1.4.25
terminal>sudo ungit -v
1.4.25
```
ungit at my vscode version 1.1.21

**Comment by jung-kim** [comment]
That is probably because it is asking you to update ungit as newer version of ungit is out.

You could disable this via adding in `ungitVersionCheckOverride: true` to your `~/.ungitrc` file or you could update the ungit to latest version.

**Comment by annymosse** [comment]
which version the vs code is use? the normal node or the root node ?
(coz the alert showing `sudo -H npm update ungit -g` instead `npm update ungit -g`)

**Comment by jung-kim** [comment]
I'm not sure if I follow as ungit itself is not dependent on vscode.  

If you are using ungit via vscode plugin, you might want to reach out to @Hirse about this and how vscode plugin maintains ungit version as it might be separate from global npm installation.

https://github.com/hirse/vscode-ungit

**Comment by Hirse** [comment]
Updated the extension with the latest version of ungit today.
