### ISSUE TITLE
How can I configure ungit to automatically show specified repos on the home screen?

### ISSUE THREAD

**Issue by tkambler** [FredrikNoren/ungit#1104]
Is this possible? If so - how? The documentation doesn't say, but it seems like it should be possible.

**Comment by campersau** [comment]
Yes, this is possible. After you opened a repository in ungit you click on the `+` icon on the right side to add it to the home screen. 
![image](https://user-images.githubusercontent.com/4009570/41336309-2dca2872-6eec-11e8-918a-8d6255e12f9d.png)

The state is stored in `localStorage`.

**Comment by tkambler** [comment]
Thank you for the reply, but it wasn’t particularly useful. The question is: *How* would one go about pre-configuring the home screen to show certain repos when the application is launched.

**Comment by jung-kim** [comment]
Ah... isn't that what @campersau answered?

by clicking "+" sign you can see the repos in ungit home page.  There is no official way to preconfigure this so you can modified the local storage of browser.

**Comment by tkambler** [comment]
Technically, yes. Sorry if that came off as rude, that was not my intent. Perhaps I could have been clearer with the original question. I understand how I, as a user, can configure the homepage. The question is how can I - as an admin - *pre-configure* Ungit to display certain repositories when a user first loads the tool.

If I understand correctly, this is not currently possible.

**Comment by jung-kim** [comment]
You are correct that is not supported yet.

How are you deploying/envisioning this?  via ungit.rc file? via http end point?  I think ungit.rc config is the way to go

**Comment by tkambler** [comment]
I agree - simpler is better. We already have a configuration mechanism - `.ungitrc`. I'm envisioning a field that allows you to pre-populate the home screen with repos. Something like this:

```
...
"defaultRepositories": [
    "/workspace/repo1",
    "/workspace/repo2"
]
...
```

**Comment by jung-kim** [comment]
Cool, I will punch one out this weekend if no body work on it before

**Comment by tkambler** [comment]
Very cool. :)

**Comment by jung-kim** [comment]
I was going to add some automated tests but bit busy at the moment and it's functionality works with brief testings I've done.  

few things:

1. It doesn't do git repo validations as in it will allow add any path to be added not just a path for git repos.  (will be marked red if it's not git repo in the home page)
2. You can remove the preconfigured git path.  However it will be added back in on page refresh. (I don't think this is a big deal.)
3. .ungitrc looks something like below as an example as I haven't written a documentation around this feature.
```
{
        ...
        "defaultRepositories": ["/path/to/git/aaaa", "/path/to/git/bbb"],
        ...
}

```
