### ISSUE TITLE
Implement GIT_OPTIONAL_LOCKS

### ISSUE THREAD

**Issue by stdedos** [FredrikNoren/ungit#1105]
I have been spammed a lot of times with "fatal: Unable to create '[...]/.git/index.lock': File exists." during a `rebase`.

There are many occasions, however, that commands that don't strictly need the lock take it anyway (most notorious command being `git status`)

Since a lot of people are affected, git >2.15.0 added https://github.com/git/git/commit/27344d6a6c8056664966e11acf674e5da6dd7ee3 this.

I can obviously start the command with `env GIT_OPTIONAL_LOCKS=0 ungit`; however, I thought you might be interested to take a more fine-tuned / less crude look at it.

**Comment by jung-kim** [comment]
This this is a big problem for Ungit and we've added in the retry logic to get around it but clearly that doesn't 100% eliminate the problem.

I've added `--no-optional-locks` to the status end point only via #1109 when git version is appropriate.  

Thanks for bringing this issue up!

**Comment by stdedos** [comment]
@jung-kim I am not sure what you would mean by "added in the retry logic"; however, you cannot retry during `git rebase` (or I don't know yet how to continue when that breaks).

_Yeah, `rebase` is of the satan, but I like it 😸_
