### ISSUE TITLE
Cannot use ungit in cloud9

### ISSUE THREAD

**Issue by tsuckow** [FredrikNoren/ungit#1112]
ungit explicitly binds to the loopback adapter as of https://github.com/FredrikNoren/ungit/commit/d893f3a045caa0eda6c3bfae9ee55625789c8801
Which prevents using ungit in cloud9. The bind ip should be configurable or use the $IP environmental variable.

**Comment by jung-kim** [comment]
Shoot...  `127.0.0.1` binding is preferable in most of the cases and I guess I now see the where this is an exception, cloud9.

Will be pushing a simple config to allow you to do default binding
