### ISSUE TITLE
Ungit doesn't work inside a alpine container in versions after 1.4.26

### ISSUE THREAD

**Issue by vboufleur** [FredrikNoren/ungit#1115]
Hi guys.

I don't know what changed in ungit after version 1.4.26 but it stopped working in my `node:8-alpine` container. I'm currently only using version 1.4.26.

Below are the container logs:
```
Running /usr/local/bin/ungit
## Ungit started ##

Took 1346ms to start server.
Browse to http://localhost:8448/#/repository?path=%2Fgit
(node:1) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/local/lib/node_modules/ungit/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here's my old dockerfile. New one installs only version 1.4.26 of ungit with: `npm install -g ungit@1.4.26`
```
FROM node:8-alpine
MAINTAINER IPBurger <accounts@ipburger.com>

RUN \
    echo "Installing bash, git and openssh" \
    && apk add --update git openssh bash \
    && echo "Installing ungit with npm" \
    && npm install -g ungit \
    && echo "Cleaning apk..." \
    && apk del --progress --purge && rm -rf /var/cache/apk/* \
    && echo "ALL DONE"

COPY .ungitrc /root/.ungitrc

EXPOSE 8448

# https://docs.docker.com/engine/reference/builder/#workdir
WORKDIR /git

COPY entry.sh /entry.sh
ENTRYPOINT ["/entry.sh"]

CMD ["/usr/local/bin/ungit"]
```

Entrypoint:
```
#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

DAEMON=/usr/local/bin/ungit

stop() {
    echo "Received SIGINT or SIGTERM. Shutting down $DAEMON"
    pid=$(cat /var/run/$DAEMON/$DAEMON.pid)
    kill -SIGTERM "${pid}"
    wait "${pid}"
    echo "Done."
}

echo "Running $@"
if [ "$(basename $1)" == "$DAEMON" ]; then
    trap stop SIGINT SIGTERM
    $@ &
    pid="$!"
    mkdir -p /var/run/$DAEMON && echo "${pid}" > /var/run/$DAEMON/$DAEMON.pid
    wait "${pid}" && exit $?
else
    exec "$@"
fi
```

**Comment by jung-kim** [comment]
So this is odd, I did replace [`open`](https://www.npmjs.com/package/open) with [`opn`](https://www.npmjs.com/package/opn) because open is unmaintained and had a security issue.

I may try to attach a proper error handler to see the actual errors within but ungit server should be functional as process should be alive.

**Comment by vboufleur** [comment]
> but ungit server should be functional as process should be alive.

The process is still alive, but when I try to access ungit through `localhost:8448` there's nothing there to respond to this port. When I retry with version `1.4.26` there's no error and I can access ungit.

**Comment by vboufleur** [comment]
@tsuckow Could be a duplicate, but @jung-kim made a nice suggestion of implementing a better error handler to see see the actual errors. If it's a duplicate we could transform this issue into this.

Instead of getting just this from the logs we would get the actual reason why the promise got rejected:
```
(node:1) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/local/lib/node_modules/ungit/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jung-kim** [comment]
@tsuckow  that was my first thought but it was deployed at v1.4.29 and 1.4.26 works, so I'm assuming something to do with how the `opn`work differently.  

Admittedly this is assuming @vboufleur tried v1.4.28 and 27.  

Anyhow, v1.4.30 is release with error catching and configurable binding.  @vboufleur, you would want to look for [`failed to navigate to`](https://github.com/FredrikNoren/ungit/pull/1113/files#diff-48ffa8abde0e3cbafcbadb1d28aa2ea0R31)

**Comment by vboufleur** [comment]
Ungit v1.4.30 is not available in npm yet for me to test it: https://www.npmjs.com/package/ungit

I tried v1.4.28 and 27 too. v1.4.26 was the first one that worked in my container.

**Comment by jung-kim** [comment]
Ah shoot, yeah either github hooks or travis logic changed and it didn't get to build.

Will try to fix it tonight.

**Comment by maxsennin** [comment]
Hello,

I just install ungit, I have the same problem with version 1.4.32.

`## Ungit started ##

Took 670ms to start server.
Navigate to http://localhost:8448/#/repository?path=%2Fhome%2Fadmin
failed to navigate to http://localhost:8448/#/repository?path=%2Fhome%2Fadmin Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/lib/node_modules/ungit/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)`

**Comment by campersau** [comment]
@maxsennin this is expected because the error is still logged. But now you should be able to browser to the page `http://localhost:8448/#/repository?path=%2Fhome%2Fadmin` manually. Or didn't that work?

---

Exit code 3 means `A required tool could not be found.` according to the [documentation of `xdg-open`](https://linux.die.net/man/1/xdg-open).

**Comment by maxsennin** [comment]
@campersau ok, that don't work... But maybe because ungit and my web server is installed on my virtual machine (debian, without UI). When I try to access from my computer, with the IP address, I have no respond...

**Comment by campersau** [comment]
@maxsennin Since ungit `1.4.30` you also need to specify `ungitBindIp` if you want to access ungit from another machine for security reasons (https://github.com/FredrikNoren/ungit/issues/988). You can get the previous behavior by using `/usr/local/bin/ungit --ungitBindIp 0.0.0.0`.

**Comment by campersau** [comment]
I have confirmed that the issue is fixed with ungit 1.4.32 using the instructions from @vboufleur .

**Comment by dregad** [comment]
I confirm that adding `--ungitBindIp 0.0.0.0` fixes the problem (i.e. Ungit works again). However, the error message is still displayed in the console log, which I find confusing.
```
$ ungit
info: BugTracker set version: 1.4.36
info: BugTracker set user hash
## Ungit started ##

Took 1169ms to start server.
Navigate to http://0.0.0.0:8081/#/repository?path=%2Fhome%2Fubuntu%2Fworkspace%2Fapecove
info: Sending to keen.io: event {"launchTimeMs":1169,"version":"1.4.36","userHash":"eba480840222cb836d44a2ea38ee0c32"}
failed to navigate to http://0.0.0.0:8081/#/repository?path=%2Fhome%2Fubuntu%2Fworkspace%2Fapecove Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/ubuntu/.nvm/versions/node/v8.7.0/lib/node_modules/ungit/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

**Comment by campersau** [comment]
@dregad see https://github.com/FredrikNoren/ungit/issues/1115#issuecomment-415990234, https://github.com/FredrikNoren/ungit/issues/1138#issuecomment-421717577

**Comment by dregad** [comment]
@campersau Yes I saw those... My point is that if the error is expected, then ungit should display some meaningful warning, instead of a stack dump.
