### ISSUE TITLE
ungit crashes immediately after running

### ISSUE THREAD

**Issue by Thatkookooguy** [FredrikNoren/ungit#1123]
I'm trying to run ungit (version 1.4.31) with `ungit`,

and as soon as the UI opens in a browser tab, I get the following UI and console errors:
![screen shot 2018-08-07 at 2 07 44 pm](https://user-images.githubusercontent.com/10427304/43772605-53261074-9a4b-11e8-982d-a6d50042eef1.png)

i also attached the logs dump file from my browser (chrome)
[localhost-1533640181519.txt](https://github.com/FredrikNoren/ungit/files/2266162/localhost-1533640181519.txt)

**Comment by jung-kim** [comment]
Hmm that is odd...  

I can see that pretty much all API calls are failing but I'm not seeing why so it is big hard for me to judge this one.  Do you have the server side log? What is your `.ungitrc` file?

Also, can you use gist or anything else other than uploading a file?
