### ISSUE TITLE
diff doesn't work for first commit

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1124]
Because of this line: https://github.com/FredrikNoren/ungit/blob/2aae26ada4f010cf6d42568018351075564a5663/source/git-promise.js#L288

If you want to see the diff of the very first commit of a git repo you will see the current file content instead of the original one.

**Comment by jung-kim** [comment]
I remember having an issue with the very first commit of a new repo as ungit try to compare with previous commit that doesn't exist.

I don't remember if I ever fixed it, but will fix it

**Comment by jung-kim** [comment]
It seems to be working... Can you tell me how I can replicate?

<img width="794" alt="screen shot 2018-08-11 at 16 43 54" src="https://user-images.githubusercontent.com/5281068/43997035-cb117b40-9d85-11e8-828a-2cafbd994712.png">

**Comment by ylecuyer** [comment]
You have to add another commit and modify the file to reproduce the error

**Comment by jung-kim** [comment]
Ah Okay, will retest later and reevaluate

**Comment by ylecuyer** [comment]
This also happens if you look for an old commit and locally modify the same file as one in the commit. Then the diff for the select file in the commit will show the current file content

**Comment by jung-kim** [comment]
![screen shot 2018-10-15 at 20 16 51](https://user-images.githubusercontent.com/5281068/46990663-47faa000-d0b7-11e8-8bf6-9ff5f4a451ca.png)

It seems that I can see the 2nd and 1st commit...? are you at a particular screen dimension?

**Comment by ylecuyer** [comment]
I have found a way to reproduce:

```
cd ~
mkdir ungit-temp
cd ungit-temp
git init
echo "a" > text.txt
git add -A
git commit -m "commit"
```
![first_commit](https://user-images.githubusercontent.com/1866809/48547590-46491580-e8cb-11e8-8c2e-2b2ca78f03e3.png)
Everything is OK

Revert the commit

![second](https://user-images.githubusercontent.com/1866809/48547605-5660f500-e8cb-11e8-9f35-54b6c33255e1.png)
Everything is OK

Check the first commit

![second_b](https://user-images.githubusercontent.com/1866809/48547627-624cb700-e8cb-11e8-977e-303f1c05cfdd.png)
NOT OK should be +a (though the +1/-0 is ok on top)

```
echo "b" > text.txt
``` 

Stage 

![stage](https://user-images.githubusercontent.com/1866809/48547800-c2dbf400-e8cb-11e8-8122-b4d363c93113.png)
Everything is OK

Reverted commit
![revert_commit](https://user-images.githubusercontent.com/1866809/48547867-e141ef80-e8cb-11e8-8799-8ad37ce38813.png)
NOT OK should be - a (+0/-1 is ok on top though)

Initial commit
![initial_commit](https://user-images.githubusercontent.com/1866809/48547938-02a2db80-e8cc-11e8-86d1-e2f075717dc5.png)
NOT OK should be - a (+1/-0 is ok on top though)

```
git add -A
git commit -m "change"
```

New commit
![change](https://user-images.githubusercontent.com/1866809/48548015-31b94d00-e8cc-11e8-9a6d-a7e7b9e83212.png)
Everything is OK

Reverted commit
![reverted_ok](https://user-images.githubusercontent.com/1866809/48548039-44338680-e8cc-11e8-8cbe-2b655f14be13.png)
Went back to is OK

Initial commit
![initial_nok](https://user-images.githubusercontent.com/1866809/48548066-56152980-e8cc-11e8-8acc-a8ce9d7bc03d.png)
Still not OK (should be + a)
