### ISSUE TITLE
Warning of local commits lost when checkout origin

### ISSUE THREAD

**Issue by atomic** [FredrikNoren/ungit#1125]
When you have commits locally, and there are new commits on the origin, sometimes, you want to checkout origin branch first, while keeping the local commits somewhere. 
When you use ungit to checkout origin, all local commits are lost.

I know this is intended behavior from Git, but this does not mean it's intuitive and I feel for this trap couple of times because of how easy it is to use Ungit. I think there should be a big warning signs whenever you do operations that will remove work permanently, since there is no way to recover the lost commits.

**Comment by jung-kim** [comment]
So just to be clear no commits are lost.

When you do `reflog` you should be able to see the headless commits without branch you can checkout via sha1 hash. 

To work with this, you could create another ref, either branch or tag, and then checkout origin.  Then you can see the unpushed commits on the newly created ref.

Does this help you?

**Comment by atomic** [comment]
Yeah, what I now do is create a temporary branch whenever I want to checkout origin branch without losing my local commits.
