### ISSUE TITLE
ungit throws error at startup and quits

### ISSUE THREAD

**Issue by guillaumedavidphd** [FredrikNoren/ungit#1130]
I haven't been able to run `ungit` since the last update. I get the following error:

    internal/modules/cjs/loader.js:596

    throw err;
    ^

    Error: Cannot find module 'editions'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
        at Function.Module._load (internal/modules/cjs/loader.js:520:25)
        at Module.require (internal/modules/cjs/loader.js:650:17)
        at require (internal/modules/cjs/helpers.js:20:18)
        at Object.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\ungit\node_modules\getmac\index.js:4:18)
        at Module._compile (internal/modules/cjs/loader.js:702:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
        at Module.load (internal/modules/cjs/loader.js:612:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
        at Function.Module._load (internal/modules/cjs/loader.js:543:3)

The module `editions` is installed globally, and so is `ungit`.

**Comment by ylecuyer** [comment]
Which version of node/npm are you using? 

Please refer to https://github.com/FredrikNoren/ungit/blob/master/CONTRIBUTING.md

> Posting issues
>Just common sense; do a quick search before posting, someone might already have created an issue (or resolved the problem!). If you're posting a bug; try to include as much relevant information as possible (ungit version, node and npm version, os, any git errors displayed, the output from CLI console and output from the browser console).

**Comment by guillaumedavidphd** [comment]
ungit@1.4.32
node@10.3.0
npm@6.4.0
os: Win10

**Comment by balupton** [comment]
getmac and editions are my packages. Could the author please try updating getmac to 1.4.4 as the debugging info users have provided is for getmac 1.4.1

**Comment by guillaumedavidphd** [comment]
I've updated getmac to 1.4.4. Probem is still here.

**Comment by balupton** [comment]
Ok. I think I miss configured something with editions. Let me push up a fix. One moment. Strange errors are now only coming in, as the version is a few weeks old.

**Comment by balupton** [comment]
v1.4.5 of getmac will be published as soon as https://travis-ci.org/bevry/getmac/builds/419868038 passes - let me know if that resolves the issue

**Comment by tony90018** [comment]
I've updated getmac to 1.4.5. But the problem still exists.

**Comment by balupton** [comment]
I will need to remote into your machine to debug, as I am unable to reproduce. Grab a time on https://balupton.com/meet and we’ll work it out

**Comment by balupton** [comment]
Also interesting that all reports are for windows. Is anyone encountering this not on windows?

Will try and get a windoes VM going. Perhaps it is an issue with using colon in directory names, affecting the node resolution system or the npm bundles.

**Comment by ylecuyer** [comment]
I tried on ubuntu 18.04 with the exact same versions and I didn't had problems

**Comment by balupton** [comment]
Crossposted on the npm forum for advice

https://npm.community/t/packages-published-on-unix-with-in-filenames-fail-to-be-loaded-on-windows/1682?u=balupton

**Comment by balupton** [comment]
I'll see what they say. Regardless, I'll push up a workaround (using underscores instead of colons) tomorrow. Sorry for the stuff up everyone.

**Comment by balupton** [comment]
Hand got infected and had to return to Australia for treatment. Will be another day or so. I'm really sorry for the delays.

**Comment by mastermind3043** [comment]
+1 facing the same issue

**Comment by per2mn** [comment]
Also facing the same issue since many days (weeks?).
Seems that npm plugin  'editions' is not Windows compatible because of a ':' in the plugin name or dir???

**Comment by balupton** [comment]
Correct. I will get to it when I can, so far I have been too injured. Things are finally getting better though.

For the meantime, pin getmac to an earlier version.

**Comment by jung-kim** [comment]
@balupton Will downgrading to getmac@1.4.3 and locking it to that version work?

**Comment by balupton** [comment]
[getmac 1.4.6 is incoming](https://travis-ci.org/bevry/getmac/builds/423892845) which will resolve this issue

if you experience it again, clear your npm cache and try again

**Comment by guillaumedavidphd** [comment]
Looks like `ungit` is fixed for me.
