### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by sguillia** [FredrikNoren/ungit#1132]
Hello,

I've just installed ungit.

```
$ ungit           
Ungit server already running
Navigate to http://localhost:8448/#/repository?path=%2Fhome%2Fbilow
```

When I go to this URL I get this:
```
Connection refused
Description: Connection refused
```

There isn't any additional info.

How can I use ungit?

**Comment by jung-kim** [comment]
some details are missing but could you try this below? 

https://github.com/FredrikNoren/ungit/issues/1115#issuecomment-417947594
