### ISSUE TITLE
Ungit don't detect that a tag was pushed on the remote

### ISSUE THREAD

**Issue by gigi206** [FredrikNoren/ungit#1139]
Git tag **v1.0.0** and **v1.1.0** are pushed on the remote, but only tag **v1.0.0** is detected on the remote.

If I click on tag **v1.1.0** ungit displays the push button.

I have already tried to erase the tag **v1.1.0** from github and click push again with ungit but this is the same result.

```
$ git ls-remote --tags
From https://github.com/xxx/xxx.git
aeab362abe50f5e9ad8cf98b79e7cc522d2e8c97        refs/tags/v1.0.0
f6191bf1b622266a6928d667550f5c3a518357ad        refs/tags/v1.0.0^{}
3db2b40a60395c1944957fd3d345f2d2dbeb8dce        refs/tags/v1.1.0
```

Ungit see only one pushed :
![](https://image.ibb.co/npVjme/1.png)

![](https://image.ibb.co/m7D9Kz/2.png)

**Comment by jung-kim** [comment]
Is that your ungit? `https://github.com/xxx/xxx.git`

Because `https://github.com/FredrikNoren/ungit/tags` doesn't show v1.1.0 and I don't think it was ever published.

I think the wrong remote is targeted when you try to push the tag. When you push tag or branches, make sure correct remote is targeted in the remote section.  

This is a bit confusing part of the current UI and please let me know if you have any suggestions.

**Comment by gigi206** [comment]
I replace the true url with **xxx** but the remote exists. The remote is :
```
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/gigi206/VSCode-Anywhere.git
  Push  URL: https://github.com/gigi206/VSCode-Anywhere.git
  HEAD branch: master
  Remote branches:
    dev    tracked
    master tracked
    old    tracked
  Local branches configured for 'git pull':
    dev    merges with remote dev
    master merges with remote master
  Local refs configured for 'git push':
    dev    pushes to dev    (local out of date)
    master pushes to master (up to date)
```

We can see on previous images that the tag **v1.1.0** is only detected locally by ungit. And the tag **v1.0.0** is detected on the remote and locally by ungit. But we can see that tag **v1.1.0** exists on the remote :
```
$ git ls-remote --tags
From https://github.com/gigi206/VSCode-Anywhere.git
aeab362abe50f5e9ad8cf98b79e7cc522d2e8c97    refs/tags/v1.0.0
f6191bf1b622266a6928d667550f5c3a518357ad    refs/tags/v1.0.0^{}
3db2b40a60395c1944957fd3d345f2d2dbeb8dce    refs/tags/v1.1.0
```

**Comment by jung-kim** [comment]
You are asking why there is no remote `v1.1.0` tag right?

when you do `git ls-remote --tags` is `refs/tags/v1.1.0^{}` tag exists?

**Comment by gigi206** [comment]
> You are asking why there is no remote v1.1.0 tag right?

Yes

> when you do git ls-remote --tags is refs/tags/v1.1.0^{} tag exists?

**refs/tags/v1.1.0^{}** not exist

**Comment by jung-kim** [comment]
https://github.com/FredrikNoren/ungit/blob/master/components/graph/graph.js#L290

Ungit does look for that `^{}` tag and treat that as remote ref.  It is very strange that that is not happening here and I'm not aware of how a remote tag can be created such way as this is an exception I didn't think was possible.

Was creation of this remote tag some how different than normal?

**Comment by gigi206** [comment]
> Was creation of this remote tag some how different than normal?

No I push the tag with Ungit. I have already try to delete and create the same tag but I have the same issue.

**Comment by jung-kim** [comment]
#1144 is created to fix this issue.

What version of git are you running on?  I think newer version of git changed how the remote tag refs are working and this is confusing the heck out of me.

**Comment by gigi206** [comment]
Thank you for the fix :+1: 
Actually I use 2.19.1 (included in my project VSCode-Anywhere)

I will test when @Hirse will update the VSCode extension.

**Comment by gigi206** [comment]
It works, thank you to both of you :+1:
