### ISSUE TITLE
how to reverse or reset a commit in ungit?

### ISSUE THREAD

**Issue by zzzgit** [FredrikNoren/ungit#1140]
how to reverse or reset a commit in ungit?

**Comment by LosEagle** [comment]
soft reset - click on commit, click on "uncommit" button
hard reset - click on branch, click on "move" button next to commit you wish to reset to
revert - click on commit, click on "revert" button

**Comment by zzzgit** [comment]
why not use `reset` instead of `uncommit` and `move`?
they are confusing

**Comment by jung-kim** [comment]
There are many ways to do it, quite frankly easiest would be simply move active branch to a previous one.

Admittedly, documentations of these operations are needed and it is something that can be improved.  I would normally recommend cloning a test repo and clicking around as git is quite durable.
