### ISSUE TITLE
Configure Path and filename of the git executable

### ISSUE THREAD

**Issue by Hirse** [FredrikNoren/ungit#1151]
Based on https://github.com/Hirse/vscode-ungit/issues/63, is it possible to set the path to git as a CLI parameter?
```sh
ungit --gitPath=/a/b/c/git
```

**Comment by jung-kim** [comment]
Hm, it sounds more like the navigation part of the ungit within vs code right?

You could extract `git.path` and pass it to the url to navigate to it? `http://127.0.0.1:8080/#/repository?path=%2Fgit%2Fpath`


There is also the `forcedLaunchPath` [config](https://github.com/FredrikNoren/ungit/blob/master/source/config.js#L57)

**Comment by Hirse** [comment]
This is not about the path to the repository, but the path to the git executable like `C:\\Users\\Hirse\\AppData\\Local\\Programs\\Git\\cmd\\git.exe`.

I think the use case from the linked issue is using VSCode with Ungit without installation (or from a USB drive). In that case, git might not be in the path, so they would like to set the path to it.

**Comment by Hirse** [comment]
I guess this was done in https://github.com/FredrikNoren/ungit/commit/dbd54ad28400234aff35ff6b52c129b171888feb for v1.4.36, right?
