### ISSUE TITLE
feature request: move current branch here 

### ISSUE THREAD

**Issue by capaj** [FredrikNoren/ungit#1161]
When you check out a branch which has not been comitted to in a long time it's required to scroll down to it in order to select it. This becomes very tedious if the branch is very far in history.

What I would like to see would be a way of moving the branch to a commit even without having to select the branch first.
So I could move it simply by checking it out via the right upper corner dropdown and selecting a commit:
![image](https://user-images.githubusercontent.com/1305378/48165309-7863e180-e2e5-11e8-80d2-88bc6f0dddde.png)

and selecting a new button `Move {Branch name} here`.

That would be awesome.

**Comment by jung-kim** [comment]
Git it self is a very flexible tool and it may not be the best to make ALL possibilities in a single action.  You could do with below right now, is this acceptable?

1. either `git branch -D ${branch_name}` or find the branch and click the "x" button to delete the branch
2. create new branch at the any node `${branch_name}`


<img width="562" alt="screen shot 2018-11-11 at 21 45 36" src="https://user-images.githubusercontent.com/5281068/48328906-2976be80-e5fb-11e8-9b39-bcd141172fc8.png">
