### ISSUE TITLE
Use node-watch instead of fs.watch

### ISSUE THREAD

**Issue by h3** [FredrikNoren/ungit#1164]
Aside from adding Linux support, it would also allow ignoring tempory files:

https://www.npmjs.com/package/node-watch

**Comment by campersau** [comment]
Unfortunately node-watch currently might exceed the maximum file watchers in big repros see https://github.com/FredrikNoren/ungit/pull/1313#issuecomment-618855555

**Comment by wmertens** [comment]
In the meantime nodewatch properly handles ignored directories, so I'll re-do my PR.

**Comment by wmertens** [comment]
See #1465
