### ISSUE TITLE
Public Analytics

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1170]
Anlytics are sent to Keen.io, Google Analytics, Sentry but there is no public dashboard.

Is there a way to have a public dashboard ? or read access to those services ?

cc @FredrikNoren

**Comment by ylecuyer** [comment]
ping @FredrikNoren

**Comment by jung-kim** [comment]
So there is a dashboard and it is now broken due to unpaid keen.io.  Other data points I don't know about
