### ISSUE TITLE
How do i UNinstall?

### ISSUE THREAD

**Issue by GAZ082** [FredrikNoren/ungit#1171]
Hey. How do i remove ungit? Installed via AUR in arch.

Thanks!

**Comment by campersau** [comment]
Looks like `pacman -R nodejs-ungit` should work if you are using [`nodejs-ungit`](https://aur.archlinux.org/packages/nodejs-ungit/).

See https://wiki.archlinux.org/index.php/Pacman#Removing_packages

(Note: this package is maintained by the community.)

**Comment by GAZ082** [comment]
Thanks!

**Comment by unbeatable-101** [comment]
Or `sudo npm uninstall ungit` on macOS after CDing into the directory

**Comment by unbeatable-101** [comment]
Or `sudo npm uninstall -g ungit` on macOS after CDing into the directory
