### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/- - Not found

### ISSUE THREAD

**Issue by klawrawkz** [FredrikNoren/ungit#1186]
Was I **wrong** to try and install this?  ...I'm _new around here_... so I'm just askin'...

info using npm@6.8.0
info using node@v11.10.0

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>npm install - g ungit
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/- - Not found
npm ERR! 404
npm ERR! 404  '-@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!   <some-sorta-file-path>\2019-02-28T00_33_53_384Z-debug.log

----------------------
                 debug.log output                  
----------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\devCrPhoneDebug\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-',
1 verbose cli   'g',
1 verbose cli   'ungit' ]
2 info using npm@6.8.0
3 info using node@v11.10.0
4 verbose npm-session 3e9090f0df3c1fa8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/g 207ms
8 silly pacote tag manifest for g@latest fetched in 232ms
9 http fetch GET 404 https://registry.npmjs.org/- 246ms
10 http fetch GET 200 https://registry.npmjs.org/ungit 273ms
11 silly pacote tag manifest for ungit@latest fetched in 295ms
12 http fetch GET 404 https://registry.npmjs.org/- 100ms
13 silly fetchPackageMetaData error for -@latest 404 Not Found - GET https://registry.npmjs.org/- - Not found
14 timing stage:rollbackFailedOptional Completed in 1ms
15 timing stage:runTopLevelLifecycles Completed in 423ms
16 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/- - Not found
16 verbose stack     at res.buffer.catch.then.body (C:\Users\devCrPhoneDebug\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
16 verbose stack     at processTicksAndRejections (internal/process/next_tick.js:81:5)
17 verbose statusCode 404
18 verbose pkgid -@latest
19 verbose cwd C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
20 verbose Windows_NT 10.0.17763
21 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\devCrPhoneDebug\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-" "g" "ungit"
22 verbose node v11.10.0
23 verbose npm  v6.8.0
24 error code E404
25 error 404 Not Found - GET https://registry.npmjs.org/- - Not found
26 error 404
27 error 404 '-@latest' is not in the npm registry.
28 error 404 Your package name is not valid, because
29 error 404 1. name can only contain URL-friendly characters
30 error 404 Note that you can also install from a
31 error 404 tarball, folder, http url, or git url.
32 verbose exit [ 1, true ]

**Comment by Hirse** [comment]
@klawrawkz you seem to have a space between the `-` and the `g` making npm think that you are trying to install a package called `-` instead of `ungit` globally.

You should run `npm install -g ungit`.

**Comment by amirphp7** [comment]
npm install slate-image-plugin
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/slate-image-plugin - Not found
npm ERR! 404 
npm ERR! 404  'slate-image-plugin@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appdhaka\AppData\Roaming\npm-cache\_logs\2019-10-03T13_31_40_077Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'slate-image-plugin'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.11.1
4 verbose npm-session 364c19a45a65664d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/slate-image-plugin 1198ms
8 http fetch GET 404 https://registry.npmjs.org/slate-image-plugin 878ms
9 silly fetchPackageMetaData error for slate-image-plugin@latest 404 Not Found - GET https://registry.npmjs.org/slate-image-plugin - Not found
10 timing stage:rollbackFailedOptional Completed in 2ms
11 timing stage:runTopLevelLifecycles Completed in 19432ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/slate-image-plugin - Not found
12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid slate-image-plugin@latest
15 verbose cwd F:\wamp\www\twisker
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "slate-image-plugin"
18 verbose node v12.11.1
19 verbose npm  v6.11.3
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/slate-image-plugin - Not found
22 error 404
23 error 404 'slate-image-plugin@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by Hirse** [comment]
@amirphp7 I have no idea what you are trying to say or how that is related at all, but you might be looking for this:
```
npm install @slate-editor/image-plugin
```

**Comment by amirphp7** [comment]
Hello Pilzer,

Basically i am trying to build a slate react editor. All the b, i, u,
blockquote, code is working but i can't open file browser to click on image
icon and as well ul and ol list. I want to upload a image type file and
.pdf type file. The uploaded .pdf file would be downloadable. Would you
please assist me on that? Or have you any example which you can provide me.
Please, help me.

**Comment by amirphp7** [comment]
Hello Pilzer,

When I clicked on image icon it open the file browser. But after select an
image it comes up [SlateEditor][ImagePlugin]: Invalid response from server
in the console and no image render in the editor body. please help.

Regards,
MD. Amir Hossain.

**Comment by amirphp7** [comment]
Warning: Failed prop type: Invalid prop `signingUrl` of type `number`
supplied to `<<anonymous>>`, expected `string`.
    in Unknown (created by ImageButton)
    in ImageButton (at Home.js:79)
    in div
    in Unknown (at Home.js:71)
    in div (created by SlateEditor)
    in SlateEditor (at Home.js:70)
    in div (at Home.js:69)
    in Home (created by Context.Consumer)
    in Route (at App.js:16)
    in Switch (at App.js:14)
    in div (at App.js:12)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:11)
    in App (at src/index.js:7)

Regards,
MD. Amir Hossain.

**Comment by Hirse** [comment]
@amirphp7 I'm sorry, but I don't think I can help you with that.
Also, this is not the right place for that regardless.

@jung-kim, @campersau could you close this issue?

**Comment by umitozturk34** [comment]
check your proxy settings and firewall configurations. it's looks like not related to npm or node.js's modules.

have a nice day!

**Comment by campersau** [comment]
Yes, this does not look related to ungit.

**Comment by Vishnuvardhan-Kuragayala** [comment]
> @klawrawkz you seem to have a space between the `-` and the `g` making npm think that you are trying to install a package called `-` instead of `ungit` globally.
> 
> You should run `npm install -g ungit`.

yes  you re correct

**Comment by dhmorrison** [comment]
Yup, I think I was a bit punchy when that went down.  I didn't see the light, nor did I see the space.  Thanks for pointing that out.

-K

**Comment by atmanandsah** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/server-favicon - Not found
npm ERR! 404
npm ERR! 404  'server-favicon@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nodeauth'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sonu\AppData\Roaming\npm-cache\_logs\2020-01-23T09_47_32_734Z-debug.log

**Comment by TMsravan** [comment]
C:\Users\SRAVAN\Downloads\Datta-able-angular-lite-vesrion-v8.2.3\lite-vesrion>npm install --save-dev @angular-devkit/build-angularng serve -o
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@angular-devkit%2fbuild-angularng - Not found
npm ERR! 404
npm ERR! 404  '@angular-devkit/build-angularng@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SRAVAN\AppData\Roaming\npm-cache\_logs\2020-01-27T07_45_42_983Z-debug.log

C:\Users\SRAVAN\Downloads\Datta-able-angular-lite-vesrion-v8.2.3\lite-vesrion>

**Comment by campersau** [comment]
@atmanandsah did you mean https://www.npmjs.com/package/get-favicon ?
@TMsravan did you mean https://www.npmjs.com/package/@angular-devkit/build-angular ?

Since the latest comments are also unrelated to ungit I am going to lock the conversation on this already closed issue.
