### ISSUE TITLE
ungit should always run git commands in english

### ISSUE THREAD

**Issue by yukulele** [FredrikNoren/ungit#1187]
If system is not configured in english:
- Ungit show wrong error message
- it sometimes displays an error when there is none (for example when changing branches)

(I suppose he parses git's answers to check that the process went well)

ungit should always run git commands in english

workaround: run ungit itself in english: 
```console
LANG=en_US ungit
```

**Comment by jung-kim** [comment]
https://github.com/FredrikNoren/ungit/pull/963

So I've tried it years ago but it didn't work out for me.  But feel free to have a a crack at it.  

[gitConfigArgument](https://github.com/FredrikNoren/ungit/blob/master/source/git-promise.js#L11) is an argument that get appended to all git commands.

**Comment by campersau** [comment]
Fixed by https://github.com/FredrikNoren/ungit/pull/1208#issuecomment-511027300
