### ISSUE TITLE
diff --numstat called always

### ISSUE THREAD

**Issue by vegesm** [FredrikNoren/ungit#1193]
Hi,

On some repos ungit is very slow for me, the underlying reason is that `git diff --numstat --` is very slow as the git repo has some slow filters. Since it is called frequently (i.e. even when I want to see just a diff for a file), every operation takes ages.

Is there a way to prevent calling `git diff --numstat --` that often? For example, it seems unnecessary when looking at old commits and diffing them

**Comment by jung-kim** [comment]
Interesting, are you saying doing `git diff` is consistently faster than `git diff --numstat` even outside of ungit?  For ungit, when it slows down does restarting ungit process help?

I will do some testing myself but one of the major performance hit due to cpu being taken over is addressed via #1192 so can you also try latest version?

**Comment by vegesm** [comment]
The problem is not that `git diff --numstat` is slower than `git diff`, it is that running `git diff` on the entire repo is slow (due to some custom filters I have and can not optimize further unfortunately). Running `git diff` on a single file is fast. The slowness is not due to ungit, it exists when calling git directly from the command line.

However, it seems `git diff` on the entire repo is called unnecessarily by ungit sometimes. I did a bit more debugging, and it seems that the /api/diff call to the backend generates the following calls to git (among others):

- `git diff --num-stat --` call on the entire repo, 
- `git diff --num-stat --cached --`
- `git diff -- <filename>`

The first call is very slow and makes the whole API call hang due to the above reasons. Also, it seems to be an unneeded command because the results of the `/api/diff` call only contain the results of the `git diff -- <filename>` call.

**Comment by jung-kim** [comment]
So i've been testing this around and it seems that it breaks test cases especially during the merge conflicts.  git status alone cannot give us the numstats that ungit is asking for as API doesn't return numstats.  And I do see the arguments about the slowness in big repos as I can see myself.

However, I'm having some hard time with coming up with an acceptable answer.

**Comment by vegesm** [comment]
Yeah, I don't think the `git.status` call in git-promise.js can be sped up easily. However, it seems possible to remove some calls to it. 

For example, [here](https://github.com/FredrikNoren/ungit/blob/0e9368a3c91c91371316669ceceb898fb790ab20/source/git-promise.js#L279) `git.status` is called to detect whether a file is already tracked or not, if I understood correctly. For that use case calling numstats on the entire repo is unnecessary, a simple `git status file` would be enough. Changing only that would be already a huge benefit.

Looking at the code, it seems git.discardChangesInFile and git.commit can be optimised this way as well. As for the frontend needing the numstats, I think that's fine, it is called parallell anyway so there is no noticeable slowdown.

**Comment by jung-kim** [comment]
I will play with `git status file` later to see if can reduce the overall call counts but have you tried out #1194?  does this help you?  

I've changed it so that it `/status` do `diff --numstat` only when there are unstaged files are detected by `diff-index HEAD`.

**Comment by vegesm** [comment]
I've tried it, it had no visible effect in practice, I almost always had unstaged files, except after a commit.

**Comment by jung-kim** [comment]
Ah I see.... Then I will try to come up with a replacement query rather than look for conditional one

**Comment by jung-kim** [comment]
Hi, so I could not find any more performant to get the numdiffs on unstaged files.  So I've added a config to disable if you wish to. #1194 will this be acceptable for your case?

**Comment by vegesm** [comment]
Hi, this seems to work pretty well! It makes looking at the diffs much faster. One additional idea: when showing the files to be selected for commit, ungit shows a 'New' or 'Removed' label next to the filename. For modified files it used to be the number of lines changed but with numstat turned off there is nothing displayed. It would be nice if it showed 'Modified', would make the whole view more consistent.

**Comment by jung-kim** [comment]
Sorry I forgot to mention that PR is updated and do you wanna have another go at it?

**Comment by vegesm** [comment]
Hi, yes, it looks good!
