### ISSUE TITLE
Fail to start ungit

### ISSUE THREAD

**Issue by farribeiro** [FredrikNoren/ungit#1197]
Output, in Windows 10 with nodejs v12.0.0 and installed via npm:
```
info: BugTracker set version: 1.4.43
info: BugTracker set user hash
## Ungit started ##

Took 30219ms to start server.
Navigate to http://localhost:8448/#/repository?path=C%3A%5CUsers ...
stderr: #
# Fatal error in , li
stderr: ne 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 00000059CAEFDB00
Stopped keeping ungit alive
```

**Comment by farribeiro** [comment]
See in output, but if I using node v12 suppose to be lastest npm

**Comment by jung-kim** [comment]
Oh sorry, don't know how I completely missed that. 

Admittedly ungit needs more testing in windows settings but this one seems like a very harsh failure and tests has been passing within windows so I'm confused about this.  I will try to replicate on my end but currently I'm not sure how best to proceed.

**Comment by farribeiro** [comment]
I upgraded to node to v12.2.0 and will try again soon

**Comment by farribeiro** [comment]
New version of node v12.2.0, npm v6.9.0 and new version of ungit v1.4.44 is up. Then is fixed to me.
