### ISSUE TITLE
bug in "server already running" check (edgecase)

### ISSUE THREAD

**Issue by simonwiles** [FredrikNoren/ungit#1198]
There is a small bug in the launch script -- the check to see if the server is already running checks for a service listing on `config.port`, but checks on host `127.0.0.1` regardless of the value of `config.ungitBindIp`.

In my case, I tried running ungit with `authbind --deep ungit --ungitBindIp=127.0.0.2 --port=80 --no-launchBrowser` (and mapping `127.0.0.2` to "ungit" in `/etc/hosts`) -- this works fine unless something is listening on `127.0.0.1:80`, in which case the launch script decides that ungit is already running, and merely opens a browser window (not respecting `--no-launchBrowser` either, fwiw).

The fix is to add `config.ungitBindIp` to the `server.listen` call on line 90 of the launch script.  Would you accept a pull request?

Thanks for ungit, it makes my life easier!

**Comment by campersau** [comment]
This was fixed by https://github.com/FredrikNoren/ungit/pull/1217 a few months ago.
