### ISSUE TITLE
Issue with renamed and modified files

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#1201]
I had already noticied that renamed files were not handled in the diff view of a commit but this was not a big issue.

However today I've got the case with a file that as been renamed and had its contents modified and the diff was not displayed: 

![Screenshot_2019-05-21_16-23-52](https://user-images.githubusercontent.com/1866809/58104453-1a457e80-7be5-11e9-8fb1-497d8c1e3672.png)

**Comment by campersau** [comment]
For me this looks like a duplicate of https://github.com/FredrikNoren/ungit/issues/1175 .
