### ISSUE TITLE
Can tags be added or applied through ungit?

### ISSUE THREAD

**Issue by SwingsetTheory** [FredrikNoren/ungit#1207]

**Comment by jung-kim** [comment]
![add-my-tag](https://user-images.githubusercontent.com/5281068/60903360-03ef9280-a226-11e9-8ee9-e518a5af1a9c.gif)

**Comment by jung-kim** [comment]
You mean like that?

**Comment by SwingsetTheory** [comment]
Thanks!

**Comment by SwingsetTheory** [comment]
wait how do I apply the tag to other commits? When i type the same thing in that window it tells me that the tag already exists and gives an error.

**Comment by jung-kim** [comment]
Tag is very similar to branches and you need unique names.  if you have tag with same name you cannot create another tag with same name.

1. you can move the already existing tag to new commit
2. create a tag with different name
3. or delete tag (this is discouraged as tags are more of a persistent and permanent reference point)

**Comment by SwingsetTheory** [comment]
When you say move the tag, you mean remove it from one commit and put it on another? What use is a tag if I can only put it on one commit?

**Comment by jung-kim** [comment]
You could also drag and drop like branches.

Tag is meant to be semi permanent.  Its biggest use case is to represent a version within software.  

If I have a software with v0.2.3 or whatever, if the underneath code of v0.2.3 changes because somebody moved the tag.  Then you potentially have different codes for the v0.2.3 and integrity of what "a version of software" means is compromise and causes so many confusions.

https://git-scm.com/book/en/v2/Git-Basics-Tagging
https://stackoverflow.com/questions/1457103/how-is-a-tag-different-from-a-branch-in-git-which-should-i-use-here

**Comment by SwingsetTheory** [comment]
Okay I'm not sure if we're talking about the same thing.

In common usage as I understand it a "tag" is a thing that can be applied to many different things, so that one can search for a subset of the overall group using the tag.

This is how git tags work in Xcode, for example, and the GitHub desktop app.

So once a tag is created it can then be applied to an infinite number of commits, not only one.

If the ungit usage of tags is that they must be unique to one and only one commit, that can't really be called a "tag" in the same sense as it is used commonly, in my understanding.

**Comment by jung-kim** [comment]
Within the context of git, tag means [`git-tag`](https://git-scm.com/docs/git-tag).  Ungit is merely a UI representation on top of git, ungit itself didn't invent or develop the meaning of what `tag` means.  It was done within git and it merely gave UI to it's use case according to git. 

I'm not sure what Xcode does but what you have describe doesn't sounds like git feature, rather a xcode one, and sounds nothing like what tag means within the git context.

**Comment by SwingsetTheory** [comment]
I apologize, you are correct. I understand better how this is working now. Thanks for your help and understanding.
