### ISSUE TITLE
Switch to libgit2

### ISSUE THREAD

**Issue by MailYouLater** [FredrikNoren/ungit#1213]
There have been issues with ungit which stem from the fact that ungit calls git on a command line, and interprets its output. Most notably, there were issues if git was set to use a language other than English. See #959 & #963.

I suggest that you switch to [libgit2](https://libgit2.org/) to accomplish git tasks, instead of calling the `git` command for these functions, this would avoid any similar issues in the future.

**Comment by jung-kim** [comment]
so with #1208 multi lang shouldn't be an issue.  

There are other arguments for libgit2 and we've had discussions before #260 and it maybe worth to revisit again but yes it will be a big overhaul.

**Comment by MailYouLater** [comment]
Edited OP.

**Comment by wmertens** [comment]
I think this issue is just a duplicate of #260 and can therefore be closed.
