### ISSUE TITLE
Actual releases?

### ISSUE THREAD

**Issue by gerroon** [FredrikNoren/ungit#1218]
Hi 

Are there plans to make actual actual releases for platforms for those who are not familiar with node js stuff?

thanks

**Comment by campersau** [comment]
Yes, maybe we can start doing that again. We could even create release tags automatically during the build like the npm publishing .
Then we could fix our electron packaging and publish the resulting artifacts as github release via travis.
Which would also fix https://github.com/FredrikNoren/ungit/issues/1222

I have prepared something like that over here https://github.com/campersau/ungit/tree/testing
And here are example builds/releases with the electron artifacts:
- https://github.com/campersau/ungit/releases/tag/release-1.4.48
- https://ci.appveyor.com/project/campersau/ungit/builds/28557864/job/w5d4v4bci3i2ai6e/artifacts

@jung-kim what do you think?

**Comment by gerroon** [comment]
Thank you, I am testing it now.

**Comment by campersau** [comment]
We are now producing electron builds which don't require `node` or `npm`. They just need `git` to be installed. You can download them from here https://github.com/FredrikNoren/ungit/releases
