### ISSUE TITLE
Readme has no info about installing on Windows

### ISSUE THREAD

**Issue by NooneAtAll** [FredrikNoren/ungit#1220]
I'm complete noob. I don't know anything about Node or npm.
I came here in search of easy Git GUI.
I have read the Readme of this project
I have no idea how to install it on Windows

where do I put commands? isn't "sudo" the linux command? please help

**Comment by jung-kim** [comment]
Even for windows, [installation guide](https://github.com/FredrikNoren/ungit#installing) should still be applicable.  Part where it asks for sudo is if your system asks for it, and windows shouldn't.

so for you it should be 

```
1. npm install -g ungit
2. configure any if you want to (optional)
3. in terminal type `ungit`
```

**Comment by campersau** [comment]
We are now producing electron builds which don't require `node` or `npm`. They just need `git` to be installed. You can download them from here https://github.com/FredrikNoren/ungit/releases
