### ISSUE TITLE
Is there a compiled version of ungit?

### ISSUE THREAD

**Issue by adelriosantiago** [FredrikNoren/ungit#1222]
Is there a way to obtain a compiled version of it? I work under a proxy that won't allow to `npm install` most of the packages.

Thanks.

**Comment by campersau** [comment]
No, there currently aren't any compiled versions. But maybe we can add them, see https://github.com/FredrikNoren/ungit/issues/1218#issuecomment-548980020

**Comment by campersau** [comment]
We are now producing electron builds which don't require `node` or `npm`. They just need `git` to be installed. You can download them from here https://github.com/FredrikNoren/ungit/releases
