### ISSUE TITLE
Trying to install IntegralUI in my angular application

### ISSUE THREAD

**Issue by MonalisaNayak10** [FredrikNoren/ungit#1226]
I am trying to install IntegralUI in my angular application using command "npm install https://github.com/lidorsystems/integralui-web.git". But it is throwing error :

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/lidorsystems/integralui-web.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Monalisa\AppData\Roaming\npm-cache\_logs\2019-10-23T05_48_44_922Z-debug.log

**Comment by campersau** [comment]
Not sure if this is related to ungit.
It seems that git is missing and not ungit.

See https://stackoverflow.com/questions/19290899/git-is-not-installed-or-not-in-the-path
