### ISSUE TITLE
global install --set-home flag

### ISSUE THREAD

**Issue by yukulele** [FredrikNoren/ungit#1253]
to install (or update) ungit globally it is suggested to use the command: 
```
sudo -H npm update -g ungit
```
why should the `--set-home` (`-H`) flag be used?

**Comment by campersau** [comment]
It is only suggested if your system requires root access for installing npm packages globally.
Here is some more information regarding that which also includes the [`-H` solution](https://stackoverflow.com/a/37178615): https://stackoverflow.com/q/16151018
