### ISSUE TITLE
Git log for merge / empty commits does not work correctly

### ISSUE THREAD

**Issue by campersau** [FredrikNoren/ungit#1270]
Based on https://github.com/FredrikNoren/ungit/pull/1262#issuecomment-581139604 I have found issues in the updated git parser from https://github.com/FredrikNoren/ungit/pull/1262 where merge / empty commits are no longer parsed correctly.

---

Merge commits with multiline text were outputed like this before:
```
commit 621a04f931ea9007ac826c04a1a02832e20aa470
Merge: 4e5d611f e2dc3ef6
Author: campersau <>
Date:   Wed Jan 29 12:07:38 2020 +0100

    Merge pull request #1268 from campersau/prepare_152

    Prepare version 1.5.2

4       1       CHANGELOG.md
1       1       package-lock.json
1       1       package.json
8       6       source/git-parser.js

commit e2dc3ef6e2cbf6ab0acb456c0837257dc01baafd
```

But with the `-z` option they are outputed as:
```
commit 621a04f931ea9007ac826c04a1a02832e20aa470
Merge: 4e5d611f e2dc3ef6
Author: campersau <>
Date:   Wed Jan 29 12:07:38 2020 +0100

    Merge pull request #1268 from campersau/prepare_152

    Prepare version 1.5.2
\x004     1       CHANGELOG.md\x001 1       package-lock.json\x001    1       package.json\x008 6       source/git-parser.js\x00\x00commit e2dc3ef6e2cbf6ab0acb456c0837257dc01baafd
```
The problem here is that there is no new line after the commit message.

---

Empty commits with multiline text were outputed like this before:
```
commit 868962b341b31bd2d06035e5b365b0a50d2f9278
Author: campersau <>
Date:   Sun Feb 2 17:56:36 2020 +0100

    empty commit

    message content

commit 2a583a26dd8cee2f9569ae0320b5681e23afc02e
```

But with the `-z` option they are outputed as:
```
commit 868962b341b31bd2d06035e5b365b0a50d2f9278
Author: campersau <>
Date:   Sun Feb 2 17:56:36 2020 +0100

    empty commit

    message content
\x00commit 2a583a26dd8cee2f9569ae0320b5681e23afc02e
```
The problem here is that there is no new line after the commit message and also the next line starts with `\x00commit` instead of `commit`.

**Comment by campersau** [comment]
cc @ylecuyer

**Comment by ylecuyer** [comment]
Thanks @campersau for handling this. I wasn't able to do so as I am on my way back from FOSDEM.
