### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by pogo555** [FredrikNoren/ungit#1272]
I'm running linux Mint 17.
Following the install instructions here, I got this result:
`npm http GET https://registry.npmjs.org/ungit
npm http GET https://registry.npmjs.org/ungit
npm http GET https://registry.npmjs.org/ungit
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ungit"
npm ERR! cwd /home/pogo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pogo/npm-debug.log
npm ERR! not ok code 0
`
The debug file contents are:
 
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '-g', 'ungit' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'ungit', null ]
5 verbose cache add name=undefined spec="ungit" args=["ungit",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'ungit',
6 verbose parsed url   path: 'ungit',
6 verbose parsed url   href: 'ungit' }
7 silly lockFile b5f3d853-ungit ungit
8 verbose lock ungit /root/.npm/b5f3d853-ungit.lock
9 silly lockFile b5f3d853-ungit ungit
10 silly lockFile b5f3d853-ungit ungit
11 verbose addNamed [ 'ungit', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 8d18b492-ungit ungit@
14 verbose lock ungit@ /root/.npm/8d18b492-ungit.lock
15 silly addNameRange { name: 'ungit', range: '*', hasData: false }
16 verbose url raw ungit
17 verbose url resolving [ 'https://registry.npmjs.org/', './ungit' ]
18 verbose url resolved https://registry.npmjs.org/ungit
19 info trying registry request attempt 1 at 02:25:55
20 http GET https://registry.npmjs.org/ungit
21 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
22 info trying registry request attempt 2 at 02:26:06
23 http GET https://registry.npmjs.org/ungit
24 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
25 info trying registry request attempt 3 at 02:27:06
26 http GET https://registry.npmjs.org/ungit
27 silly lockFile 8d18b492-ungit ungit@
28 silly lockFile 8d18b492-ungit ungit@
29 error Error: CERT_UNTRUSTED
29 error     at SecurePair.<anonymous> (tls.js:1370:32)
29 error     at SecurePair.EventEmitter.emit (events.js:92:17)
29 error     at SecurePair.maybeInitFinished (tls.js:982:10)
29 error     at CleartextStream.read [as _read] (tls.js:469:13)
29 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
29 error     at EncryptedStream.write [as _write] (tls.js:366:25)
29 error     at doWrite (_stream_writable.js:223:10)
29 error     at writeOrBuffer (_stream_writable.js:213:5)
29 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
29 error     at write (_stream_readable.js:583:24)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Linux 3.13.0-24-generic
32 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ungit"
33 error cwd /home/pogo
34 error node -v v0.10.25
35 error npm -v 1.3.10
36 verbose exit [ 1, true ]
`

Any suggestions as to what I might try?

**Comment by campersau** [comment]
I think that is a problem with your network not beeing able to access `https://registry.npmjs.org/ungit`. Can you try to open the URL in the browser?
You can try to disable strict-ssl like this https://stackoverflow.com/a/22526046

Similar issue reported somes years ago: https://github.com/FredrikNoren/ungit/issues/201

**Comment by Hirse** [comment]
>npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10

Your node and npm versions are severely out of date, no longer maintained by node, and therefore not supported by ungit.

As an aside, even Linux Mint 17 support ended April 2019.

**Comment by pogo555** [comment]
> > npm ERR! node -v v0.10.25
> > npm ERR! npm -v 1.3.10
> 
> Your node and npm versions are severely out of date, no longer maintained by node, and therefore not supported by ungit.
> 
> As an aside, even Linux Mint 17 support ended April 2019.

Thanks. I'm testing LM 18 with a view to updating. LM 17 has worked fine on my netbook but LM 18 is slow...

I have no idea where these  live, what versions they are or how to update them. I've run the updates as they come in. A look with the package manager doesn't list either as available for update. 

I'll live with them until I get a later linux.

**Comment by Hirse** [comment]
Updating Node should be enough (npm comes bundled). You can have a look here how to do it:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages

If you just want to run ungit, you could also try the electron installer from here:
https://github.com/FredrikNoren/ungit/releases
It comes with node bundled and only requires you to have git installed.

**Comment by pogo555** [comment]
Thanks @Hirse . I had to install curl, but the upgrade went well.

**Comment by Hirse** [comment]
Were you able to run ungit then? 😃

**Comment by pogo555** [comment]
> Thanks @Hirse . I had to install curl, but the upgrade went well.

I'll retract that. I tried to install ungit after the node and npm update and got the same errors. A close look revealed the same old versions of node and npm.

I didn't need another hobby. I've made enough progress with git-gui to not need to install ungit. I'll poke at the node install when I get bored.

Thanks for your help.
