### ISSUE TITLE
I love this app! Will donate

### ISSUE THREAD

**Issue by ovikholt** [FredrikNoren/ungit#1276]
If you fix these two bugs I will donate 1000 kroner

- When I load a repository, it shows branch and tag names on the commits, but after 1 or 2 seconds, it reloads (animated by a speed stripe at the top), and the names disappear!! Super frustrating.
- After i did npm install -g ungit today, to see if maybe that other bug had been fixed, it now fails with a Whooops page, for any repository.

**Comment by jung-kim** [comment]
can you provide browser console logs and terminal backend log?

**Comment by ovikholt** [comment]
How can I see the logs? In the current version, it detaches right after starting ungit. It didn't do that before. Before I had to do `ungit &` and `disown %1`.

**Comment by jung-kim** [comment]
Easiest log to extract is the browser log, you could share the browser inspector's console outputs

**Comment by ovikholt** [comment]
I sent this a long time ago through email but it didn't arrive :o Sorry about that
https://drive.google.com/file/d/1EY1zn9AekwYOQSafXQGznWvC0hCa-JWY/view?usp=sharing

**Comment by campersau** [comment]
This looks like something I had fixed in version 1.5.3 https://github.com/FredrikNoren/ungit/issues/1270 .
Which version do you use? Can you share a link to the repo?

**Comment by ovikholt** [comment]
I was running 1.5.4, but with another npm install -g ungit I got 1.5.5 and
now the problems is gone! Thank you. I have to be a man of my words, so,
let me know if you want the money and how.
    <https://gobistories.co/>


*OLA BRUNBORG VIKHOLT**CTO  |  Gobitech AS*
(+47) 40099958
Hegdehaugsveien 34, 0352 Oslo

**Comment by jung-kim** [comment]
It's fantastic that it is resolved.  

I obviously was not involved and do not deserve it at all.  However I just want to be explicit and clearly state that I do not wish to receive this reward.  I hope those who deserves this rewards can approach it freely.

@ovikholt thank you for the support
