### ISSUE TITLE
forcedLaunchPath of null fails to work

### ISSUE THREAD

**Issue by martinmcclure** [FredrikNoren/ungit#1281]
source/config.js says 
```
// Instead of launching ungit with the current folder force a different path to be used. Can be set to null to force the home screen.
  forcedLaunchPath: undefined,
```
However, putting the line
`"forcedLaunchPath": null,`
in .ungitrc results in a browser tab being opened on
http://localhost:8448/#/repository?path=null
which complains 
```
Invalid path
"null" doesn't seem to be a valid path.
```
Seems like the new tab should instead open on
`http://localhost:8448/#/`
when forcedLaunchPath is set to null. This is a useful feature. I have a simple candidate fix for this; I'll create a PR shortly.

**Comment by campersau** [comment]
fixed by #1282
