### ISSUE TITLE
A way to squash commits

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#129]
Suggested by @slang800 in #92

**Comment by jcowgar** [comment]
Drag one commit into another and then click "squash"? by @Ajedi32 is the best suggestion. Start simple and see where it goes from there.

Other git clients when doing a squash merge will simply call git merge --squash branch-name. That then leaves the git repo in an uncommitted state. They will then simply switch to the build in commit view and let the developer take it from there.

This would be a fantastic addition to ungit.
