### ISSUE TITLE
diff out is not properly escaping 

### ISSUE THREAD

**Issue by bes-internal** [FredrikNoren/ungit#1387]
Sometimes diff pane is suffering from properly html (to say user input) escaping:

![Screenshot_4](https://user-images.githubusercontent.com/2046529/85308387-d55fdb80-b4b9-11ea-8977-ec835bd3bde8.png)

real diff
![Screenshot_3](https://user-images.githubusercontent.com/2046529/85307963-45ba2d00-b4b9-11ea-810e-fcc611bf1965.png)

ungit v1.5.7

**Comment by campersau** [comment]
Thanks for the report. It seems to be a bug with `diff2html` so I opened https://github.com/rtfpessoa/diff2html/issues/324

**Comment by campersau** [comment]
Fixed by https://github.com/FredrikNoren/ungit/pull/1385
