### ISSUE TITLE
Ungit crashing after a few seconds

### ISSUE THREAD

**Issue by GautierT** [FredrikNoren/ungit#1455]
Hi. 

`ungit` is crashing after a few minutes like this : 
```
2020-12-18T09:24:36.129Z - error: Error: read EFAULT
    at Pipe.onStreamRead (node:internal/stream_base_commons:213:20)
Stopped keeping ungit alive
```

I have the same problem with `nodemon` (https://github.com/remy/nodemon/issues/1812) for my nodejs process. Maybe it's related to the fact that i am on a Apple Silicon processor ?

Thanks

**Comment by campersau** [comment]
How do you start ungit? Via commandline (which arguments / node version?) or using the electron package?
Could you please try out the `ungit-darwin-arm64.zip` build from https://github.com/FredrikNoren/ungit/releases/tag/v1.5.14

**Comment by GautierT** [comment]
Hi @campersau . thanks for looking into this. i start ungit from the cli.
`node -v` : v15.4.0
`ungit -v`: 1.5.13+dad9659

i installed ungit using `npm install -g ungit`.

i will test the arm64 electron package and come back to you

**Comment by GautierT** [comment]
hey!
I switch to arch -x86_64 zsh (so the rosetta 2 emulator instead of native) and it seems to fix it. So i guess it's problem with nodejs on arm.
Sorry for the trouble !
