### ISSUE TITLE
simple git flow breaks ungit

### ISSUE THREAD

**Issue by Console32** [FredrikNoren/ungit#1460]
I was trying to create a graphical representation of our git workflow. I used the following commands to create the history

```
git init                                                              
git commit --allow-empty -m 'Initial commit'                  
git checkout -b dev                                           
git checkout -b features/A                                     
git commit --allow-empty -m 'implement feature A'         
git commit --allow-empty -m 'implement feature A'         
git checkout dev                                          
git checkout -b features/B                                     
git commit --allow-empty -m 'implement feature B'         
git commit --allow-empty -m 'implement feature B'         
git checkout dev                                          
git merge --no-ff features/A                               
git merge --no-ff features/B                                   
```

The resulting graph looks like this in my CLI:
![image](https://user-images.githubusercontent.com/4870099/106240844-46603200-6205-11eb-8cb7-095ef9b26561.png)

But ungit shows:
![image](https://user-images.githubusercontent.com/4870099/106240912-65f75a80-6205-11eb-992e-bf329e0eed5f.png)

I tried a fresh start - same result.

**Comment by antibunching** [comment]
I am facing the same issue, with ver1.5.11 on windows 10, and ver1.5.13 on Debian 10.

**Comment by wmertens** [comment]
This is what it looks like with #1315 : 
![image](https://user-images.githubusercontent.com/54934/109050132-59b5ce80-76d9-11eb-80eb-d1735d5afedd.png)
