### ISSUE TITLE
Support bare repositories

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#177]
Right now ungit crashes (#168) if you try to run it in a bare repository.

**Comment by mesosteros** [comment]
+1 for this. This feature would allow us to effectively have a sort of personal github/gitlab. It would be really useful for small teams. We'll be using normal repos for now but would appreciate this.

**Comment by michaelachrisco** [comment]
I am having the same issue with remote repos that may or may not be set up. Some of the errors are resolved if you run `ungit --no-autoFetch`

**Comment by codingtwinky** [comment]
Quite frankly, i thought this was fixed.  When i do `mkdir test; cd test; git init` and than going into test director didn't cause any errors for me.  What error are you seeing specifically?

**Comment by campersau** [comment]
@codingtwinky try `git init --bare`. For  local bare repositories ungits `quickstatus` just returns `"uninited"` (no errors).

**Comment by Ajedi32** [comment]
Yeah, "bare" is not the same thing as "empty". A bare repository is basically just the `.git` folder, with no working directory. It's often used on servers where a working directory isn't needed. (So you can push and pull from the repository, but the server doesn't need to a copy of the source at any given revision.)

**Comment by codingtwinky** [comment]
Sorry for my own incompetence that took forever to fix such easy fix.

It is should now support bare repo without any error messages but with disabled staging and stash as it is not applicable to bare repo.

**Comment by michaelachrisco** [comment]
Thanks @codingtwinky!
