### ISSUE TITLE
Can't use bitbucket with ungit

### ISSUE THREAD

**Issue by nielsene54** [FredrikNoren/ungit#202]
I am not able to push when using a repository from www.bitbucket.com.  It constantly repeats entering the password but never actually gets through to push or pull.

**Comment by skoam** [comment]
I just wanted to add that this issue still exists. The credentials-helper fails to authenticate on windows if ungit is launched via cmd.exe (node.js command prompt). The helper asks for a password to unlock your private key (id_rsa) but fails to actually unlock the key.

You can bypass this issue by launching ungit from Git Bash (that comes with msygit). I configured my Git Bash to unlock the key at launch, so the authentification is already done like it would be on linux, were you would launch ungit from bash either.

**Comment by FredrikNoren** [comment]
@skoam hm ok, but that's not bitbucket specific is it? Does sound like something that should at least be on the known issues list though
