### ISSUE TITLE
Update Ungit UI when the repository is modified by command line git or other tools

### ISSUE THREAD

**Issue by Ajedi32** [FredrikNoren/ungit#283]
I have many tools I use besides ungit that integrate with git. Currently, if I make changes to the repo with any of these tools, I have to refresh Ungit to see the changes there.

That's not too big of a deal, but it would be nice if Ungit handled this in the background somehow so I don't have to worry about whether what I'm looking at is really the current state of the repository.

**Comment by brettswift** [comment]
This is a couple of years old..but I'd love this as well. 

I teach a .git course at work every once in a while and like http://learngitbranching.js.org/ this would be a great tool but to visualize the repo changing at the front of the room on a big display :)

**Comment by codingtwinky** [comment]
@brettswift #809 is merged I think we should be good as we are entire folder recursively and watching `.git` and `.git/refs` in the cases where recursive watches doesn't work. 

Will be closing it for now but please let me know if there any other operations that may not work.

shoutout to @Ajedi32 for guiding me through this.
