### ISSUE TITLE
Handle long file paths in the staging area in a slightly better way

### ISSUE THREAD

**Issue by jwir3** [FredrikNoren/ungit#317]
When ungit has files stages where the file paths are quite long, it handles them, but it might make more sense to handle them in a better way (e.g. reducing font size, breaking up files by directory, breaking lines at intelligent places, etc) to make the files more easily readable. (See the image below for what I mean)

![screen shot 2014-02-26 at 5 14 09 pm](https://f.cloud.github.com/assets/997106/2277096/d3790f70-9f3b-11e3-8afe-35e2b04427ab.png)

Also, it would be nice if files next to each other in the staging list had alternating light/dark backgrounds. That way, it would be easier to tell which name goes with which checkmark when indicating whether or not to add them to the commit.

**Comment by codingtwinky** [comment]
As a java dev I run into this a lot my self.  


But I don't want to do something like (this)[http://www.w3schools.com/cssref/tryit.asp?filename=trycss3_js_text-overflow] as this would hide the end of the line but end of the line is the important part for me.  

Does anybody have any ideas?

**Comment by Ajedi32** [comment]
Well, if you want to ensure that the full text is shown, I'd recommend a combination of [`word-wrap: break-word;`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap) with [`<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) tags inserted after every slash. [Example](http://jsfiddle.net/Ajedi32/b5ygdxbp/)

Or, if you want to keep everything on one line, but want the text to be cut off with an ellipsis on the right, you can use [`white-space: nowrap;`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space), with [`text-overflow: ellipsis;`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow), [`direction: rtl;`](https://developer.mozilla.org/en-US/docs/Web/CSS/direction), and [`text-align: left;`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align). [Example](http://jsfiddle.net/Ajedi32/f2p8kvvj/1/)

**Comment by jwir3** [comment]
I guess I'd probably disagree, since the rightmost part of the file path (for RTL text) is the most significant. It'd probably be better to hide the left part of the path, IMO.

**Comment by jwir3** [comment]
Sorry, @ajedi32, I read your proposed solution as "text cut off on the right". My bad.

**Comment by Ajedi32** [comment]
@jwir3 Actually, that might be my fault. My post actually *did* say "on the right" when I originally posted it. I edited it a few minutes afterwards to fix that mistake. So if you read my message in your email before going to the site to reply that would explain the misunderstanding.

Anyway, `direction: rtl;`, and `text-align: left;` will result in the ellipses being on the left.
