### ISSUE TITLE
Laravel Vendor make ungit crash

### ISSUE THREAD

**Issue by kenmaclord** [FredrikNoren/ungit#407]
Hello,

when starting with a fresh Laravel install, if I try to add and commit my whole project, ungit crashes down, probably because there are too much files to add (~3500) in the vendor directory.

Just a notice.

Ken

**Comment by campersau** [comment]
Similar to https://github.com/FredrikNoren/ungit/issues/432 closed by https://github.com/FredrikNoren/ungit/pull/508
