### ISSUE TITLE
When other branches get far ahead of your current one, your current branch is not displayed

### ISSUE THREAD

**Issue by hirden** [FredrikNoren/ungit#420]
When you are on a branch which then get passed in commits by another remote, your current "branch track" is not displayed.
![ungit issue](https://cloud.githubusercontent.com/assets/82352/3810770/00bb233e-1c95-11e4-9e22-03e02284e85f.PNG)

**Comment by daedalus28** [comment]
I know this is an old ticket, but I wanted to bring this up as I have a use case where scrolling isn't really viable. In my project I have some branches that are very far behind and when switching to them (using the fancy new branch picker dropdown :smile:), I can't see the current commit to merge in the latest version of the main branch. These branches are few months behind and there are so many commits to scroll though that I really can't find it and have to jump to the command line to make it work.

The commit collapsing idea is cool, but even a "jump to" or just "load n more months of history" command would do it.
