### ISSUE TITLE
Really slow to handles lot of new filesto commit (~4000)

### ISSUE THREAD

**Issue by eucalyp** [FredrikNoren/ungit#432]
I changed the name of a wordpress folder. So it's about 4000 files to commit and ungit is really slow (2mn to generate the diff) and even crash to create the diff or to commit (once the diff succeed). I don't know what is the bottleneck. For information, I have a ssd installed on my computer, so the hard drive is not the problem.

**Comment by campersau** [comment]
Should have been closed by https://github.com/FredrikNoren/ungit/pull/508
