### ISSUE TITLE
Confirmation before Delete and Reset

### ISSUE THREAD

**Issue by jamesjnadeau** [FredrikNoren/ungit#460]
I've accidentally clicked these buttons before and had to go back to the command line(gasp) to fix it :) 

Some kind of confirmation would fix this issue.

In the simpilist form, and confirm() would work.

Ideally I think it would change the delete button on click to "are you sure?", with another click confirming the action.

I hope to work on this in the coming weeks, as I use ungit daily, and am want to see how it works :)

similar to the request in #387 

ps Great work, love this thing :+1:

**Comment by mrametharam** [comment]
How was this resolved? I just clicked on delete and it deleted without confirming. Showing a button to restore the branch after it has been deleted is not really a solution unless, I still have that option even after I've closed my browser and realized my mistake.
