### ISSUE TITLE
ChromeApp version

### ISSUE THREAD

**Issue by kasajian** [FredrikNoren/ungit#468]
I'm curious if anyone is interested in porting this to ChromeApp so that it it's easier to install and show up in the ChromeApp store?

**Comment by futagoza** [comment]
To port this to a chrome app you would need to split the current ungit project into 2 or 3 projects: 
* Project 1 would be the server side project, providing a restful interface and library api
* Project 2 would be the ChromeApp based UI Frontend that connects to any Project 1 servers
* Project 3 (this repo?) using Project 1 and a server based client to provide the current ungit experiance

**Comment by campersau** [comment]
Chrome Apps are discontinued https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html
