### ISSUE TITLE
User Authentication - Example?

### ISSUE THREAD

**Issue by shakna-israel** [FredrikNoren/ungit#489]
Using .ungitrc you can enable authentication, for a specific set of users and passwords, however, how exactly would you define said users?

For example:

{
    "authentication": true,
    "users": ?
}

**Comment by FredrikNoren** [comment]
@shakna-israel An example would be:

```JSON
{
 "authentication": true,
 "users": {
  "some_username": "whatever_password_you_want"
 }
}
```
