### ISSUE TITLE
Plugin Proposal: Git Sounds

### ISSUE THREAD

**Issue by danielstern** [FredrikNoren/ungit#491]
How about a plugin that generates a series of tones based on your commit tree (using web audio), so you can hear your repository?

**Comment by codingtwinky** [comment]
As far as I know Ungit doesn't permanently checks git repo on the background.  It checks git repo in certain intervals when ungit view is on focus.

So if you want something that give you real time alert's on git repo change while you are working on something else, that require more changes on how ungit works.

If you want to hear your git action as you make the change, I think that is little annoying.

If you want ungit to play [Rick Roll](http://en.wikipedia.org/wiki/Rickrolling) users when users try to certain inadvisable operations, such committing to a detached head, I'm all for it.

**Comment by Ajedi32** [comment]
It sounds to me like he wants to generate music based on his commit tree. Not really meant to be a serious feature, more of a "just for kicks" kind of thing.

**Comment by codingtwinky** [comment]
You mean something like [this](https://code.google.com/p/gource/) but for sound?  That is little odd...

**Comment by shingonoide** [comment]
Very funny

**Comment by FredrikNoren** [comment]
@danielstern Give it a go, it's should be fairly easy to add a plugin ;)
