### ISSUE TITLE
Optimist Deprecated

### ISSUE THREAD

**Issue by shakna-israel** [FredrikNoren/ungit#504]
[Optimist](https://github.com/substack/node-optimist), what ungit is using as the parser for commandline arguments was deprecated about a year ago.

There's [minimist](https://github.com/substack/minimist) and [yargs](https://github.com/chevex/yargs), which are both currently maintained as alternatives.

Yargs tends to be the more popular, despite having to suffer the pirate talk.

**Comment by campersau** [comment]
ungit already uses `yargs` since https://github.com/FredrikNoren/ungit/pull/480 got merged.
But the [README.md](https://github.com/FredrikNoren/ungit/blob/master/README.md) was not updated accordingly.

**Comment by codingtwinky** [comment]
I enjoyed pirate talk, I found their documents to be more engaging as a dyslexic kid.

And will be updating ungit doc later to include some of the updates.
