### ISSUE TITLE
Commit on enter key

### ISSUE THREAD

**Issue by Febalist** [FredrikNoren/ungit#509]
Can you add hotkeys for submit commit form? Title input can listen `enter` key, body textarea `ctrl+enter`.

**Comment by FredrikNoren** [comment]
Fixed by @codingtwinky, will go out with the next release

**Comment by chneau** [comment]
For the input, could it be both `enter` and `ctrl+enter` ? For the moment it's only listening on `enter`. Listening to `ctrl+enter` too could give some consistency I guess. (Plus, it's similar to VSCode commit box too)

**Comment by jung-kim** [comment]
Can you please create separate issue?
