### ISSUE TITLE
Credentials unathorized ip

### ISSUE THREAD

**Issue by bensagardoy** [FredrikNoren/ungit#522]
I have this message when i try to push to or fetch from my distant repository (bitbucket in this case) :
`2015-04-01T15:15:55.630Z - info: Trying to get credentials from unathorized ip: ::ffff:127.0.0.1`

I found the "if" test in the file git-api.js, line 559 :
```javascript
if (req.ip != '127.0.0.1') {
  winston.info('Trying to get credentials from unathorized ip: ' + req.ip);
  res.status(400).json({ errorCode: 'request-from-unathorized-location' });
  return;
}
```

I didn't have this message before, just since a few days now.

**Comment by FredrikNoren** [comment]
Thanks for the fix for this, will be released shortly
