### ISSUE TITLE
On windows lots of cmd windows

### ISSUE THREAD

**Issue by PedroKTFC** [FredrikNoren/ungit#531]
I've just upgraded to the latest version (0.9.1) on WIndows and although it is working, it's throwing lots of cmd windows, each running cmd.exe. I've never seen one cmd window before, let alone lots!

**Comment by betsegaw** [comment]
I see this as well. But on top of that, it freezes while fetching from the remote so I never get past the loading screen.

**Comment by campersau** [comment]
Yes, I have the same Problem here.

```
$ ungit --version
ungit version: 0.9.1
```

```
$ git --version
git version 1.8.3.msysgit.0
```

```
$ node --version
v0.10.31
```

```
$ npm --version
1.4.23
```

```
$ systeminfo
OS Name:                            Microsoft Windows 8.1 Pro
OS Version:                         6.3.9600 Build 9600
Systemtyp:                          x64-based PC
```

**Comment by codingtwinky** [comment]
err...  Do you have any logs that you can share?  0.9.0 has quite a problem...

**Comment by FredrikNoren** [comment]
@codingtwinky Yeah same comment as I posted in the other thread here: could be spawn related

**Comment by codingtwinky** [comment]
I'm little modified on the fact that I might have to do tedious process of converting from spawn to exec...

But I can't find anything on the web about spawn having this kind of behaviors in windows.  But when document says it is making new process, it could mean that.  

I may have to go pick up a window box from craigslist or something to start testing...

**Comment by betsegaw** [comment]
Not sure why its showing this new behavior. It was working without spawning windows earlier. Must be either a recent change you made or because of some update to node.

**Comment by renkun-ken** [comment]
I have exactly the same problem with @betsegaw.

**Comment by FredrikNoren** [comment]
I tried using .exec instead but it still seems to open extra windows. 0.8.4 with the exact same setup does not open extra windows

**Comment by FredrikNoren** [comment]
Ok seems like it's not the git.js exec/spawn that's to blame, something else seems to be opening those windows and I'm not sure what

**Comment by ginus** [comment]
+1

**Comment by tornade69** [comment]
+1

**Comment by FredrikNoren** [comment]
Ok this seems to fix this problem at least: https://github.com/FredrikNoren/ungit/pull/538
Still a couple more issues on windows though
