### ISSUE TITLE
Why js files in public directory is ignored?

### ISSUE THREAD

**Issue by erayalakese** [FredrikNoren/ungit#535]
I just made a few improvements about UI of **ungit** . So I've modified /public/js/ungit.js file but I couldn't made a commit and sent it as PR to you. Because this file is ignored by .gitignore. What I'm missing? Why it's ignored?

**Comment by codingtwinky** [comment]
so pretty much all files under /public is generated via `grunt`.  ungit.js file is composed of components folder and some of the source files.  

https://github.com/FredrikNoren/ungit/blob/master/CONTRIBUTING.md this has more info

**Comment by erayalakese** [comment]
My mistake. Thanks. @codingtwinky
