### ISSUE TITLE
Most recent commit diffs don't open

### ISSUE THREAD

**Issue by mesosteros** [FredrikNoren/ungit#541]
New issue: the most recent commit does not show me the diff for each file when I click it. However if the commit isn't the most recent, it does:

![commit diff](https://cloud.githubusercontent.com/assets/1943233/7249325/7ac4b7ec-e811-11e4-9e52-7924345ce422.gif)

The cursor is off in the gif because of the gif capturing software. I'm clicking the file names.

**Comment by codingtwinky** [comment]
I just checked out 0.9.2 and i don't see this in mac...  Do you see any errors on server or browser log?

**Comment by mesosteros** [comment]
No errors. This is in Windows 8.1 x64 bits.
Turns out it isn't the most recent commit: just some commits. I have no idea why though.
Server shows no errors, and in the browser log I only get these (which are not errors:

Fire change event due to re-activity
Event: Object {event: "working-tree-changed"}
Event: Object {event: "init-tooltip"}

**Comment by codingtwinky** [comment]
Could you please run this command `git diff fb049b55^^! -- getYourTarget/client/lib/router.js` at `C:\users\mesos_000\Desktop\Projects` and share the output?  also could you try with single carrot as well just like this?  `git diff fb049b55^! -- getYourTarget/client/lib/router.js`

**Comment by campersau** [comment]
I have the same issue on Windows 8.1 x64 that some diffs do not open.

I have tracked it down to these lines: https://github.com/FredrikNoren/ungit/blob/master/source/git.js#L59-L81
The `stdout` variable is empty if the `gitProcess` is closed. It looks like the child process starts so quickly that the `data` event handlers are attached too late to get called.

If I run the git comand in the command prompt I get the expected output.

---

Here is a test case to demonstrate the issue.
Create a new file in your ungit repository and run it with node. Toggle the two `commands` variables. to see the different results.
```js
var child_process = require('child_process');
var path = process.cwd(); // set this to the ungit repository path if the cwd is somewhere else

// not working commands
var commands = ['diff', 'e6f115fcdedd97fb68701614bd85b368c1a1f53c^^!', '--', 'components/stash/stash.js'];
// working commands
//var commands = ['diff', '34e717f76a195582501e038567b47e083827a07f^^!', '--', 'source/git-parser.js'];

var gitProcess = child_process.spawn('git', commands, { cwd: path });

var stdout = '';
gitProcess.stdout.on('data', function(data) {
    stdout += data.toString();
});
var stderr = '';
gitProcess.stderr.on('data', function(data) {
    stderr += data.toString();
});

gitProcess.on('close', function() {
    console.log('stdout length', stdout.length);
    console.log('stderr length', stderr.length);
});
```
The expected result is that the `stdout` variable is not empty. But with the first `commands` it is...

**Comment by campersau** [comment]
Actually the bug is because of the [double `^` carrots](https://github.com/FredrikNoren/ungit/blob/master/source/git.js#L219) which are not needed if you use `child_process.spawn` on windows.

If you try this script on windows it works correctly:
```js
var child_process = require('child_process');
var path = process.cwd(); // set this to the ungit repository path if the cwd is somewhere else

// not working commands
var commands = ['diff', 'e6f115fcdedd97fb68701614bd85b368c1a1f53c^!', '--', 'components/stash/stash.js'];
// working commands
//var commands = ['diff', '34e717f76a195582501e038567b47e083827a07f^!', '--', 'source/git-parser.js'];

var gitProcess = child_process.spawn('git', commands, { cwd: path });

var stdout = '';
gitProcess.stdout.on('data', function(data) {
    stdout += data.toString();
});
var stderr = '';
gitProcess.stderr.on('data', function(data) {
    stderr += data.toString();
});

gitProcess.on('close', function() {
    console.log('stdout length', stdout.length);
    console.log('stderr length', stderr.length);
});
```

So the PR #560 is not needed to fix this bug. New PR coming soon.
