### ISSUE TITLE
Couldn't load ungit. v0.9.2 with node v0.12 

### ISSUE THREAD

**Issue by yanosh-igor** [FredrikNoren/ungit#542]
On v0.8.4 everything works fine with node v0.12.
But with v0.9.2 when I type ungit it opens browser and loading very long and at the end shows "Connection lost Refresh the page to try to reconnect".

Attached console information and screen from browser:
![console2 - ungit 2015-04-21 13 04 27](https://cloud.githubusercontent.com/assets/435827/7249978/0c2a12bc-e827-11e4-8b39-b44d37db669a.png)

![dukejobs _ e_ - google chrome 2015-04-21 13 03 44](https://cloud.githubusercontent.com/assets/435827/7249991/2b2389a0-e827-11e4-8c7e-cea8333ec4c4.png)

Could you please suggest something.
.

**Comment by FredrikNoren** [comment]
Try uninstalling `npm uninstall -g ungit`, restarting your machine and then installing `npm install -g ungit@latest`

**Comment by codingtwinky** [comment]
Also do you see anything interesting on the client side log?

**Comment by FredrikNoren** [comment]
@codingtwinky the last thing in his log is /baserepopath which previously froze the whole process so I suspect that somehow he's still on old code somehow

**Comment by codingtwinky** [comment]
@yanosh-igor is it possible that having two different versions, dev version and global installed npm version, and are you confusing one from another?

**Comment by yanosh-igor** [comment]
Tried reinstall ungit(remove/install).
Run ungit command in console, sometimes its loaded properly and sometimes not.

**Comment by yanosh-igor** [comment]
@codingtwinky no, I have installed ungit only globally.

**Comment by yanosh-igor** [comment]
Have noticed that ungit loads only from subdirectory, not from root directory where my git project initialized.

**Comment by codingtwinky** [comment]
My suspicion is that [this line](https://github.com/FredrikNoren/ungit/blob/master/source/git-api.js#L501) doesn't work for you as your git repo location is at `E:/dukejobs`.

@FredrikNoren what exactly is the purpose of `isRoot` function?  Maybe I'm missing something but function suppose to determine whether a path is NOT root rather then is root.  Also for windows why is it length > 3?

**Comment by brianwalleshauser** [comment]
@yanosh-igor I was having the exact same issue

@codingtwinky this is probably terrible, but I went to that line and changed the 3 to a 1.  Everything seems to be working for now

**Comment by FredrikNoren** [comment]
@brianwalleshauser can you try the latest master? `git clone https://github.com/FredrikNoren/ungit.git && cd ungit && npm install && npm install grunt-cli && ./node_modules/.bin/grunt && npm install -g .` should build and install it
