### ISSUE TITLE
Easy browsing doesn't work on Windows

### ISSUE THREAD

**Issue by tengwar** [FredrikNoren/ungit#543]
Windows uses its weird "\" path separator, not "/". Ungit inserts "/" when pressing the right arrow.

**Comment by campersau** [comment]
This was fixed in #544 (but the commit message of https://github.com/codingtwinky/ungit/commit/74287fcf374496fe99630ebda3eb5dc5fbd6ea5a didn't referenced this issue correctly)

**Comment by FredrikNoren** [comment]
Thanks @campersau, closing this one
