### ISSUE TITLE
 Error: spawn ENOENT

### ISSUE THREAD

**Issue by faouzzz** [FredrikNoren/ungit#546]
Hi,

I can't get ungit work for me in Windows 8.1
Errors :
``error: Error: spawn ENOENT``
    &nbsp;&nbsp;&nbsp;&nbsp;``at errnoException (child_process.js:1011:11) ``
    &nbsp;&nbsp;&nbsp;&nbsp;``at Process.ChildProcess._handle.onexit (child_process.js:802:34) ``
</code>

Browser start with this page:
![image](https://cloud.githubusercontent.com/assets/576894/7335212/c07e26cc-ebb0-11e4-9ea5-b11319cd1def.png)

Nothing a part the path of project folder...

**Comment by codingtwinky** [comment]
Can you share node version you are using?

**Comment by faouzzz** [comment]
I'm using node v0.10.35 with npm 1.4.28

**Comment by faouzzz** [comment]
i tryed with the last version of node, same thing...
![image](https://cloud.githubusercontent.com/assets/576894/7336741/a7d8fbd6-ec0c-11e4-871f-4c33d9a8120f.png)

Tryed with an empty git repo same thing

**Comment by codingtwinky** [comment]
You do have git installed right?  When you go to your cmd and running `git --version` give you a version number right?

**Comment by faouzzz** [comment]
thank you @codingtwinky, git was installed but the path variable pointing only on git.exe and not on the  git-core and unix tools folders. So git woked in command line but not with ungit. After adding all git-core module path and unix tools path to the path variable it working well.

Thank you again.
