### ISSUE TITLE
Ungit 0.9.3

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#570]
I've seen a bunch of Windows fixes trickling in (thanks @campersau for contributing a bunch of those!) so I figure it's probably time to do another service release, 0.9.3, to get those fixes out there.

Before I do, I just want to give everyone a chance to get any other last bug fixes in, if there's anything anyone is working on etc. It will probably be at least a week but probably 2-3 before I can release so there's time if anyone needs it (and can of course be more if there's a particular bug fix we want to wait for).

cc @codingtwinky @Ajedi32 @ylecuyer

**Comment by FredrikNoren** [comment]
@codingtwinky hm is #514 expected to fix some of the issues people are seeing or have all of those been addressed in other patches? I.e. should we include it in the service release? I would prefer not to as it's a pretty big change and I don't want to release something with high breakage risk, but if it's fixing a lot of problems it may be worth the risk.

**Comment by campersau** [comment]
It would be nice if the fix in https://github.com/FredrikNoren/ungit/pull/558 can also be included in the new version. This would help a lot debugging issues with git commands. (I just amned and pushed again so travis is green now)

---

I just found another issue https://github.com/FredrikNoren/ungit/issues/571 which would also be nice to be fixed in 0.9.3. Investigating...

**Comment by ylecuyer** [comment]
Will #554 be part of the service release ?

**Comment by codingtwinky** [comment]
#514, #530, #547, #550 should be all ready.

Tests failures seems to be unrelated to changes and will trigger later.

**Comment by FredrikNoren** [comment]
@codingtwinky I want this to be purely a service release (i.e. no new features, just bugfixes) so let's wait with the PRs with new features. I merged #514 as it seems to fix a lot of issues though.

@ylecuyer Yeah I merged it, seems like a bug fix to me.

I'll leave the window to get things fixed in this patch open a little longer as I just merged a bunch of stuff and it would be nice to know all of that works.

**Comment by ylecuyer** [comment]
When is the release planed ?

**Comment by FredrikNoren** [comment]
@ylecuyer now!

I just released 0.9.3, here are all the commits that went into the release: https://github.com/FredrikNoren/ungit/compare/v0.9.2...v0.9.3

Awesome job everyone, hope this release will increase the quality even further of ungit.
