### ISSUE TITLE
Broken rendering on Fedora 22

### ISSUE THREAD

**Issue by rlat** [FredrikNoren/ungit#582]
After update from Fedora 21 to Fedora 22 the ungit UI got completely broken. See the attached screenshots from Fedora 22 and from Debian. In Fedora 22, for all repos there is just one column of dots. 

Debian (working):
![ok](https://cloud.githubusercontent.com/assets/7273178/8204218/4ded0366-14e7-11e5-958a-4fe79a29f675.png)

Fedora 22 (broken):
![broken](https://cloud.githubusercontent.com/assets/7273178/8204217/4debac8c-14e7-11e5-8447-d54fdb7fadb1.png)

I tried downgrading system packages of npm and node.js, using latest node.js built from source, uninstalling and installing ungit again, using different browsers (Firefox 38, Chrome 43, midori 0.5.10), using three different machines with Fedora 22, using older version of ungit... nothing helped.

When I run ungit, there are no errors, only info messages.

Any idea how to fix this? If I can provide more information to debug this issue, please let me know. Currently, ungit is unusable in this state.

**Comment by campersau** [comment]
@rlat what version of git are you using? 
```
$ git --version
```

Maybe this is related to #580

**Comment by rlat** [comment]
Indeed, it seems to be caused by git. I had version 2.4.3. I tried to downgrade it to 2.4.0 and the UI works again.

**Comment by FredrikNoren** [comment]
Closing this one as it should be fixed by #581
