### ISSUE TITLE
dev: how to pass ajax result to UI components?

### ISSUE THREAD

**Issue by linquize** [FredrikNoren/ungit#583]
For example, I want to get `/api/userconfig` through ajax.
Then pass a particular config value to UI components.
However, knockout's data binding makes it complex and difficult to deal with ajax result.
I need to load a value from ajax in the UI that apply data-binding.
I do not want to call the same ajax multiple times for multiple commit nodes (component).
I want to reuse the fetched value in all nodes.

**Comment by FredrikNoren** [comment]
@linquize For config, there's a global `ungit.config`, you should be able to use that from all components. It's also synchronously loaded so will be available instantaneously.

Hope that answers the question
