### ISSUE TITLE
Package Ungit as an Electron App

### ISSUE THREAD

**Issue by Ajedi32** [FredrikNoren/ungit#593]
Seems to me it's about time we simplify the installation process for ungit. [Electron](http://electron.atom.io/) has been out for a while now and seems to be pretty mature at this point ([even Microsoft is using it](http://arstechnica.com/information-technology/2015/04/microsofts-new-code-editor-is-built-on-googles-chromium/) now). 

This would make ungit much more user friendly. No need to download NPM or Node separately, and no need to run ungit in a separate console window; just launch it like a regular desktop application. And as an extra benefit, you get stuff like automatic updates and access to native OS features for free. Seems like a no-brainer to me.

**Comment by PhnxRbrn** [comment]
I second this!

**Comment by FredrikNoren** [comment]
:+1: definitely something I'm interested in, would be awesome to get rid of the awkward npm and node setup we have now

**Comment by kwonoj** [comment]
I'm quite interested about this topic also and gave a quick try, was able to bring ungit as standalone (not packaged yet, dev build only). But it has one hack while bootstrapping application instance. While current ungit initialization rely on console output from forever instance ('## ungit started ##'), this mechanism does not works on electron since all of console output is redirected into chrome logging and does not goes to stdout so forever-monitor does not able to raise event for stdout properly. 

Still looking into way to utilize current codebase without heavily modifying it but also able to hook it inside of electron app bootstrapping. Meanwhile, if there's any suggestion I'd gladly give it a try by myself.

**Comment by Ajedi32** [comment]
I'm certainly no expert here, but would the functionality of `forever-monitor` even be necessary with Electron? It seems Electron has its own architecture for managing the "server" process. (I can definitely understand trying to keep as much of the current architecture as possible with the initial "just get it working" bit though.)

**Comment by kwonoj** [comment]
I'm also exploring of possibilities to reach stage of make it work, not concluded exact way to approach to either to use current bootstrapping using forever-monitor or other way. While initial exploring I don't recall specific mechanism provided by electron, may need read docs once again.

**Comment by Ajedi32** [comment]
I didn't read a whole lot, but my impression was that the server in ungit would correspond to the "main process" in Electron. (<http://electron.atom.io/docs/v0.29.0/tutorial/quick-start/>) Maybe not though?

**Comment by kwonoj** [comment]
Since main process is default node process for electron, my original thought was it's still required to spawn server instance as same as current ungit does. Maybe you're correct and worth to give it a try.

**Comment by kwonoj** [comment]
Yes, it seems additional spawning is not necessarily required.

**Comment by paroxp** [comment]
:+1:

**Comment by FredrikNoren** [comment]
It might be good to know that the UI is somewhat built for this as well. I wanted to package it as a node-webkit app a while back, so fixed the UI for that but never had time to actually finish the packaging.

**Comment by kwonoj** [comment]
@FredrikNoren, what do you think about PR suggested? basically this PR is intended to have very thin bootstarpper for electron, does not make any changes to current codebases (yet) to avoid possible regressions into production releases. I feel there'll be refactorings required in further.

**Comment by FredrikNoren** [comment]
Very cool! Commented in the PR

**Comment by argv-minus-one** [comment]
This would be good for security. Listening on a (non-Unix) socket allows any process on the same machine to potentially attack ungit (especially if authentication isn't configured, which by default it isn't). That's bad; different processes have different privileges for a reason. But if ungit runs in Electron, there's no socket, so there's no problem.

**Comment by jung-kim** [comment]
So once you clone ungit repo, you could do `npm i && npm install -g grunt-cli` and then run `grunt package` to package electron app.  

But it has been awhile since we've implemented it and it may not work... :P 

Is there something like npm registry for the electron apps?

**Comment by HarvsG** [comment]
@jung-kim 
Yes it is at https://electronjs.org/apps

**Comment by jeff-hykin** [comment]
So it looks like the electron app is built, but I don't see anything about it in the readme. Where can I find the app/build?

**Comment by campersau** [comment]
@jeff-hykin I have added a little text to the readme in the installing section https://github.com/FredrikNoren/ungit#installing . You can download the electron apps from here https://github.com/FredrikNoren/ungit/releases . Just choose the zip file which fits your environment.

**Comment by jeff-hykin** [comment]
Thanks!
