### ISSUE TITLE
Strict umask causes bad installation

### ISSUE THREAD

**Issue by zkxs** [FredrikNoren/ungit#596]
To reproduce the problem:

    umask 077
    sudo -H npm install -g ungit

The resulting installation will only be usable by root.  I had to use a less strict umask prior to installing with npm to avoid this.

**Comment by codingtwinky** [comment]
don't you think this is a npm problem?

**Comment by Ajedi32** [comment]
Is this really a problem at all? Seems to me that that's exactly what umask is supposed to do.

**Comment by zkxs** [comment]
I agree with @codingtwinky that this is an npm issue.  I feel like if the user runs `npm install -g ungit`, it is expected that the package should be globally accessible, regardless of what umask was set (possibly in .bashrc, where I forgot about it).  I suppose I'll go see if the npm devs think `npm install -g` should override umask settings.
