### ISSUE TITLE
Add syncing a fork functionality for github

### ISSUE THREAD

**Issue by PhnxRbrn** [FredrikNoren/ungit#600]
When you are fork of the upstream, you have to run the following to update the fork with the upstream changes:

First you have to have the upstream remote added:
git remote add upstream HTTPS://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git

Then do the following to sync:

git fetch upstream
git checkout master
git merge upstream/master

And then push the changes to the fork's master.

Can we have this functionality added in ungit?

**Comment by Ajedi32** [comment]
Pretty sure Ungit can already do that. Multiple remotes are supported, and it's definitely possible to merge a branch. Those are very simple git operations; pretty basic functionality.

Also, the exact process you listed above is a bit more complicated than it needs to be. After setting up the remote you could just checkout master then run `git pull upstream`; that'll do approximately the same thing.

**Comment by PhnxRbrn** [comment]
OK I see now how that is done... Sorry new to the process of pulling updates from the upstream... But could there be a feature added when cloning the repo to specify it is a fork and pass the upstream url?
