### ISSUE TITLE
Using promise framework

### ISSUE THREAD

**Issue by jung-kim** [FredrikNoren/ungit#603]
So this is something that is purely for devs but I think it is about time to do this.

Right now, most async usecases in ungit isn't difficult enough for calling a need for this but I think we need to start slowly phase in bluebird.

i.e. [git-task](https://github.com/FredrikNoren/ungit/blob/master/source/git-task.js) is a great candidate to take full advantage of promises and it would have made implementation of #602 much easier.  (#602 uses wrapped promises around git-task)

**Comment by Ajedi32** [comment]
If #593 is implemented, you could potentially just use the [built-in JS promise implementation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), since you wouldn't necessarily have to worry about browser support anymore.

**Comment by codingtwinky** [comment]
Why would usage of built it promises be depend on #593?  Isn't that just matter of updating node with compatible v8 engine isn't it?  

anyhow, I'm not sure how I feel about this.  it has surprisingly [good coverage](http://caniuse.com/#search=promise) but once it come to the choice between stand alone project vs native javascript implementation I'm bias towards stand alone project and I can list out my reasons.  

Is there a compelling reason to use native js implementation other then one less dependency?

**Comment by Ajedi32** [comment]
Ah, if you're only using it on the server then, yes updating node would work. I was referring more to usage on the front end. No particular reason to prefer the native implementation other than availability and performance; it's just another option really.

**Comment by codingtwinky** [comment]
There are definitely places where I would love to use promises at front end as well.  However I'm not sure if I'm convinced that [native is faster then bluebird](http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird), although it's self proclaimed number...

**Comment by capaj** [comment]
:+1: that git task could be a lot simpler if it were using promises

**Comment by campersau** [comment]
We now use promises in several places https://github.com/FredrikNoren/ungit/pull/666.
