### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by codingtwinky** [FredrikNoren/ungit#608]
Bootstrap 4?  

bootstrap 4 use of sass rather then less will be a tricky one for us.  Also, bootstrap upgrade was one of my failed experiment, I remember having some js runtime issues when I pulled from npm...  :sob: 

http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by FredrikNoren** [comment]
I think it would be awesome but a lot of work with little reward and a lot of risk of breaking stuff :/
