### ISSUE TITLE
version issues

### ISSUE THREAD

**Issue by Xbot3maSter** [FredrikNoren/ungit#614]
HI i got this error warns while install it....
i was ruinng it on kali sana  os latest linux-x64.
this is my version node  installed and npm ;
node -v v0.12.7
npm -v 2.11.3 

here the output;

npm install -g ungit
npm WARN engine forever-monitor@1.1.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> typechecker@2.0.8 preinstall /usr/local/lib/node_modules/ungit/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> ws@0.4.32 install /usr/local/lib/node_modules/ungit/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/ungit/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/ungit/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
/usr/local/bin/ungit -> /usr/local/lib/node_modules/ungit/bin/ungit
/usr/local/bin/0ungit-credentials-helper -> /usr/local/lib/node_modules/ungit/bin/credentials-helper
npm WARN unmet dependency /usr/local/lib/node_modules/codebox/node_modules/hr.js/node_modules/express requires commander@'0.6.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/codebox/node_modules/commander,
npm WARN unmet dependency which is version 1.1.1
npm WARN unmet dependency /usr/local/lib/node_modules/codebox/node_modules/hr.js/node_modules/express requires crc@'0.2.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/codebox/node_modules/crc,
npm WARN unmet dependency which is version 0.2.1
ungit@0.9.3 /usr/local/lib/node_modules/ungit
├── os-homedir@1.0.1
├── open@0.0.5
├── blueimp-md5@1.1.1
├── crossroads@0.12.2
├── uuid@2.0.1
├── async@1.3.0
├── semver@5.0.1
├── cookie-parser@1.3.5 (cookie@0.1.3, cookie-signature@1.0.6)
├── passport-local@1.0.0 (passport-strategy@1.0.0)
├── passport@0.2.2 (pause@0.0.1, passport-strategy@1.0.0)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── signals@1.0.0
├── rc@1.0.3 (ini@1.3.4, strip-json-comments@0.1.3, deep-extend@0.2.11, minimist@0.0.10)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── diff2html@0.2.6 (diff@1.4.0)
├── express-session@1.11.3 (cookie@0.1.3, cookie-signature@1.0.6, utils-merge@1.0.0, on-headers@1.0.0, parseurl@1.3.0, depd@1.0.1, crc@3.3.0, uid-safe@2.0.0, debug@2.2.0)
├── knockout@3.3.0
├── getmac@1.0.7 (extract-opts@2.2.0)
├── keen.io@0.1.3 (underscore@1.5.2)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── raven@0.8.1 (lsmod@0.0.3, stack-trace@0.0.7, cookie@0.1.0, node-uuid@1.4.3)
├── color@0.10.1 (color-convert@0.5.3, color-string@0.3.0)
├── npmconf@2.1.2 (uid-number@0.0.5, ini@1.3.4, inherits@2.0.1, osenv@0.1.3, once@1.3.2, nopt@3.0.3, config-chain@1.1.9, semver@4.3.6)
├── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.2.0, readable-stream@1.0.27-1, formidable@1.0.14, form-data@0.1.3)
├── body-parser@1.13.3 (bytes@2.1.0, content-type@1.0.1, depd@1.0.1, http-errors@1.3.1, on-finished@2.3.0, qs@4.0.0, raw-body@2.1.2, debug@2.2.0, type-is@1.6.8, iconv-lite@0.4.11)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, path-to-regexp@0.1.7, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, depd@1.0.1, finalhandler@0.4.0, on-finished@2.3.0, qs@4.0.0, debug@2.2.0, send@0.13.0, proxy-addr@1.0.8, type-is@1.6.8, accepts@1.2.13)
├── rimraf@2.4.3 (glob@5.0.14)
├── winston@1.0.1 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, pkginfo@0.3.0, async@0.9.2, colors@1.0.3)
├── yargs@3.15.0 (decamelize@1.0.0, camelcase@1.2.1, window-size@0.1.2, cliui@2.1.0)
├── lodash@3.10.1
├── hasher@1.2.0
├── moment@2.10.6
├── forever-monitor@1.1.0 (watch@0.5.1, pkginfo@0.3.0, minimatch@0.0.5, utile@0.1.7, ps-tree@0.0.3, broadway@0.2.10)
├── npm-registry-client@6.5.1 (chownr@0.0.2, slide@1.1.6, graceful-fs@3.0.8, retry@0.6.1, once@1.3.2, npm-package-arg@4.0.2, concat-stream@1.5.0, normalize-package-data@2.3.2, npmlog@1.2.1, request@2.61.0)
└── socket.io@0.9.17 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)

**Comment by FredrikNoren** [comment]
I only see warnings? Did it not run once it was installed?

**Comment by campersau** [comment]
Closing as this issue is quite old.
Please open a new issue if there is an error with installing the current version.
