### ISSUE TITLE
npm installation

### ISSUE THREAD

**Issue by Xbot3maSter** [FredrikNoren/ungit#615]
i trying setting up a project  it required   npm install -g ungit  and it  running rethinkdb database..
during my installation everything is good except this ungit  occurs few error code line on my  terminal screen ;

npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

  i just ignored it until i knowning  because of this problem during install dependencies WARN issue 
 and it caused  my project  doesnt working at all  how can i fix them?..
  can you help me out i ll be gratefully.

here more detail  the building  project dependencies npm install output;

npm install

> ws@0.6.5 install /root/Downloads/Code/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Downloads/Code/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/root/Downloads/Code/node_modules/ws/build'
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> hiredis@0.2.0 install /root/Downloads/Code/node_modules/livedb/node_modules/hiredis
> node-gyp rebuild

make: Entering directory '/root/Downloads/Code/node_modules/livedb/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis.a
  COPY Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory '/root/Downloads/Code/node_modules/livedb/node_modules/hiredis/build'
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> kerberos@0.0.11 install /root/Downloads/Code/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Downloads/Code/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
kerberos.target.mk:91: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: Leaving directory '/root/Downloads/Code/node_modules/mongodb/node_modules/kerberos/build'
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> bson@0.2.22 install /root/Downloads/Code/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Downloads/Code/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory '/root/Downloads/Code/node_modules/mongodb/node_modules/bson/build'
npm WARN prefer global nodemon@1.4.1 should be installed with -g

> ws@0.4.32 install /root/Downloads/Code/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Downloads/Code/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/root/Downloads/Code/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
\

> node-sass@2.1.1 install /root/Downloads/Code/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js
## 

> node-sass@2.1.1 postinstall /root/Downloads/Code/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64-node-0.12` exists; testing
Binary is fine; exiting

> nodegit@0.4.1 install /root/Downloads/Code/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.
karma-firefox-launcher@0.1.6 node_modules/karma-firefox-launcher

is-git-url@0.1.0 node_modules/is-git-url

karma-jasmine@0.3.6 node_modules/karma-jasmine

share-codemirror@0.1.0 node_modules/share-codemirror

bcrypt-nodejs@0.0.3 node_modules/bcrypt-nodejs

underscore.string@2.4.0 node_modules/underscore.string

config@1.16.0 node_modules/config

wrench@1.5.8 node_modules/wrench

cookie-parser@1.3.5 node_modules/cookie-parser
├── cookie@0.1.3
└── cookie-signature@1.0.6

q@1.4.1 node_modules/q

passport-local@1.0.0 node_modules/passport-local
└── passport-strategy@1.0.0

passport@0.2.2 node_modules/passport
├── pause@0.0.1
└── passport-strategy@1.0.0

rethinkdb@2.1.1 node_modules/rethinkdb

mkdirp@0.5.1 node_modules/mkdirp
└── minimist@0.0.8

jshashes@1.0.5 node_modules/jshashes

multiparty@4.1.2 node_modules/multiparty
└── fd-slicer@1.0.1 (pend@1.2.0)

livedb-mongo@0.4.1 node_modules/livedb-mongo
├── async@0.9.2
└── mongoskin@1.4.13

morgan@1.6.1 node_modules/morgan
├── basic-auth@1.0.3
├── on-headers@1.0.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
└── debug@2.2.0 (ms@0.7.1)

express-session@1.11.3 node_modules/express-session
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── on-headers@1.0.0
├── parseurl@1.3.0
├── depd@1.0.1
├── crc@3.3.0
├── uid-safe@2.0.0 (base64-url@1.2.1)
└── debug@2.2.0 (ms@0.7.1)

optimist@0.6.1 node_modules/optimist
├── wordwrap@0.0.3
└── minimist@0.0.10

jasmine-core@2.3.4 node_modules/jasmine-core

karma-chrome-launcher@0.1.12 node_modules/karma-chrome-launcher
└── which@1.1.1 (is-absolute@0.1.7)

connect@3.4.0 node_modules/connect
├── utils-merge@1.0.0
├── parseurl@1.3.0
├── debug@2.2.0 (ms@0.7.1)
└── finalhandler@0.4.0 (escape-html@1.0.2, unpipe@1.0.0, on-finished@2.3.0)

passport-github@0.1.5 node_modules/passport-github
├── pkginfo@0.2.3
└── passport-oauth@0.1.15 (oauth@0.9.13, passport@0.1.18)

body-parser@1.13.3 node_modules/body-parser
├── bytes@2.1.0
├── content-type@1.0.1
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.1, statuses@1.2.1)
├── raw-body@2.1.2 (unpipe@1.0.0)
├── qs@4.0.0
├── debug@2.2.0 (ms@0.7.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── iconv-lite@0.4.11

rimraf@2.4.3 node_modules/rimraf
└── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.10)

bluebird@2.9.34 node_modules/bluebird

ws@0.6.5 node_modules/ws
├── options@0.0.6
├── ultron@1.0.2
└── nan@1.4.3

chai@1.10.0 node_modules/chai
├── assertion-error@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── content-type@1.0.1
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── qs@4.0.0
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.6)
└── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)

should@4.6.5 node_modules/should
├── should-type@0.0.4
├── should-equal@0.3.1
└── should-format@0.0.7

supertest@0.15.0 node_modules/supertest
├── methods@1.1.1
└── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.2.0, readable-stream@1.0.27-1, form-data@0.1.3, formidable@1.0.14)

gulp-concat@2.6.0 node_modules/gulp-concat
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── concat-with-sourcemaps@1.0.2 (source-map@0.4.4)
└── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)

supertest-as-promised@1.0.0 node_modules/supertest-as-promised
├── methods@1.1.1
└── bluebird@1.2.4

mysql@2.9.0 node_modules/mysql
├── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── bignumber.js@2.0.7

gulp-watch@3.0.0 node_modules/gulp-watch
├── glob2base@0.0.12 (find-index@0.1.1)
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── vinyl-file@1.1.1 (graceful-fs@3.0.8, strip-bom@1.0.0)
├── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
├── path2glob@0.0.2 (glob@4.5.3)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, multipipe@0.1.2, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, dateformat@1.0.11)
└── gaze@0.5.1 (globule@0.1.0)

lodash@2.4.2 node_modules/lodash

request@2.61.0 node_modules/request
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── caseless@0.11.0
├── stringstream@0.0.4
├── oauth-sign@0.8.0
├── tunnel-agent@0.4.1
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── node-uuid@1.4.3
├── qs@4.0.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── form-data@1.0.0-rc3 (async@1.4.2)
├── mime-types@2.1.6 (mime-db@1.18.0)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@1.0.0 (readable-stream@2.0.2)
├── har-validator@1.8.0 (commander@2.8.1, chalk@1.1.1, is-my-json-valid@2.12.2)
├── tough-cookie@2.0.0
└── hawk@3.1.0 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)

gulp@3.9.0 node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── minimist@1.2.0
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-uglify@1.4.0 node_modules/gulp-uglify
├── uglify-save-license@0.4.1
├── deap@1.0.0
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.11)
└── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)

jszip@2.5.0 node_modules/jszip
└── pako@0.2.7

livedb@0.5.13 node_modules/livedb
├── arraydiff@0.1.1
├── deep-is@0.1.3
├── ot-text-tp2@1.0.0
├── ot-text@1.0.1
├── statsd-client@0.2.0
├── async@0.9.2
├── ot-json0@1.0.1
├── redis@0.12.1
└── hiredis@0.2.0 (bindings@1.2.1, nan@1.5.3)

archiver@0.13.1 node_modules/archiver
├── buffer-crc32@0.2.5
├── lazystream@0.1.0
├── async@0.9.2
├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
├── tar-stream@1.1.5 (xtend@4.0.0, bl@0.9.4, end-of-stream@1.1.0)
├── glob@4.3.5 (inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.10)
└── zip-stream@0.5.2 (compress-commons@0.2.9, lodash@3.2.0)

forever@0.12.0 node_modules/forever
├── watch@0.8.0
├── colors@0.6.2
├── pkginfo@0.3.0
├── timespan@2.3.0
├── utile@0.2.1 (deep-equal@1.0.1, ncp@0.4.2, async@0.2.10, i@0.3.3)
├── nssocket@0.5.3 (eventemitter2@0.4.14, lazy@1.0.11)
├── nconf@0.6.9 (ini@1.3.4, async@0.2.9, optimist@0.6.0)
├── cliff@0.1.8 (eyes@0.1.8, winston@0.6.2)
├── winston@0.7.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, async@0.2.10, request@2.16.6)
├── forever-monitor@1.4.0 (watch@0.5.1, minimatch@0.2.14, utile@0.1.7, ps-tree@0.0.3, broadway@0.2.10)
└── flatiron@0.3.11 (optimist@0.6.0, director@1.1.10, prompt@0.2.11, broadway@0.2.9)

rethinkdb-init@0.0.4 node_modules/rethinkdb-init
└── lodash@3.10.1

share@0.7.27 node_modules/share
├── hat@0.0.3
├── async@0.2.10
├── ottypes@1.0.3
└── express@3.21.2 (merge-descriptors@1.0.0, escape-html@1.0.2, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, basic-auth@1.0.3, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, connect@2.30.2)

lodash-contrib@241.4.14 node_modules/lodash-contrib
└── lodash@2.4.1

livedb-rethinkdb@0.0.5 node_modules/livedb-rethinkdb
├── async@0.9.2
├── rethinkdbdash@1.16.13
└── lodash@3.10.1

mocha@2.3.1 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── lodash.create@3.1.1 (lodash._basecreate@3.0.3, lodash._isiterateecall@3.0.9, lodash._baseassign@3.2.0)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@1.11.0 (character-parser@1.2.1, void-elements@2.0.1, commander@2.6.0, jstransformer@0.0.2, constantinople@3.0.2, with@4.0.3, clean-css@3.4.1, transformers@2.1.0, uglify-js@2.4.24)

bookshelf@0.7.9 node_modules/bookshelf
├── inherits@2.0.1
├── trigger-then@0.3.0
├── simple-extend@0.1.0
├── create-error@0.3.1
├── inflection@1.7.1
├── semver@4.3.6
└── backbone@1.1.0 (underscore@1.8.3)

nodemon@1.4.1 node_modules/nodemon
├── minimatch@0.3.0 (sigmund@1.0.1, lru-cache@2.6.5)
├── touch@1.0.0 (nopt@1.0.10)
├── ps-tree@0.0.3 (event-stream@0.5.3)
└── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.1, chalk@1.1.1, semver-diff@2.0.0, latest-version@1.0.1, configstore@0.3.2)

moment@2.10.6 node_modules/moment

codemirror@4.13.0 node_modules/codemirror

knex@0.7.6 node_modules/knex
├── interpret@0.3.10
├── inherits@2.0.1
├── generic-pool-redux@0.1.0
├── minimist@1.1.3
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── tildify@1.0.0 (user-home@1.1.1)
├── readable-stream@1.1.13 (isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── liftoff@0.13.6 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-sync@0.1.3)

mongodb@1.4.39 node_modules/mongodb
├── readable-stream@2.0.2 (process-nextick-args@1.0.2, isarray@0.0.1, inherits@2.0.1, util-deprecate@1.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
├── kerberos@0.0.11 (nan@1.8.4)
└── bson@0.2.22 (nan@1.8.4)

karma@0.12.37 node_modules/karma
├── di@0.0.1
├── graceful-fs@3.0.8
├── mime@1.3.4
├── colors@1.1.2
├── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── source-map@0.4.4 (amdefine@1.0.0)
├── minimatch@2.0.10 (brace-expansion@1.1.0)
├── useragent@2.1.7 (lru-cache@2.2.4)
├── chokidar@1.0.5 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.4.0, anymatch@1.3.0)
├── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, utile@0.2.1)
├── connect@2.30.2 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, cookie-signature@1.0.6, pause@0.1.0, fresh@0.3.0, response-time@2.3.1, vhost@3.0.1, content-type@1.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, parseurl@1.3.0, depd@1.0.1, qs@4.0.0, http-errors@1.3.1, connect-timeout@1.6.2, serve-favicon@2.3.0, debug@2.2.0, method-override@2.3.5, finalhandler@0.4.0, csurf@1.8.3, serve-static@1.10.0, type-is@1.6.8, multiparty@3.3.2, errorhandler@1.4.2, compression@1.5.2, serve-index@1.7.2)
├── lodash@3.10.1
├── log4js@0.6.26 (async@0.2.10, underscore@1.8.2, semver@4.3.6, readable-stream@1.0.33)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)

gulp-sass@1.3.3 node_modules/gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── node-sass@2.1.1 (get-stdin@4.0.1, object-assign@2.1.1, replace-ext@0.0.1, semver@4.3.6, shelljs@0.3.0, cross-spawn@0.2.9, chalk@0.5.1, nan@1.9.0, gaze@0.5.1, npmconf@2.1.2, meow@3.3.0, sass-graph@1.3.0, pangyp@2.3.1)

nodegit@0.4.1 node_modules/nodegit
├── fs-extra@0.18.4 (graceful-fs@3.0.8, jsonfile@2.2.1)
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── which-native-nodish@1.1.3 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
└── npm@2.14.2

**Comment by FredrikNoren** [comment]
I'm not sure what the question is? Is the install failing for you? Or are you worried that the about WARNs?

**Comment by asafm** [comment]
Same for me. WARN, but installation is successfull

**Comment by sanstream** [comment]
These WARN's are just telling you that you're version of node is older that wanted by those libraries.

`npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})`

Updating nodejs would 'fix' that.
