### ISSUE TITLE
Can I see git revision graph on ungit?

### ISSUE THREAD

**Issue by shuogawa** [FredrikNoren/ungit#620]
I wanna see git revision graph like https://tortoisegit.org/docs/tortoisegit/tgit-dug-revgraph.html.
Does ungit have this feture?

**Comment by Ajedi32** [comment]
Yeah, that's kinda the default view. Didn't you see the screenshot in the README?

![](https://raw.githubusercontent.com/FredrikNoren/ungit/master/screenshot.png)

**Comment by FredrikNoren** [comment]
I call this resolved
