### ISSUE TITLE
1.0.0!

### ISSUE THREAD

**Issue by dbkaplun** [FredrikNoren/ungit#621]

**Comment by FredrikNoren** [comment]
Yes! I want that to be #593 though, that @kwonoj is working on. Basically packaging ungit as an electron app.

**Comment by codingtwinky** [comment]
I think this would be very nice.  One quick thought though, can we do one or couple more releases prior so we can have more battle test #593 and #602?

These are couple of big features that may need more burn time in the user's hands.

**Comment by FredrikNoren** [comment]
@codingtwinky Yup I think that makes sense, we should probably feature freeze once that is out and focus only on the electron release and have that really polished.

**Comment by linquize** [comment]
1.0 means plugin API stable?

**Comment by Ajedi32** [comment]
@linquize Good point. If we're following SemVer, that would be what a 1.0 release would mean. I think most people here though seem to be thinking of the version number from a much more squishy "user's perspective", rather than from the perspective of the Ungit plugin API.

**Comment by FredrikNoren** [comment]
Yeah I feel like the plugin system never really caught on so almost
thinking we should remove it for 1.0. Complicated to support properly and
adds unknowns with electron. Can keep the code but no "official" support
(remove from docs etc.). (Unless it turns out people are using it, but
haven't seen any evidence of that so far)

**Comment by Ajedi32** [comment]
Aren't some of the components in the ungit core implemented as plugins though?

**Comment by FredrikNoren** [comment]
Yeah, I think the code should remain, just changing the documentation to not "encourage" plugins
