### ISSUE TITLE
commit & push button next to commit button

### ISSUE THREAD

**Issue by capaj** [FredrikNoren/ungit#633]
Most git UIs offer to commit & push on one click. Looking at the commit bubble, there is plenty of space there to put another button. Or just make it a button with the little down-chevron on the right where we could pick an option to push as well. What do you think-if I opened a PR for that, would you @codingtwinky or @FredrikNoren happily accept it?

**Comment by Ajedi32** [comment]
What might be interesting would be to implment some version of the "always online experience" mentioned in http://tonsky.me/blog/reinventing-git-interface/

Obviously there are some circumstances where you don't necessarily want to push every change, but maybe like a "automatically sync changes on this branch" option would be interesting. We could integrate it with git's built-in system for tracking branches, maybe call it "live branches" or something in the UI.

**Comment by codingtwinky** [comment]
Every time when something can be done easy it also means mistakes can be made easy as well and I don't think benefit is worth possible complications from mistakes.

I thoroughly believe best Git practice is commit often and push only when certain level of quality can be promised.  There are reasons why commit and push is a separate operation and it should be remain that way.

Now if you want to do some dedicated special branch ops like @Ajedi32 is recommending, that would be something interesting but I'd imagine it would require much more thought process.

**Comment by FredrikNoren** [comment]
I agree with @codingtwinky. Closing this one as there's no further action for now.

@Ajedi32 hm that's an interesting idea. Would be a little hesitant to add the UI complexity though (my hunch is that the gain is too small to warrant it).

**Comment by Ajedi32** [comment]
Yeah, it'd be a very minor workflow optimization. There are certainly other changes yet to be made that would make a much bigger difference IMO.
