### ISSUE TITLE
too much screen space lost because of commit message inputs

### ISSUE THREAD

**Issue by capaj** [FredrikNoren/ungit#643]
I quite like ungit's UI, but there are several weak points. One of them being staging component.
I useally work on one commit few hours and all that time, 1/3 of my screen has to be filled with en empty space like here:
![screenshot from 2015-11-11 18-54-03](https://cloud.githubusercontent.com/assets/1305378/11099990/6b86c262-88a6-11e5-9c98-a063627759ad.png)

If I could propose an improvement, I think commit message should open in a popup or a modal. So we would only have a commit button in the staging area. That button could easily be in the corner overlaying the staging window content-that way the content could take up the whole screen.

What do you think, should I try making a PR?

**Comment by codingtwinky** [comment]
I did have a version with a toggle button that hide/show commit message column somewhere when I was in merge hell...  But yes I think that would be great if you can send a PR for that.
