### ISSUE TITLE
git clone in ungit

### ISSUE THREAD

**Issue by stefanks** [FredrikNoren/ungit#645]
It would be useful if pasting a link such as https://github.com/FredrikNoren/ungit.git would run the git clone command. A dialog with a folder chooser could let you pick which directory to clone to.

**Comment by codingtwinky** [comment]
So Ungit already has such feature.

if you navigate to a none existing location, ungit will prompt a page where you can create an empty folder with given path.  And once it is created or you have navigated to an empty folder, ungit will give you an interface for you to clone a repo based on url. 

Please let me know if this addresses your problem.
