### ISSUE TITLE
Shouldn't use github logo for checkout

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#651]
It's cute but ungit hasn't got anything to with Github so I feel like we should stay away from using their logo in the tool.

![screen shot 2015-11-24 at 9 56 15 pm](https://cloud.githubusercontent.com/assets/1288009/11387196/3bf87d4c-92f6-11e5-81ed-32b3a4cdc14b.png)

**Comment by linquize** [comment]
Use arrow to replace that?

**Comment by campersau** [comment]
Strange. This is how the checkout icon looks in my environment:

![image](https://cloud.githubusercontent.com/assets/4009570/11399200/020728c8-9386-11e5-80d2-d009047fb56d.png)

**Comment by linquize** [comment]
@campersau  Nice image

**Comment by codingtwinky** [comment]
so #640 should have given you the icons @campersau posted.  Is this a matter of pulling or is this a legitimate issue?

**Comment by linquize** [comment]
Use octicons but exclude octocat?

**Comment by FredrikNoren** [comment]
@codingtwinky ah seems like it was a bad on my end, looks good now! Thanks!
