### ISSUE TITLE
Stable build on Windows

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#663]
Currently incredibly unstable on windows, let's use this as a tracking issue to improve things.

**Comment by GammaNu** [comment]
1.1.29 still very instable on windows (at least with uBlock on)

**Comment by codingtwinky** [comment]
Ad blocker is a known issue and I'm sure you know this but you can find more about it in [readme](https://github.com/FredrikNoren/ungit#known-issues).  

For windows, please file individual tickets for each issues and will try to take a look at it.  But considering I don't have windows machine, it can be difficult.  I would welcome your PR though, should you want to fix on your own

**Comment by campersau** [comment]
Builds on windows are finally stable https://github.com/FredrikNoren/ungit/pull/1263
