### ISSUE TITLE
Changelog/Release Notes

### ISSUE THREAD

**Issue by daedalus28** [FredrikNoren/ungit#687]
Congrats and excellent work releasing 0.10! I rushed to update as soon as I saw the email.

It would be really nice to have a list of things that have changed each version moving forward - as it is now I am just looking around in the UI for new features and reading all the commit messages since the last version. Any chance we could get a changelog.md or something similar?

**Comment by FredrikNoren** [comment]
Happy to hear :) And yeah agree, a changelog is much needed.

I think what we should do is that we keep a `CHANGELOG.md` file and any PR that introduces new features also needs to add that feature to the changelog. What do you think @codingtwinky ?

**Comment by jamesjnadeau** [comment]
:+1: on the changelog! 

By the way, 
great update and work :clap: , looks fantastic! 
Love this thing! Makes git easier for everyone.

**Comment by codingtwinky** [comment]
Hooray!

I just saw release note are missing [within gihub](https://github.com/blog/1547-release-your-software)/  I thought release notes that was gathered were added in there as well.   or do you guys prefer `CHANGELOG.md`?

**Comment by codingtwinky** [comment]
Or it could be on gh-page or wiki along with #636?  

As a code cruncher I really hate writing human language and it would be nice to have that going...

**Comment by daedalus28** [comment]
`CHANGELOG.md` is probably the most straightforward to manage from the code. If it was in the wiki or gh-pages, wouldn't that mean it would have to be updated independently from the source code? In my experience that usually means it will just never get updated.

**Comment by FredrikNoren** [comment]
Yeah in source code seems like the easiest

**Comment by codingtwinky** [comment]
Do we have any quick sugestions on format of change log?   My very tired brain is imagining something like below.  Just an example...

```
### 0.10.2
feature:
* #.... : removed hover effect #688

bug fix:
* #692: fix duplicate remote tage bug #686 
```

**Comment by Ajedi32** [comment]
@codingtwinky I personally like the format suggested by the [Keep a CHANGELOG](http://keepachangelog.com/) project: https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/master/CHANGELOG.md

**Comment by FredrikNoren** [comment]
@Ajedi32 nice hadn't seen that before. Seems easiest to use that, I'll change the pr

**Comment by FredrikNoren** [comment]
@codingtwinky I like the idea of referencing issues & pr's in the change log too, I'll include that
