### ISSUE TITLE
Expose cherry-pick abort and continue in UI

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#701]
When you rebase or merge the UI shows "abort" and "continue" buttons when there's a conflict, but for cherry-pick this isn't implemented (it get's into a weird state where staging just looks like a bunch of files with changes, but they also have conflicts). Should probably look pretty much like what rebase and merge looks like.

**Comment by codingtwinky** [comment]
`/cherrypic` operation does fail properly with `merg-failed` git error.  However, problem is that cherry pick conflict doesn't get persisted.

for example, when merge conflict happens.  next `/status` reports `inMerging := true` via checking few git files and front end knows to show "in conflict" view.  However for cherry pick there is no way for us to know if we are "in cherry picking" state, as far as I know.

We can infer that we are in cherry pick failed state when any files in staging is in conflict as I believe that is the only situation where we would have files in conflicts and "inMerging" and "inRebasing" flags are false.

Thought?

**Comment by codingtwinky** [comment]
Ignore what I wrote above, it seems that git is creating ".../.git/CHERRY_PICK_HEAD" file upon cherry pick conflict, similar to merge conflicts.
