### ISSUE TITLE
v0.10.1 readiness

### ISSUE THREAD

**Issue by codingtwinky** [FredrikNoren/ungit#702]
As you may know below is the exact copy of current changelog and list of fixes at the current master branch.  @FredrikNoren after further testing, I think we are ready for next minor release. 

(i.e. I haven't merged #697 yet as I'm not sure if we want to this to be included without further testing.)

---

### Added
- Introduced change log! [#687](https://github.com/FredrikNoren/ungit/issues/687)
- Improved server and client error logging [#695](https://github.com/FredrikNoren/ungit/pull/695)

### Fixed
- Fix crashes due to submodule parsing [#690](https://github.com/FredrikNoren/ungit/issues/690) [#689](https://github.com/FredrikNoren/ungit/issues/689)
- Fix duplicate remote tag issues [#685](https://github.com/FredrikNoren/ungit/issues/685)
- Fix scrolling issue in safari [#686](https://github.com/FredrikNoren/ungit/issues/686)
- Fix git hooks failing on non-ascii files [#676](https://github.com/FredrikNoren/ungit/issues/676)

### Removed
- Reverted on hover button effects [#688](https://github.com/FredrikNoren/ungit/issues/688)

**Comment by FredrikNoren** [comment]
I think we can include #697, seems to work fine here

**Comment by codingtwinky** [comment]
#697 merged

**Comment by FredrikNoren** [comment]
Released!
