### ISSUE TITLE
Ungit as AppImage for Linux 

### ISSUE THREAD

**Issue by kskarthik** [FredrikNoren/ungit#713]
Hello! just came through this cool app :) thanks for helping newcomers to learn git easily. 

Well, I also have a suggestion too ! Please also make it portable using AppImage so that we could carry the app on an usb stick to another linux PC whatever OS it is on & run it without any special permissions & dependencies. 

 AppImage is based on concept of **one app = one file** & also supports __Delta updates__ too. 

Pack the required dependency (nodejs) & ship it as AppImage for Linux. No special skills needed to make an appimage. Plugins can be loaded from ~/.ungit as usual. 

Project website: http://AppImage.org

Github repo: https://github.com/probonopd/appimagekit 

The project's dev @probonopd is happy to help you in this process :)

**Comment by codingtwinky** [comment]
FYI, similar effort for electron is ongoing or near finished at #593.  Considering it supports windows, I would favor that over this if I was given an option to choose one or another. 

But you are welcome to send PRs.

**Comment by kskarthik** [comment]
Well, electron is ideal for webapps. So, I'm closing this issue.

**Comment by doradoro** [comment]
The linux Electron versin ahve no executable files inside and it is not installable so an AppImage should be better...
