### ISSUE TITLE
I have docker stuff for this, does anyone want it?

### ISSUE THREAD

**Issue by ppanyukov** [FredrikNoren/ungit#714]
I wanted to play around with this and build a quick small docker image for this with docker-compose etc.

This might be handy for people who want to use `ungit` but don't want to install various bits and run it as a global thing on their machine.

Also might be handy for devs of this repo :)

The repo for this is https://github.com/ppanyukov/ungit-docker

If there is interest, I can do a PR. Or just grab it and use whatever is the easiest for people.

**Comment by linquize** [comment]
1. Your Dockerfile downloads to released version of ungit
2. The user needs to aware of file owner problem if he uses Docker image to write to the repo. (Docker engine usually runs in root account)
If you use Docker image for read-only repo operations, then it is fine.

**Comment by ppanyukov** [comment]
Released version is the one we need right? To match the "installation instructions" as per the readme. Granted, this makes it lesser suitable for devs perhaps. Can always bake in a "dev" image into the source tree for that though.

Yep, everyone knows about docker and root, I'm not even pretending to solve this here.

**Comment by codingtwinky** [comment]
You are welcome to send PR against a readme to include this.  But please do specify noted concerns and limitations.
