### ISSUE TITLE
The move feature can cause commits to be lost

### ISSUE THREAD

**Issue by sedge** [FredrikNoren/ungit#715]
Moving a branch with new commits in it will lose the reference to those commits:

![ungit](https://cloud.githubusercontent.com/assets/1616860/13639529/2ce11468-e5df-11e5-94c1-4c38200a32d1.gif)

At the very least this action should come with a warning when this is the case.

**Comment by codingtwinky** [comment]
Thing about adding warning is that it will be annoying to others...  will try to think of a way

**Comment by sedge** [comment]
Maybe a "do not show again"?

**Comment by FredrikNoren** [comment]
This should be solved with the #124 feature. I.e. when you do this, it would show a small help text at the top of the screen with "You just moved a commit. Undo?", where you could click Undo to go back in the ref log.

**Comment by sedge** [comment]
@FredrikNoren Does that issue have a PR associated with it that's close to merging? If not, I'd advise you to keep this issue open so that people can see it in a search :+1:
