### ISSUE TITLE
Why !

### ISSUE THREAD

**Issue by jak645** [FredrikNoren/ungit#719]
why the new header and body or not align ^^ grrrrr :P

![whyy](https://cloud.githubusercontent.com/assets/6710664/13879470/fb767628-eced-11e5-96bf-d9a26799611d.png)

**Comment by lfx** [comment]
It's aligned! You have focus in header field this adds glow/selected effect that's it looks _bigger_ and not aligned.

**Comment by jak645** [comment]
Omg ! feel so stupid !
