### ISSUE TITLE
word wrapping on diffs

### ISSUE THREAD

**Issue by kosir** [FredrikNoren/ungit#721]
hi, thanks for this fantastic tool :+1: 

is it possible to implement word wrap on diff like github [https://github.com/blog/1707-soft-wrapping-on-prose-diffs](https://github.com/blog/1707-soft-wrapping-on-prose-diffs)
...because I'm doing lot of mysqldumps and lines are sooo long, I really need this

thanks in advance for any reply

**Comment by codingtwinky** [comment]
This should be a fairly easy fix and will cook one soon.

I'm envisioning adding a toggle button for each text views that are similar to default view vs side by side view buttons.  Please let me know if anybody have any other suggestions.

**Comment by kosir** [comment]
Thank you!  For me soft-wrapping would be all I currently need. Hope to see it soon :)
