### ISSUE TITLE
`git checkout -b` option when creating branches

### ISSUE THREAD

**Issue by chrisuehlinger** [FredrikNoren/ungit#738]
I often find that while using ungit, I go through a "Make a Branch -> Checkout that branch" sort of workflow. In fact, I almost never create a branch unless I'm about to check it out. If there was a way for ungit to auto-checkout new branches, it would make things much easier.

I also recognize that it would be bad to change the default behavior of ungit and confuse current users. Here are a couple ideas I had:

1. Add a [Branch + Checkout] option when creating a Branch/Tag. This would work for me, but might clutter the UI a bit.
2. Add an `"autoCheckout"` flag to the `.ungitrc` spec, just like the current `"autoFetch"` one. This would help me out as well, wouldn't clutter the UI, and could be set to `false` by default so that only power users would need to know about it.

Thanks for the consideration!

**Comment by codingtwinky** [comment]
I think this would be a "good-first-contribution" if anybody want to try it and I be happy to help.  But if not, I will jump on it once I'm done with my work mayhem that is going on right now...
