### ISSUE TITLE
Revert a merge commit

### ISSUE THREAD

**Issue by sedge** [FredrikNoren/ungit#753]
This operation fails because `ungit` doesn't detect that the commit selected is a merge commit, which requires an extra option:
![screen shot 2016-06-01 at 2 15 31 pm](https://cloud.githubusercontent.com/assets/1616860/15720689/6dbd3f46-2803-11e6-8f4d-50b239f842eb.png)

**Comment by sedge** [comment]
🎉

**Comment by codingtwinky** [comment]
Just give a heads up.  Ungit will pick 1st parent blindly on revert merge.
