### ISSUE TITLE
Cherry-Pick conflict continue

### ISSUE THREAD

**Issue by ylecuyer** [FredrikNoren/ungit#758]
If there is a conflict during cherry-pick, the continue command must be fired from the command line as it is not present on the webui

**Comment by codingtwinky** [comment]
In case of cherry-pick conflicts, you will see "conflict" button next to each conflicted filed.  Once a conflict is resolved, you would need to click on "conflict" button to mark it as resolved.  Once all conflicts are resolved, than you will be allowed to click on "commit" button and make progress.

Please re open this ticket and let me know if this is not the case.

* example "conflict" button
<img width="404" alt="screen shot 2016-07-31 at 15 15 33" src="https://cloud.githubusercontent.com/assets/5281068/17279769/15b7c484-5732-11e6-8887-79490b155ca3.png">

* "conflict" button change to "resolve conflict" on mouse hover
<img width="363" alt="screen shot 2016-07-31 at 15 16 21" src="https://cloud.githubusercontent.com/assets/5281068/17279772/1d1d6ef4-5732-11e6-9c81-11d148e57c88.png">

* "commit" button is enabled after all are resolved.
<img width="853" alt="screen shot 2016-07-31 at 15 18 00" src="https://cloud.githubusercontent.com/assets/5281068/17279774/1f72175e-5732-11e6-8da3-7a285d994ae5.png">
