### ISSUE TITLE
Minimatch warning on install

### ISSUE THREAD

**Issue by avindra** [FredrikNoren/ungit#760]
Here is the upstream PR to fix it:

https://github.com/foreverjs/forever-monitor/pull/127

```
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

Please track and update if necessary on release.

**Comment by codingtwinky** [comment]
forever-monitor had a very nasty bug for us [previously](https://github.com/FredrikNoren/ungit/issues/528), mores pecifically [#forever-minotor/86](forever-monitor/issues/86).  That is why our forever-monitor dep is very outdated.  

We may try to upgrade and see but I'm little hesitant to do it without window people confirms working

**Comment by campersau** [comment]
We removed the forever-monitor dependency in ungit version 1.1.33 (see #971).
Please open another issue if the issue is still there.
