### ISSUE TITLE
Add an ignore whitespace option for diffs

### ISSUE THREAD

**Issue by daedalus28** [FredrikNoren/ungit#777]
It would be great if we could optionally ignore whitespace changes on diffs (first google result - https://coderwall.com/p/crj69a/from-a-useless-git-diff-to-a-useful-one). Assuming you're using the actual git diff command, it should just be about passing another option. I use ungit as my primary git tool and this is one case that brings me back to command line/other tools.

If you can point me to the place in the code where this happens, I'd be happy to submit a PR for it.

**Comment by codingtwinky** [comment]
Sure, file you would need to update is [dfifFile](https://github.com/FredrikNoren/ungit/blob/master/source/git-promise.js#L256-L287).  I would suggest having this as a variable in [config.js](https://github.com/FredrikNoren/ungit/blob/master/source/config.js) and control that way.

Cheers!
