### ISSUE TITLE
Edits of merge commit message discarded

### ISSUE THREAD

**Issue by dregad** [FredrikNoren/ungit#779]
Today performed a merge operation that caused a conflict. After fixing the problem, I went back to ungit to complete the merge, and modified the default commit message to describe how I had resolved the conflict.

I entered my text in the dialog, but as soon as I moved the mouse to the _Continue Merge_ button, the commit message was reverted to the default, discarding my edit - see screenshot below.

![edit_merge_1](https://cloud.githubusercontent.com/assets/449891/17734725/5641f19c-647e-11e6-9fb1-ef46531da32c.png)

This behavior occurs frequently, but it is not consistently reproducible, so I'm not really sure what is triggering the event. While testing I was sometimes able to complete the merge with the modified commit message.

**Comment by FredrikNoren** [comment]
Hm my guess is that it's because of the mouse move refresh thing (https://github.com/FredrikNoren/ungit/blob/master/public/source/main.js#L83), which triggers a refresh from git, which overwrites the commits message.

**Comment by dregad** [comment]
Thank you! :+1:
