### ISSUE TITLE
Overlapping lines makes causes incorrect display of git history 

### ISSUE THREAD

**Issue by dregad** [FredrikNoren/ungit#804]
Consider the following log history (from https://github.com/ADOdb/ADOdb/commits/43fc38055c415009ec772fcc517d79486a6854e6)

![screenshot-20161011-1304](https://cloud.githubusercontent.com/assets/449891/19268210/5f7a268e-8fb3-11e6-8a26-a731ae279809.png)

The left line is the _master_ branch, while the right one is the _hotfixes_ branch. Ungit incorrectly makes it appear like the commit highlighted with the red arrow is part of the latter, but in fact it's not, as shown in the screenshots below:
- Smartgit log view:  ![screenshot-20161011-1309](https://cloud.githubusercontent.com/assets/449891/19268308/10e3ce98-8fb4-11e6-8b84-241c8667a941.png)
- Github network graph:  ![screenshot-20161011-1311](https://cloud.githubusercontent.com/assets/449891/19268369/695f560a-8fb4-11e6-992c-381da41f65c1.png)

**Comment by dregad** [comment]
Thank you!

**Comment by dregad** [comment]
Hello, any idea when you'll cut the next release so this fix actually becomes available ?

**Comment by codingtwinky** [comment]
I don't have any exact date but we are working on a more permanent solution to have quicker releases, #827.

But if you would like you can manually change the changes in #808 to your installation as it is a very simple fix.

**Comment by dregad** [comment]
Thanks for the feedback. I'll try that.
