### ISSUE TITLE
"Something went wrong, reload the page to start over." onload ungit@0.10.3 which runs in a docker container

### ISSUE THREAD

**Issue by PennYU** [FredrikNoren/ungit#815]
Hi!
I ran ungit v0.10.3 in a docker (v1.12.3) container, the container is running in a CentOS 7.1 host behind a proxy, but there is no proxy in the container. "Something went wrong, reload the page to start over." will come up within 1 minute, this occurs when ungit is not able to get latest version from "https://registry.npmjs.org/ungit".

Logs from Chrome.

server.js:220 Gateway Time-out 504Server._onUnhandledBadBackendResponse @ server.js:220(anonymous function) @ server.js:166httpRequest.onreadystatechange @ server.js:62
server.js:225 Error: Backend error: Gateway Time-out 504
    at Server.query (server.js:139)
    at Server.get (server.js:122)
    at AppViewModel.shown (app.js:74)
    at init (knockout-bindings.js:124)
    at knockout:3303
    at Object.ignore (knockout:1461)
    at knockout:3302
    at Object.arrayForEach (knockout:159)
    at applyBindingsToNodeInternal (knockout:3288)
    at applyBindingsToNodeAndDescendantsInternal (knockout:3168)
    at applyBindingsToDescendantsInternal (knockout:3150)
    at applyBindingsToNodeAndDescendantsInternal (knockout:3177)
    at Object.ko.applyBindings (knockout:3379)
    at knockout:5237
    at invokeForEachNodeInContinuousRange (knockout:5188)
    at activateBindingsOnContinuousNodeArray (knockout:5235)
program-events.js:8 Event: Object {event: "git-crash-error"}
main.js:90 Fire change event due to re-activity
program-events.js:8 Event: Object {event: "working-tree-changed"}
program-events.js:8 Event: Object {event: "init-tooltip"}

I modified “/usr/lib/node_modules/ungit/src/server.js” to skip it, the issue didn't come up any more.

app.get('/api/latestversion', function (req, res) {
  return res.json({}); // skip getting latest version.
  sysinfo.getUngitVersion(function (err, currentVersion) {
    sysinfo.getUngitLatestVersion(function (err, latestVersion) {
      if (err) res.json({ latestVersion: currentVersion, currentVersion: currentVersion, outdated: false });else if (!semver.valid(currentVersi
    });
  });
});

I hope it helps.

Thank you.

**Comment by codingtwinky** [comment]
For that one problem is that we were not correctly handling the cases where Ungit failed fetch the npm source.  if you are behind a proxy I guess network connection fails and throws exception.

This was fixed in recent [promisifie effort](https://github.com/FredrikNoren/ungit/commit/cbb88ef15e57fefab24c2a25357558e723ec5cd0) and this should be fixed once new release is cut.
