### ISSUE TITLE
Endless status requests since #809 on windows

### ISSUE THREAD

**Issue by campersau** [FredrikNoren/ungit#820]
With the new feature from #809 ungit makes endless status requests on windows even though nothing has changed.
Will investigate further over the weekend.

![image](https://cloud.githubusercontent.com/assets/4009570/20634305/a0a30076-b34f-11e6-9262-56e771fd9b60.png)

![image](https://cloud.githubusercontent.com/assets/4009570/20634362/59627d30-b350-11e6-8583-58687d9a7067.png)

/cc @codingtwinky

**Comment by campersau** [comment]
It looks like that also windows supports the [`recursive` option in `fs.watch`](https://nodejs.org/docs/latest/api/fs.html#fs_caveats).
Which means that there are two events for a (e.g. `.git/index.lock`) file.
But by explicitly watching the [`.git` dir](https://github.com/FredrikNoren/ungit/pull/809/files#diff-7cc6d113be128a4ba2e032f8db376ebaR52), the filenames do not [start with `.git`](https://github.com/FredrikNoren/ungit/pull/809/files#diff-7cc6d113be128a4ba2e032f8db376ebaR82) and are not ignored.

E.g. there are two events for `.git/index.lock`:
- filname: `.git/index.lock` (watching the project dir and will be ignored)
- filename: `index.lock` (watching the git dir inside the project dir and will not be ignored)

**Comment by codingtwinky** [comment]
I'm at the aws reinvent event right now so I will circle back to this later but two thoughts: 

1. Thanks for catching the file watcher bug where expected prefixes are omitted.
2. Appveyor test did failed when recurisve is true in windows for some of the new tests I have added in.  Which lead me to believe that file watch even didn't trigger for the `test.commands.js`.

Thanks!
