### ISSUE TITLE
Heirarchical path permissions

### ISSUE THREAD

**Issue by viharm** [FredrikNoren/ungit#822]
- Ungit version 0.10.3
- Debian Jessie 8.6 kernel 3.16.36-1+deb8u2
- NodeJS 6.9.1-1nodesource1~jessie1
- npm 4.0.2
- Apache 2.4.10-10+deb8u7 (not running Ungit, but probably relevant)

Ungit is very good; and I appreciate the hard work in making something so intuitive.

I am trying to create a self-sufficient IDE by combining Codiad for editing and Ungit for Git, as it suits my particular application where these apps are hosted on my home server and I am able to pick up my coding tasks from wherever I am using a browser. Ungit can latch on to Codiad's workspaces and work beautifully.

However if the workspace is in a path whose parent is owned by root or ready-only, it throws in "Invalid Path" error, even if the particular directory is owned by the user running the ungit binary. I can easily get to the same path via console.
```
Invalid path

"[object HTMLScriptElement]" doesn't seem to be a valid path.
```

When I put the workspace in the user's home directory and link Codiad to it, it works OK. However with the files in user's home directory it does not fit with my backup strategy.

Any thoughts on why Ungit would not work unless the entire path is owned or write-enabled for the user running Ungit.

For information Codiad runs under an Apache2 virtual host running as the same user to so files created by both Ungit and Codiad should be accessible by either.

Regards,
viharm

**Comment by viharm** [comment]
Firefox console output

```
The resource from “https://DOMAIN/ROOTPATH/plugins/refreshButton/refreshbutton.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)
....

GET  https://DOMAIN/ROOTPATH/socket.io/ [HTTP/1.1 400 Bad Request 90ms]

Firefox can’t establish a connection to the server at wss://DOMAIN/ROOTPATH/socket.io/?EIO=3&transport=websocket&sid=tvjGTNTJRe2jYM9oAAAF.
```

Hope this helps.

**Comment by codingtwinky** [comment]
What is the chmod and chown result of ungit installation directory?  Also could you possibly answer below questions?

1. how did you install ungit?  did you do `npm -g install ungit` ?
2. how are you starting ungit?  are you starting with root?  

You should be able to install and start ungit without root access and work as you wish to but in some OSs npm -g installation location need some fidgeting to straighten out the access rights.

**Comment by viharm** [comment]
Ungit installation directory: `/usr/lib/node_modules/`
Ownership: `nobody:proxyadmin`
Permissions: `755`

Answers:

1. `sudo -H npm install -g ungit`
1. Ungit is started by the individual users in their respective screen sessions with the following command
    ```bash
    ungit --port=8450 --rootPath="git" --logDirectory="~/.ungit/logs" --forcedLaunchPath="/var/www/User/username" --no-launchBrowser --no-autoFetch
    ```

The additional information is that I am unable to reproduce this; however it does come back :-(

Regards.

**Comment by viharm** [comment]
I am using Ungit in the same environment for a few days now, with no issues; I am unable to reproduce this issue.

Unless you have identified the root cause and working on it, I am happy for this issue to be closed. I will request reopening if I can reproduce the symptoms.


Regards,

**Comment by codingtwinky** [comment]
Was there any changes on your end?  I would like to keep this open until it is confirmed no longer an issue.

**Comment by viharm** [comment]
Understood and agreed. I will monitor this closely and try a few combinations of scenarios and provide feedback.

**Comment by viharm** [comment]
Scenario: All users who need Ungit access belong to group `customgroup`. Example below shown for user `username`.

User directory
- Path: `/var/www/user/username`
- Owner: `username`
- Group: `username`
- Perm: `750`

Parent directory
- Path: `/var/www/user/`
- Owner: `root`
- Group: `customgroup`
- Perm: `750`

Grandparent directory
- Path: `/var/www/`
- Owner: `root`
- Group: `customgroup`
- Perm: `755`

Has been working without issue for several weeks. I believe this can be closed.

@codingtwinky , do you concur?

-Viharm

**Comment by codingtwinky** [comment]
Yes, thank you so much for such a through work and reporting.

Cheers,
