### ISSUE TITLE
Continuous deployment (npm publish on merge)

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#823]
Hi all,

Ungit is a great community driven project, and I'm constantly impressed with all the stuff people are contributing back to this project.

However, I've noticed one big bottleneck to progress: Releases. The way they work today is a strictly manual process, so a person (usually me) has to at some point decided that "now seems like a good time to release" and then perform the release. There's a couple of problems with this:

1. Merge to deploy time is very long. Sometimes it's been months, and even if we try to be more diligent about releasing more often, it will still probably be weeks between a change being merged and users actually seeing that change.
2. This means valuable new features and fixes aren't getting out fast enough to users.
3. Master is "untested". Since only a handful of people use the master branch, it's very hard to catch problems. Often we don't discover bugs until we do a release. At that point it's very hard to know exactly what commit introduced the bug.

Therefore, I'd like to propose that we change to a continuous deployment release system instead of a manual one. On each commit or merge to master, the travis build would automatically calculate a new patch number and push the package to NPM.

There are some drawbacks to this approach, most of all users would be getting a lot more "it's time to upgrade" messages. To make this less distracting I'd suggest we update the UI of this message to something slightly more discreet, or perhaps something that highlights more the older your version is (if it's < 5 patches diff, do a small thing, if it's more do a big dialog).

It's a big change in "how we work" so I'd like to hear what people have to say before making this change (or if someone is interested in taking this on, let me know), so I'll leave this ticket open for a few weeks to gather feedback/input before moving forward.

cc @codingtwinky

**Comment by Ajedi32** [comment]
Are you still planning to use SemVer? How will Travis know whether a particular change is SemVer-patch or SemVer-minor when incrementing the version number?

**Comment by FredrikNoren** [comment]
@Ajedi32 This is how I've done it in other projects: Major and minor versions are manual, to bump them you have to change the actual number in package.json, and create a tag for them. All regular commits are patches, and the patch number is calculated as the number of commits since the last version git-tag.

Maybe there's a better way where a PR could be tagged major/minor version change and all of that would happen automatically though.. not sure.

**Comment by codingtwinky** [comment]
I think it would be good as long as minor version publish requires manual intervention as that is important, which seems to be the direction we are going.

So I'm for this idea.

**Comment by FredrikNoren** [comment]
I've done some digging, and what I suggested before with automatic patch version calculation is actually really hard to pull off (it requires each major/minor release to be a push directly to master, since they also need to have a tag, which in turn means they need manual intervention from one of the repo owners).

Another way of doing this would be to require all patch and feature PRs to actually bump the version number in package.json manually, as well as include a line in the CHANGELOG about the change. Each build on master would then be published to npm in the format version-commit_hash (for instance 0.10.4-87dd7b8) so that we don't conflicts for commits that aren't feature/patch changes (say a README change). The downside of this that we'd have to enforce this ("hey looks good but can you please bump the version and add a line in CHANGELOG?"), but the upside is that I think people might feel a bit more ownership of code changes if they can see the change go out ("0.11.3 was _my_ change, and someone said it broke something, oh maybe I should try to fix that"). Would people be up for trying this?

(cc @campersau too)

**Comment by FredrikNoren** [comment]
See #827 to get an idea of how this would look like in practice.
