### ISSUE TITLE
A manual refresh is required after every command

### ISSUE THREAD

**Issue by givo** [FredrikNoren/ungit#829]
I noticed that you need to manually refresh ungit in order to see the effects of your actions. It can be every little operation like commit, checkout.. 

for example: after committing a new commit the tree doesn't advance

It could be nice if the GUI will update itself after every operation.

**Comment by codingtwinky** [comment]
@givo Thank for the report and this was actually addressed recently in #809 and will be addressed in next release.  

I will be closing this for now but please do reopen with additional comments if I have missed anything.

Thanks!
