### ISSUE TITLE
FileWatcher filename is sometimes null

### ISSUE THREAD

**Issue by campersau** [FredrikNoren/ungit#836]
The node FileWachter sometimes [sends `null` as filename](http://stackoverflow.com/a/9629375).
Which results in an exception in `path.join`. (ungit does NOT crash)

```
2016-12-21T16:37:30.800Z - error: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at FSWatcher.runOnFileWatchEvent (p:\ungit\source\git-api.js:42:35)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1412:12)
```

**Comment by codingtwinky** [comment]
I haven't seen this so I'm going to assume this is an Windows things.  Do you know why windows is sending null file name?

**Comment by campersau** [comment]
No, I don't. The documentation it says:

> Providing filename argument in the callback is only supported on Linux and Windows. Even on supported platforms, filename is not always guaranteed to be provided. Therefore, don't assume that filename argument is always provided in the callback, and have some fallback logic if it is null.

https://nodejs.org/api/fs.html#fs_filename_argument

I will run in debug mode for the next few days and see if the error comes up again.

**Comment by campersau** [comment]
Just FYI: I got this error again during a rebase, where a lot of files were removed.
