### ISSUE TITLE
Credentials prompt for remote repository not appearing on web interface

### ISSUE THREAD

**Issue by viharm** [FredrikNoren/ungit#838]
- Ungit version 0.10.3
- Debian Jessie 8.6 kernel 3.16.36-1+deb8u2
- NodeJS 6.9.2-1nodesource1~jessie1
- npm 3.10.9
- Apache 2.4.10-10+deb8u7 (not running Ungit, but probably relevant)

I am experiencing a similar issue to #107 where prompts for remote repository credentials do not appear on the web interface but on the command line, so have to keep an eye on the command line to enter these details. I run Ungit on a server, so have to SSH in to enter these details - very difficult :-(

Please help.

**Comment by CurtisHumphrey** [comment]
Same issue but on a Mac running it locally. Push entering the password on the command line doesn't seem to work at all.

**Comment by dimitrovs** [comment]
Same problem.

**Comment by FredrikNoren** [comment]
Is this the same issue as #102 ? If so let's move the discussion into that one

**Comment by dimitrovs** [comment]
I don't think it's the same, here we are talking about the credentials for the Git repo not a password for a private key. Ultimately the implementation may be the same though. For instance, check Eclipse Orion, it's a web IDE which comes with Git integration, there the UI handles the Git credentials prompt by throwing up a modal and the credentials are not stored.

**Comment by molda** [comment]
I'm having similar issue and i'm unable to type in my credentials
When i try to go to a repo folder in browser and check terminal i see two prompts for username 
`Username for 'https://github.com': Username for 'https://github.com':` typing in `molda`
then i get prompt for password
`Password for 'https://molda@github.com':` 
but when i type in my password i get another prompt 
`Password for 'https://<my-password-here>@github.com':` 
I never see any prompt on the web interface.

**Comment by wonson** [comment]
Same issue, so i close mine

**Comment by wonson** [comment]
one temporary means to save your day is to set your remote path like this:
http://username:password@remotepath.com/repo.git

though i think this may be a bit insecure.

**Comment by y3nly** [comment]
I have the same issue as well. Ungit 1.1.0 works fine.

**Comment by viharm** [comment]
@y3nly ,
Does 1.1.0 prompt you for remote repo credentials on the web interface?

@FredrikNoren ,
This appears to be a popular issue, and a key requirement for working with remote repositories. Is this on the roadmap?

**Comment by codingtwinky** [comment]
as this being open source I've been simply worked on "what is most interesting right now" and I understand that is not the best prioritization.  

I will jump on this later this weekend unless @FredrikNoren fixes before I do.

Cheers,

**Comment by y3nly** [comment]
@viharm 1.1.0 will give you a prompt in the web interface for the remote repo credentials properly.  I haven't had a chance to check to see which version breaks the prompt yet, and decided to try 1.1.0 because Google DataLab uses it.

**Comment by wonson** [comment]
If it had worked on 1.1.0, then it seems more like a bug than a feature request.

**Comment by viharm** [comment]
@y3nly ,

Thanks for the input. Back to 1.1.0 then, until it is fixed :-)

**Comment by viharm** [comment]
Tried `1.1.10` (in error) and `1.1.0` (as pointed out by @y3nly )

Unfortunately I did not have the same luck with `1.1.0` as @y3nly did.

The credentials prompt appears on the command line (as per the reported behaviour in this issue), but just before the console prompt is the following output

In `1.1.10`
```
Fri, 11 Aug 2017 13:52:32 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at ../usr/lib/node_modules/ungit/src/server.js:76:7
```

In `1.1.0`
```
Fri, 11 Aug 2017 14:01:19 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at ../usr/lib/node_modules/ungit/src/server.js:75:7
```

Removed and reinstalled the latest (`1.1.27` as of 2017-08-11). The console prompt appears without any other output.

Installation output for `1.1.27` is as follows (if it helps)
```
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/bin/ungit -> /usr/lib/node_modules/ungit/bin/ungit
/usr/bin/0ungit-credentials-helper -> /usr/lib/node_modules/ungit/bin/credentials-helper
                                                                                                                                                                            
> uws@0.14.5 install /usr/lib/node_modules/ungit/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0
                                                                                                                                                                            
sh: 1: cannot create build_log.txt: Permission denied
+ ungit@1.1.27
added 691 packages in 46.459s
```

Could it be the symbolic link to the credentials helper? Notice the `0` in the link name.

Environment modified w.r.t. the first post:
- *Ungit* version `1.1.0`, `1.1.10`, `1.1.26`, `1.1.27`
- *Debian Jessie* `8.9` *GNU/Linux* kernel `3.16.43-2+deb8u2`
- *NodeJS* `8.2.1-2nodesource1~jessie1`
- *npm* `5.3.0`
- *Apache* `2.4.10-10+deb8u10` (not running Ungit, but probably relevant)
- *Firefox* `54.0.1` (64-bit)

**Comment by codingtwinky** [comment]
Could you share git version?

**Comment by viharm** [comment]
@codingtwinky ,
Thanks for your efforts on this issue. Apologies for the delay in providing this - I was runnig*Git* version `2.1.4-2.1+deb8u3` (`2.1.4`)

I will try the fix and provide feedback.

**Comment by viharm** [comment]
Created #951 as suggested by @codingtwinky in #950
