### ISSUE TITLE
Codiad integration

### ISSUE THREAD

**Issue by viharm** [FredrikNoren/ungit#839]
I have developed a new *Codiad* plugin to interface with *Ungit*.

It simply opens the workspace or a directory in Ungit.

Plugin repository at https://github.com/viharm/Codiad-OpenUngit

BSD 3-clause license.

Regards.

**Comment by codingtwinky** [comment]
Lovely, feel free to send PR against `README.md` to broadcast this if you would like.  

I'm not too familiar with codiad so I don't know how I could describe it.

**Comment by viharm** [comment]
Not very familiary with pull requests, sorry, but have attempted it in  #842.

**Comment by viharm** [comment]
Thanks for merging.
