### ISSUE TITLE
Error: Cannot find module '../src/config' when trying to install from sources

### ISSUE THREAD

**Issue by adelriosantiago** [FredrikNoren/ungit#850]
I'm having the following issue:

```
module.js:471
    throw err;
    ^

Error: Cannot find module '../src/config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/profile/ungit-development/bin/ungit:4:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

When trying to install from the latest source code. **Why does this happens?** Here are some details:

```
node -v
v.6.9.4
```

```
npm -v
3.10.10
```

**Comment by adelriosantiago** [comment]
It seems that someone else is getting the same issue here: http://stackoverflow.com/questions/41719699/cant-install-ungit-globally-from-downloaded-source-code

**Comment by adelriosantiago** [comment]
Seems to be solved by renaming "source" to "src", maybe some patch changed the directory name without updating the paths.

**Comment by codingtwinky** [comment]
Can you confirm few things?

1. Quick fix you did is changing `../src/config` -> `../source/config` right?  
2. did you do this for other `../src` as well?
2. Is there `src` folder in the ungit installation location?

**Comment by adelriosantiago** [comment]
It is not working yet but this is what I did:

- Renaming "sources" to "src" does solves the error message and ungit now seems to start correctly. However ungit never actually loads when loading the page because it does not found the "/plugins" folder (and several other folders that seem to belong to the /public folder) are not found.

- I didn't rename other folders.

- Before renaming the folder there is no other "src" folders currently.

**Comment by codingtwinky** [comment]
Huh, what version of ungit are you installing?  This is strange because if you changed "sources" to "src" it means that you don't have the latest code.  https://github.com/FredrikNoren/ungit/blob/master/bin/ungit#L4

**Comment by adelriosantiago** [comment]
I'm cloning the latest source from https://github.com/FredrikNoren/ungit, which has no "src" folder. I haven't tested through the global installation although the last time I did that it worked perfectly.

**Comment by campersau** [comment]
So you want to build ungit yourself?
Please read the [CONTRIBUTING](https://github.com/FredrikNoren/ungit/blob/master/CONTRIBUTING.md#getting-started) guide.
You need to run `grunt` which builds the `source` and creates the `src` directory.

**Comment by codingtwinky** [comment]
Ah, @campersau is correct and it is important to understand `npm install ungit` vs `git clone ${UNGIT_GIT_URL}`.  Right out of git repo ungit is not executable, it must be transpiled with `grunt` command to be executable.

**Comment by adelriosantiago** [comment]
My bad! Many thanks everyone! It works great.
