### ISSUE TITLE
Add option to skip version check

### ISSUE THREAD

**Issue by yebrahim** [FredrikNoren/ungit#851]
It's useful to add a config to skip version checks, especially when running ungit as part of another project, where every new release has to be tested first.

**Comment by FredrikNoren** [comment]
@yebrahim feel free to submit a PR

**Comment by codingtwinky** [comment]
Can you clarify on what version check are you talking about?  are you talking about ungit version check or git version check?

**Comment by yebrahim** [comment]
@codingtwinky The ungit version, it pops up in the UI when there's a version difference.
