### ISSUE TITLE
Entering path results in error

### ISSUE THREAD

**Issue by normenmueller** [FredrikNoren/ungit#861]
After upgrading to v1.1.5, I get the following error:

1. First I launch `ungit` just as normal
1. Ungit web page opens, initialized with my home dir `/Users/nrm`
1. Trying to append a `/` results in an error, e.g., `/Users/nrm/`
>Whooops
>Something went wrong, reload the page to start over.

Any ideas?

**Comment by campersau** [comment]
Yes, we missed [this](https://github.com/FredrikNoren/ungit/blob/5a52f8e67c4a511e839aeeb63126162e8589c85f/public/source/main.js#L55) during promisification in #852 

It should be `server.getPromise` instead of `server.get`.

cc @codingtwinky

**Comment by normenmueller** [comment]
Ah. OK. Thanks.

Will you a release a fixed version, e.g., v1.1.6?

**Comment by codingtwinky** [comment]
Ahh poopsicles...  didn't do `.get(` global search on the source folder...  

Thanks @campersau

**Comment by normenmueller** [comment]
How can I get this fix?

**Comment by codingtwinky** [comment]
Sorry! getting used to this new deploy and forgot to bump the version in `package.json`.  it is now merged and I think it should cut new npm package soon.  Sorry about that... I've been sloppy lately...

cc: @FredrikNoren

**Comment by codingtwinky** [comment]
@FredrikNoren Hmm, CD is not triggering with this PR https://github.com/FredrikNoren/ungit/pull/863.  Am I missing something else?

**Comment by codingtwinky** [comment]
Ah nvm, it was triggered and ungit@1.1.6 is cut now. I should have waited more... :P

https://www.npmjs.com/package/ungit

**Comment by codingtwinky** [comment]
Will be closing this issue now, please let me know if you see any other problems!
