### ISSUE TITLE
diff box is often displayed out of the screen 

### ISSUE THREAD

**Issue by capaj** [FredrikNoren/ungit#868]
if a selected commit is in the left side of the screen(1/3rd of the screen), the diff box position is not on the screen. See screen:

![screenshot-localhost 8448-2017-02-13-09-48-48](https://cloud.githubusercontent.com/assets/1305378/22876718/4ad32402-f1d2-11e6-8a39-6c5ac6e166c2.png)

Selecting a commit which is more to the right side of the screen displays diff box correctly.

**Comment by codingtwinky** [comment]
I think it's same issue as #858.  Can you upgrade and test again?

**Comment by capaj** [comment]
@codingtwinky yes, this is now fixed as I am testing 1.1.7
