### ISSUE TITLE
Feature proposition: Read-only mode

### ISSUE THREAD

**Issue by mtancoigne** [FredrikNoren/ungit#869]
Hi!

I really like how Ungit looks and I think a read only mode may be interesting for presentation purposes.

I don't know if it's easily achievable, but that would be a real good thing to explain the work done, the git mechanisms or whatever can be presented around Git.

@codingtwinky, as asked, here is the proposition discussed on Gitter earlier.

**Comment by bes-internal** [comment]
It seems strange to demand it from a web interface to git. In most git documentation it says that he knows nothing about the access rights. Ie it can be done at the file system level, forbidding writing in .git directory content.
May be some other variants with --bare repository...

**Comment by mtancoigne** [comment]
@bes-internal Y'oure right, but maybe a cache system or something, to build the commits tree... or an export command... I don't really know how that can be done...

**Comment by bes-internal** [comment]
The easiest way to do this is bare repository `git clone --bare`. You can not make checkout, create branches, uncommit, cherry-pick and etc, but create/delete tags. 
Another way to set read-only attribute into .git directory. How to do this depends on your operating system

**Comment by mtancoigne** [comment]
I tried with the `bare` option and I think it's almost the right thing :) Thanks for pointing this out. I'll close this issue now.
