### ISSUE TITLE
Bug: load hidden lines in stage diff doesn't work without event fired

### ISSUE THREAD

**Issue by bes-internal** [FredrikNoren/ungit#875]
![screen_20170223-184324](https://cloud.githubusercontent.com/assets/2046529/23266789/e303f858-f9f9-11e6-9468-731f806cc8c3.png)

In stage file diff button "Load N more lines" work only if events fired
```
Event: Object {event: "working-tree-changed"}
program-events.js:8 Event: Object {event: "init-tooltip"}
```
ungit 1.1.7
node 6.9.4

**Comment by codingtwinky** [comment]
Ah... that is 100% my f up.  Really do need to add that click test as well.  Thanks! will work over the weekends when things settles down
