### ISSUE TITLE
Broken diff out if the code contains table

### ISSUE THREAD

**Issue by bes-internal** [FredrikNoren/ungit#881]
If the block header and the "<table" in diff is the same line that breaks out. Most likely diff previously should be html-escaped

![screen_20170303-183127](https://cloud.githubusercontent.com/assets/2046529/23558883/51389cd2-0046-11e7-984d-14887d0d5428.png)

**Comment by codingtwinky** [comment]
I've been meaning to test this one my own and reach out to @rtfpessoa from [diff2html](https://github.com/rtfpessoa/diff2html) team but I have been traveling so much lately and it seems that I will continue to travel.  

Ungit uses diff2html and I think that is where this bug lies at.  Can you possibly coordinate with those guys?

**Comment by rtfpessoa** [comment]
@bes-internal can you provide the diff output for me to test?

**Comment by rtfpessoa** [comment]
I grabbed a random project from GitHub with HTML diffs and seems fine in my demo page https://diff2html.xyz/demo?diff=https://github.com/hakimel/Kort/commit/7fbdfb420649742f0be7e147753fbf89728a121e

**Comment by bes-internal** [comment]
broken example:
https://diff2html.xyz/demo?diff=https://github.com/bes-internal/ungit/commit/ded2634a429db78fbe4d0f8b94c1a4a6391fc359

need to html-escape
it seems to me that this is a potential vulnerability
ref: https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

**Comment by rtfpessoa** [comment]
@bes-internal thanks for the help. Just found the problem, when a header line has html it is not being properly escaped.

I will be releasing a new version to fix this in the next few hours.

**Comment by rtfpessoa** [comment]
Fix released as version `v2.3.0`
