### ISSUE TITLE
Commit message lost when git returns error code

### ISSUE THREAD

**Issue by bakkerthehacker** [FredrikNoren/ungit#882]
When committing something using ungit, and the commit fails in some way with git returning a non-zero error code, the commit message (title and body) entered into ungit is removed.  

This is particularly frustrating when ungit is used with pre-commit hooks.  These hooks modify code and use the non-zero git return code to allow you to inspect and re-commit the automatic changes.  

In an older version of ungit (not sure which, I could bisect), when git / pre-commit hooks returned non-zero code, the commit message was preserved in the ungit UI.  This allowed me to simply press the commit button and see if the pre-commit hooks did anything and press commit again if they did.  

In the current version, if the pre-commit hooks fires, I have to retype my commit message.  This is a bit cumbersome, and I have worked around it at the moment by copying my message before committing in case the hook fires and I have to paste in the text again.

**Comment by dregad** [comment]
Sounds related to #831

**Comment by capaj** [comment]
@bakkerthehacker I have the same exact frustration! Should be an easy fix.
