### ISSUE TITLE
Toggle all button works inconsistently when files are committed

### ISSUE THREAD

**Issue by MatthewTamlin** [FredrikNoren/ungit#883]
Committing causes the toggle all button to become out of sync with the actual toggled state of the files in the change list. 

**Steps to recreate:**
1. Start ungit and open a repo.
2. Modify three or more files in the repo.
3. Deselect all but one file, and commit the changes to that file.

At this point all remaining files become selected but the toggle-all button displays as it does when nothing is selected. Clicking the toggle-all button at this point _should_ deselect everything, but instead it does nothing. A second click on the button gets it back into sync with the files.

**Screenshots:**
Before committing:
<img width="1607" alt="screen shot 2017-03-04 at 10 23 27" src="https://cloud.githubusercontent.com/assets/17073761/23573376/69421644-00c5-11e7-84d8-6c8c2c8930f5.png">
After committing:
<img width="1629" alt="screen shot 2017-03-04 at 10 24 01" src="https://cloud.githubusercontent.com/assets/17073761/23573383/6dc34e22-00c5-11e7-8e79-16ea201e32df.png">
After clicking toggle-all once:
<img width="1646" alt="screen shot 2017-03-04 at 10 24 15" src="https://cloud.githubusercontent.com/assets/17073761/23573384/7185bebe-00c5-11e7-8159-a19bf55fb70f.png">
After clicking toggle-all twice:
<img width="1635" alt="screen shot 2017-03-04 at 10 24 23" src="https://cloud.githubusercontent.com/assets/17073761/23573386/73980266-00c5-11e7-80bd-afd69285ed9a.png">

**System details:**
OS: MacOS 10.12.3
Browser: Safari 10.0.3 (also occurs in Chrome 56.0.2924.87)
Ungit version: 1.1.2
NPM version: 4.3.0
Node version: 7.6.0

**Comment by bes-internal** [comment]
Fixed in 1.1.5 #860 
Please update your ungit installation

**Comment by MatthewTamlin** [comment]
Sorry I thought I had the latest version already.
