### ISSUE TITLE
UI elements size

### ISSUE THREAD

**Issue by danielo515** [FredrikNoren/ungit#884]
Hello,

Thank you for this great tool, it is very nice-looking and rich in features.
One of my favourite things is how it shows the branches tree, far better than any other interface I used before. However, the ui has a small problem to me: everything is TOO BIG. If I want to navigate the branches tree I am only able to see a couple of giant balloons. Of course I can use the browser zooming feature, but then other parts of the UI become too small, and impossible to use, which forces me to switch the zoom constantly. Ideally, I would love tho have a zoom button on the tree view that zooms in and out just the branches tree, maybe leaving the messages and other text the same size for readability.

Thanks and regards.

**Comment by bes-internal** [comment]
At the zoom 70-90 everything fits perfectly.
![screen_20170316-160800](https://cloud.githubusercontent.com/assets/2046529/23997547/c17738f2-0a62-11e7-90d5-df6cb2a6389f.png)

**Comment by danielo515** [comment]
Yeah, that in your screen and with a very simple branch architecture. As soon as you add a couple of more it becomes unreadable. I'll post some screenshots.

**Comment by FredrikNoren** [comment]
@danielo515 yeah I agree, it could def use some work. This is being discussed here already so closing this one as a dupe: https://github.com/FredrikNoren/ungit/issues/477
