### ISSUE TITLE
How to push

### ISSUE THREAD

**Issue by danielo515** [FredrikNoren/ungit#885]
Hello,

Sorry but I can't see any button for making a `git push`. Could you please guide me a bit?

**Comment by bes-internal** [comment]
https://www.youtube.com/watch?v=hkBVAi3oKvo

**Comment by danielo515** [comment]
Thanks

However, please consider putting some written instructions or screenshots. Sometimes watching a video is not easy or feasible.

**Comment by codingtwinky** [comment]
I totally agree and feel free to submit documentation PRs! 

I did have an issue talking about possibly doing gif demo of each features somewhere...

**Comment by janat08** [comment]
push is done by clicking on branch label on diagram, after which push button appears.
