### ISSUE TITLE
UBlock Origin blocks calls and causes Ungit to fail "Whoops. Something went wrong..."

### ISSUE THREAD

**Issue by LukeDWood** [FredrikNoren/ungit#888]
I use UBlock Origin on Chrome and it started blocking calls from Ungit, causing it to fail for seemingly no reason.
Ungit didn't output any specific error messages to help diagnose this issue.

![image](https://cloud.githubusercontent.com/assets/13216206/24350677/057038ee-12db-11e7-8b0a-2fadd41490b6.png)

UBlock Version: uBlock Origin v1.11.4
Ungit Version: 1.1.11
Chrome Version: 56.0.2924.87

**Comment by LukeDWood** [comment]
I doubt this is an issue with Ungit but it's something you might like to be made aware of.

**Comment by campersau** [comment]
See https://github.com/FredrikNoren/ungit/issues/887#issuecomment-289040896

**Comment by LukeDWood** [comment]
I should really check before posting new issues, thanks.
