### ISSUE TITLE
Ungits page crashes when viewed in latest Firefox on Linux

### ISSUE THREAD

**Issue by keiter** [FredrikNoren/ungit#889]
Hello!
Ungit stopped working after the latest Firefox update this weekend. The error manifests as getting the "whoops" page as soon as you try to load a repo. I confirmed that the error was down to what browser was being used, Chromium and Brave both work. I've Attached the output from the Firefox javascript console. I'm using Firefox 52.0.1 on Linux Mint 18. Let me know if you have any more questions about my system or such.

[ungit-error.txt](https://github.com/FredrikNoren/ungit/files/872647/ungit-error.txt)

**Comment by campersau** [comment]
Maybe this is a problem with some of your browser extensions. See #887

**Comment by ylecuyer** [comment]
duplicate of #874

**Comment by keiter** [comment]
@campersau yeah it was indeed that, thanks! disregard this issue
