### ISSUE TITLE
socketId

### ISSUE THREAD

**Issue by swisslens** [FredrikNoren/ungit#890]
after updating to 1.1.11 from 1.1.3, launching ungit gives me the help text and an error "Unknown argument: socketId"

**Comment by campersau** [comment]
Yes, I had the same issue.
Please remove the `socketId` entry from your [`.ungitrc` file](https://github.com/FredrikNoren/ungit/blob/352a7d2b7470006ed2b4ed28cdabdf992fbc86c3/README.md#configuring) 

---

I think it has something to do with https://github.com/FredrikNoren/ungit/commit/6c2496a56067febaf6e8e61f1b43bb05ba3f0a10 from @bes-internal 

Here is a sample `.ungitrc` file which failes at [line 223 in config.js](https://github.com/FredrikNoren/ungit/blob/master/source/config.js#L223)
```json
{
  "bugtracking": true,
  "socketId": 0
}
```

cc: @codingtwinky

**Comment by bes-internal** [comment]
Previously .ungitrc was processed by the rc module. But now it passes through yargs. So if the "socketId" is actually used it should be simply described in [yargs at config.js:143](https://github.com/FredrikNoren/ungit/blob/master/source/config.js#L143)

**Comment by codingtwinky** [comment]
Huh.. I don't even remember `socketId` config... what was it for?

**Comment by LimeBlast** [comment]
I have the same issue. I removed the line from the file, and now I'm just getting "whoops, something went wrong"

**Comment by codingtwinky** [comment]
@LimeBlast it's nice to hear that we have resolve a bug.  For your next error, can you either add your logs to existing issues or open a new one if it something different?  Thanks,

**Comment by LimeBlast** [comment]
@codingtwinky I feel there's some miscommunication here. The bug hasn't been resolved (I'm getting "whoops, something went wrong" when running ungit), and I am posting in an existing issue.

I will admit to not having posted my logs, but that's because I don't know how to get said logs. If you can let me know where to find these, I'll happily post them.

**Comment by codingtwinky** [comment]
Ah, I was referring to the `socketId` config value being set.  I think that is a separate issue than the "woops, ..." you are seeing, which I think you have moved on from if I understand correctly.

One thing you could do is to share the command line output of the terminal that is running the ungit preferably via gist.github.com.  Thanks!

**Comment by codingtwinky** [comment]
On the side note, maybe we should take off strict from yargs?  initial intention was to make sure people, mainly me, wouldn't make typo mistake on config variable names but it seems that it is causing more headaches... 

cc: @bes-internal @FredrikNoren

**Comment by campersau** [comment]
@LimeBlast Maybe this is a problem with some of your browser extensions. See #887
We are currently getting a lot of issues about this...

**Comment by bes-internal** [comment]
@codingtwinky Yes, this should be done when there are unused options. `socketId` is this? Because we do not want to make complex migrations and follow all this. Let's go along the easy path

**Comment by swisslens** [comment]
@campersau Thx for the advice on deleting socketId in .ungitrc and the issue #887. I deactivated my adblock and ungit worked properly.
