### ISSUE TITLE
Ungit crash on Firefox

### ISSUE THREAD

**Issue by dregad** [FredrikNoren/ungit#892]
Greetings,

I am running Ungit on a Cloud9 workspace (Ubuntu 14.04). This has been working just fine for many months, but today I am getting _Whooops Something went wrong, reload the page to start over._  There haven't been any changes on the system . I tried upgrading Ungit (from 1.10.3 to 1.10.11), but the problem persists.

It's worth mentioning that the error occurs only with Firefox. When using Chrome Ungit loads just fine, no idea why.

I am not seeing any errors on the server side (with --logLevel=debug)
```
2017-03-29T14:45:06.406Z - info: Start watching /home/ubuntu/workspace/adodb recursively
2017-03-29T14:45:06.406Z - info: Start watching with .git and .git/refs/[heads|remotes|tags]
2017-03-29T14:45:09.447Z - info: emitting git-directory-changed to sockets, manually triggered
```

On the client, the console shows
```
App version: 1.1.11 mantis-dregad.c9users.io:8081:32:2
Initing raven mantis-dregad.c9users.io:8081:34:3
unreachable code after return statement ungit.js:19770:4
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create ungit.js:22079:9
unreachable code after return statement ungit.js:19770:4
Google analytics inited mantis-dregad.c9users.io:8081:914:3
Keen.io inited mantis-dregad.c9users.io:8081:921:3
Event: Object { event: "navigated-to-path", path: "/home/ubuntu/workspace/adodb" } ungit.js:50666:3
Event: Object { event: "navigation-changed", path: "repository?path=%2Fhome%2Fubuntu%2F…", oldPath: undefined } ungit.js:50666:3
Event: Object { event: "connected" } ungit.js:50666:3
Unhandled Promise ERROR:  Exception { message: "", result: 2153644038, name: "", filename: "https://mantis-dregad.c9users.io:80…", lineNumber: 5569, columnNumber: 0, data: null, stack: "require<[42]</Server.prototype._htt…", 2 de plus… } Object { _bitField: 16777216, _fulfillmentHandler0: Exception, _rejectionHandler0: undefined, _promise0: undefined, _receiver0: undefined, _trace: Object } ungit.js:5667:5

Event: Object { event: "git-crash-error" } ungit.js:50666:3
Event: Object { event: "current-remote-changed", newRemote: "origin" } ungit.js:50666:3
Event: Object { event: "init-tooltip" } ungit.js:50666:3
Event: Object { event: "remote-tags-update", tags: Array[74] } ungit.js:50666:3
Event: Object { event: "git-directory-changed" } ungit.js:50666:3
Unhandled Promise ERROR:  Exception { message: "", result: 2153644038, name: "", filename: "https://mantis-dregad.c9users.io:80…", lineNumber: 5569, columnNumber: 0, data: null, stack: "require<[42]</Server.prototype._htt…", 2 de plus… } Object { _bitField: 16777216, _fulfillmentHandler0: Exception, _rejectionHandler0: undefined, _promise0: undefined, _receiver0: undefined, _trace: Object } ungit.js:5667:5

Event: Object { event: "git-crash-error" } ungit.js:50666:3
Fire change event due to re-activity ungit.js:50525:7
Event: Object { event: "working-tree-changed" } ungit.js:50666:3
L'utilisation de « getPreventDefault() » est obsolète. Utiliser « defaultPrevented » à la place. ungit.js:6469:12223
Event: Object { event: "init-tooltip" } ungit.js:50666:3
```

Not sure what to do next (except using Chrome :wink:) - your advice would be appreciated. If you need further information, please let me know.

Thanks in advance

**Comment by campersau** [comment]
Maybe this is a problem with some of your browser extensions. See #887
We are currently getting a lot of issues about this...

**Comment by dregad** [comment]
@campersau many thanks for the hint. After reading #887, I tried Firefox without extensions (why didn't I think of that before !?), and it worked perfectly. Then I re-enabled them one-by-one, to find out that [Adblock plus](https://adblockplus.org) was causing the issue. I will analyze this in further details and report the problem to them. Thanks again.

**Comment by dregad** [comment]
For the record, the block is triggered by the [_easyprivacy_ filter](https://easylist-downloads.adblockplus.org/easyprivacy.txt), offending filters are

- /keen.min.js (script)
- /api/log? (XML request)
- ||google-analytics.com/analytics.js (script)

**Comment by campersau** [comment]
Thanks @dregad !

This is the evil commit: https://github.com/easylist/easylist/commit/12fa20426b014f4d733400778147ffb84ca6e5a3
