### ISSUE TITLE
Explore Nightmare as alternative to PhantomJS

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#894]
https://github.com/segmentio/nightmare

We've had a lot of stability issues with the "click-tests" (should probably be renamed functional tests). Phantom is running against an old webkit version as far as I can tell, whereas nightmare is much more modern (they claim a 2x speedup compared to Phantom as well). On top of that, we could get rid of a lot of the [helper](https://github.com/FredrikNoren/ungit/blob/master/clicktests/helpers.js) functions as nightmare provides a lot of that for you.

**Comment by campersau** [comment]
This was implemented in #931
