### ISSUE TITLE
Remove Grunt

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#895]
Grunt is pretty dead by now. We could probably refactor the build script into something much simpler in just plain JS

**Comment by codingtwinky** [comment]
I like how mocha testings, bumping up dependencies, transpiling and other actions have a single point of entry.  Do you really mean to get rid of Grunt? or replace with other solutions such as gulp or maybe even a make file?

**Comment by FredrikNoren** [comment]
I think most people just do plain .js build files these days (no gulp, no makefile). With async/await it's pretty easy to do multi-step asynchronous operations.

**Comment by codingtwinky** [comment]
What about babel? should we step away from that?

**Comment by FredrikNoren** [comment]
Bable is only used to make sure the backend code is compatible with old node versions right? If we removed it, the min version would be 6? Or 7?

**Comment by codingtwinky** [comment]
I think our code base will be at node 6 and considering client side code isn't es6 I think it is more safer.  Honestly, babel is something that is seemingly becoming an industry standard that I don't personally have a strong affinity for so I don't really mind it but I would like for us to understand that it means we are limiting backward compatibility if we decided to keep es6 on server side.

**Comment by FredrikNoren** [comment]
Personally, I'm perfectly fine with only supporting the "live" versions of node; 6 is the current LTS. Either way, removing grunt doesn't necessarily mean we have to remove Babel

**Comment by codingtwinky** [comment]
I'd be okay with just supporting node 5+ as well.  Hopefully there are not many complaints...
