### ISSUE TITLE
Enabling send usage statistics crashes ungit

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#912]
Got the following error:

![screen shot 2017-05-02 at 1 41 00 pm](https://cloud.githubusercontent.com/assets/1288009/25616467/2e7a864e-2f3d-11e7-9d8a-71a47a4e811b.png)

@codingtwinky

**Comment by campersau** [comment]
Broken since https://github.com/FredrikNoren/ungit/commit/b48319d1bd5dcf8a0e30c3f746e7930884b9b74c

In `gitSetUserConfig` `this` is refering to the global `window` instead of `AppViewModel` https://github.com/FredrikNoren/ungit/blob/master/components/app/app.js#L123-L132
