### ISSUE TITLE
Confirm for move last branch on rev to another rev

### ISSUE THREAD

**Issue by bes-internal** [FredrikNoren/ungit#914]
in this situation ungit silently performs destructive action

![screen_20170504-113016](https://cloud.githubusercontent.com/assets/2046529/25695876/83be3c50-30bd-11e7-97a6-178659d1bfd9.png)

**Comment by benito103e** [comment]
:+1: Moreover, it would be good to be able to disable the "move" feature trough the config file.

**Comment by benito103e** [comment]
#473
