### ISSUE TITLE
TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by capaj** [FredrikNoren/ungit#922]
![image](https://cloud.githubusercontent.com/assets/1305378/26341018/d6f08a58-3f91-11e7-9424-9139c960bc03.png)

Ungit 1.1.7

**Comment by bes-internal** [comment]
Please upgrade your ungit to latest 1.1.19 version. And try again

**Comment by codingtwinky** [comment]
Please feel free to reopen if problem persists.
