### ISSUE TITLE
npm node js installation error in ubuntu

### ISSUE THREAD

**Issue by arvi9873451821** [FredrikNoren/ungit#923]
npm http 200 https://registry.npmjs.org/ng2-tree
npm http 200 https://registry.npmjs.org/ng2-ckeditor
npm http 200 https://registry.npmjs.org/jasmine-core/-/jasmine-core-2.5.2.tgz
npm http GET https://registry.npmjs.org/rxjs/-/rxjs-5.1.1.tgz
npm http 200 https://registry.npmjs.org/normalize.css
npm http 200 https://registry.npmjs.org/ionicons
npm http 200 https://registry.npmjs.org/fullcalendar/-/fullcalendar-3.3.1.tgz
npm http 200 https://registry.npmjs.org/karma-jasmine
npm http 200 https://registry.npmjs.org/karma-jasmine-html-reporter
npm http 200 https://registry.npmjs.org/karma-cli
npm http 200 https://registry.npmjs.org/karma-coverage-istanbul-reporter
npm http 200 https://registry.npmjs.org/bootstrap
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/chart.js
npm http GET https://registry.npmjs.org/karma-chrome-launcher/-/karma-chrome-launcher-2.0.0.tgz
npm http 200 https://registry.npmjs.org/leaflet-map
npm http GET https://registry.npmjs.org/wintersmith/-/wintersmith-2.2.5.tgz
npm http GET https://registry.npmjs.org/ng2-tree/-/ng2-tree-2.0.0-alpha.5.tgz
npm http GET https://registry.npmjs.org/ng2-ckeditor/-/ng2-ckeditor-1.1.6.tgz
npm http 200 https://registry.npmjs.org/ckeditor/-/ckeditor-4.6.2.tgz
npm http 200 https://registry.npmjs.org/google-maps/-/google-maps-3.2.1.tgz
npm http GET https://registry.npmjs.org/normalize.css/-/normalize.css-6.0.0.tgz
npm http GET https://registry.npmjs.org/ionicons/-/ionicons-2.0.1.tgz
npm http GET https://registry.npmjs.org/karma-jasmine/-/karma-jasmine-1.1.0.tgz
npm http GET https://registry.npmjs.org/karma-jasmine-html-reporter/-/karma-jasmine-html-reporter-0.2.2.tgz
npm http 200 https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz
npm http GET https://registry.npmjs.org/karma-cli/-/karma-cli-1.0.1.tgz
npm http GET https://registry.npmjs.org/karma-coverage-istanbul-reporter/-/karma-coverage-istanbul-reporter-0.2.0.tgz
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.6.1.tgz
npm http GET https://registry.npmjs.org/bootstrap/-/bootstrap-4.0.0-alpha.6.tgz
npm http GET https://registry.npmjs.org/chart.js/-/chart.js-1.1.1.tgz
npm http 200 https://registry.npmjs.org/tslint-eslint-rules
npm http 200 https://registry.npmjs.org/ng2-completer/-/ng2-completer-1.3.1.tgz
npm http GET https://registry.npmjs.org/leaflet-map/-/leaflet-map-0.2.1.tgz
npm http 200 https://registry.npmjs.org/standard-changelog
npm http 404 https://registry.npmjs.org/angular/router
npm http 200 https://registry.npmjs.org/stylelint
npm http GET https://registry.npmjs.org/tslint-eslint-rules/-/tslint-eslint-rules-3.5.1.tgz
npm http 404 https://registry.npmjs.org/angular/platform-server
npm http 404 https://registry.npmjs.org/angular/compiler-cli
npm http GET https://registry.npmjs.org/standard-changelog/-/standard-changelog-1.0.1.tgz
npm http 200 https://registry.npmjs.org/npm-run-all
npm http GET https://registry.npmjs.org/stylelint/-/stylelint-7.10.1.tgz
npm http 200 https://registry.npmjs.org/tslint
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/angular2-datatable/-/angular2-datatable-0.6.0.tgz
npm http 200 https://registry.npmjs.org/gh-pages
npm http GET https://registry.npmjs.org/npm-run-all/-/npm-run-all-4.0.2.tgz
npm http 200 https://registry.npmjs.org/ngx-uploader
npm http 200 https://registry.npmjs.org/zone.js
npm http GET https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz
npm http 200 https://registry.npmjs.org/jquery-slimscroll/-/jquery-slimscroll-1.3.8.tgz
npm http GET https://registry.npmjs.org/tslint/-/tslint-4.5.0.tgz
npm http GET https://registry.npmjs.org/gh-pages/-/gh-pages-0.12.0.tgz
npm http GET https://registry.npmjs.org/ngx-uploader/-/ngx-uploader-2.2.5.tgz
npm http GET https://registry.npmjs.org/zone.js/-/zone.js-0.8.5.tgz
npm http 200 https://registry.npmjs.org/ts-node
npm http GET https://registry.npmjs.org/ts-node/-/ts-node-2.0.0.tgz
npm http 200 https://registry.npmjs.org/typogr
npm http GET https://registry.npmjs.org/typogr/-/typogr-0.6.6.tgz
npm http 200 https://registry.npmjs.org/protractor/-/protractor-5.1.0.tgz
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.8.3.tgz
npm http 200 https://registry.npmjs.org/roboto-fontface
npm http 404 https://registry.npmjs.org/types/lodash
npm http GET https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.7.0.tgz
npm http 404 https://registry.npmjs.org/angular/platform-browser
npm http 404 https://registry.npmjs.org/types/fullcalendar
npm http 200 https://registry.npmjs.org/karma-chrome-launcher/-/karma-chrome-launcher-2.0.0.tgz
npm http 200 https://registry.npmjs.org/karma-jasmine-html-reporter/-/karma-jasmine-html-reporter-0.2.2.tgz
npm http 200 https://registry.npmjs.org/ng2-ckeditor/-/ng2-ckeditor-1.1.6.tgz
npm http 200 https://registry.npmjs.org/rxjs/-/rxjs-5.1.1.tgz
npm http 200 https://registry.npmjs.org/chroma-js
npm http 200 https://registry.npmjs.org/codelyzer
npm http GET https://registry.npmjs.org/chroma-js/-/chroma-js-1.3.3.tgz
npm http 200 https://registry.npmjs.org/ng2-smart-table
npm http 200 https://registry.npmjs.org/wintersmith-sassy
npm http GET https://registry.npmjs.org/codelyzer/-/codelyzer-2.0.0.tgz
npm http GET https://registry.npmjs.org/ng2-smart-table/-/ng2-smart-table-1.0.3.tgz
npm http GET https://registry.npmjs.org/wintersmith-sassy/-/wintersmith-sassy-1.1.0.tgz
npm http 404 https://registry.npmjs.org/types/jasmine
npm http 404 https://registry.npmjs.org/types/node
npm http 200 https://registry.npmjs.org/standard-changelog/-/standard-changelog-1.0.1.tgz
npm http 200 https://registry.npmjs.org/tslint-eslint-rules/-/tslint-eslint-rules-3.5.1.tgz
npm http 200 https://registry.npmjs.org/chartist
npm http GET https://registry.npmjs.org/chartist/-/chartist-0.10.1.tgz
npm http 200 https://registry.npmjs.org/tslint-language-service/-/tslint-language-service-0.9.2.tgz
npm http 200 https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm http 200 https://registry.npmjs.org/gh-pages/-/gh-pages-0.12.0.tgz
npm http 200 https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/jquery/-/jquery-3.2.1.tgz
npm http 200 https://registry.npmjs.org/ts-node/-/ts-node-2.0.0.tgz
npm http 404 https://registry.npmjs.org/ng-bootstrap/ng-bootstrap
npm http 200 https://registry.npmjs.org/ionicons/-/ionicons-2.0.1.tgz
npm http 200 https://registry.npmjs.org/ng2-handsontable
npm http GET https://registry.npmjs.org/ng2-handsontable/-/ng2-handsontable-0.48.0.tgz
npm http 200 https://registry.npmjs.org/wintersmith/-/wintersmith-2.2.5.tgz
npm http 200 https://registry.npmjs.org/animate.css
npm http GET https://registry.npmjs.org/animate.css/-/animate.css-3.5.2.tgz
npm http 200 https://registry.npmjs.org/karma-jasmine/-/karma-jasmine-1.1.0.tgz
npm http 404 https://registry.npmjs.org/angular/cli
npm http 200 https://registry.npmjs.org/leaflet-map/-/leaflet-map-0.2.1.tgz
npm http 200 https://registry.npmjs.org/typogr/-/typogr-0.6.6.tgz
npm http 200 https://registry.npmjs.org/tslint/-/tslint-4.5.0.tgz
npm http 404 https://registry.npmjs.org/ngx-translate/core
npm http 404 https://registry.npmjs.org/angular/compiler
npm http 200 https://registry.npmjs.org/chartist/-/chartist-0.10.1.tgz
npm http 404 https://registry.npmjs.org/ammap3
npm http 200 https://registry.npmjs.org/normalize.css/-/normalize.css-6.0.0.tgz
npm http 200 https://registry.npmjs.org/stylelint/-/stylelint-7.10.1.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz
npm http 200 https://registry.npmjs.org/ng2-slim-loading-bar
npm http GET https://registry.npmjs.org/ng2-slim-loading-bar/-/ng2-slim-loading-bar-4.0.0.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.6.1.tgz
npm http 404 https://registry.npmjs.org/angular/common
npm http 200 https://registry.npmjs.org/karma-cli/-/karma-cli-1.0.1.tgz
npm http 404 https://registry.npmjs.org/amcharts3
npm http 200 https://registry.npmjs.org/ng2-tree/-/ng2-tree-2.0.0-alpha.5.tgz
npm http 200 https://registry.npmjs.org/easy-pie-chart
npm http GET https://registry.npmjs.org/easy-pie-chart/-/easy-pie-chart-2.1.7.tgz
npm http 200 https://registry.npmjs.org/karma
npm http 200 https://registry.npmjs.org/animate.css/-/animate.css-3.5.2.tgz
npm http 200 https://registry.npmjs.org/npm-run-all/-/npm-run-all-4.0.2.tgz
npm http 200 https://registry.npmjs.org/ng2-handsontable/-/ng2-handsontable-0.48.0.tgz
npm http 200 https://registry.npmjs.org/jasmine-spec-reporter
npm http 200 https://registry.npmjs.org/leaflet/-/leaflet-0.7.7.tgz
npm http GET https://registry.npmjs.org/karma/-/karma-1.4.1.tgz
npm http GET https://registry.npmjs.org/jasmine-spec-reporter/-/jasmine-spec-reporter-3.2.0.tgz
npm http 200 https://registry.npmjs.org/chart.js/-/chart.js-1.1.1.tgz
npm http 200 https://registry.npmjs.org/karma-coverage-istanbul-reporter/-/karma-coverage-istanbul-reporter-0.2.0.tgz
npm http 200 https://registry.npmjs.org/chroma-js/-/chroma-js-1.3.3.tgz
npm http 200 https://registry.npmjs.org/zone.js/-/zone.js-0.8.5.tgz
npm http 200 https://registry.npmjs.org/bootstrap/-/bootstrap-4.0.0-alpha.6.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.8.3.tgz
npm http 200 https://registry.npmjs.org/easy-pie-chart/-/easy-pie-chart-2.1.7.tgz
npm http 200 https://registry.npmjs.org/ng2-slim-loading-bar/-/ng2-slim-loading-bar-4.0.0.tgz
npm http 200 https://registry.npmjs.org/ng2-smart-table/-/ng2-smart-table-1.0.3.tgz
npm http 200 https://registry.npmjs.org/typescript
npm http 200 https://registry.npmjs.org/codelyzer/-/codelyzer-2.0.0.tgz
npm http GET https://registry.npmjs.org/typescript/-/typescript-2.3.2.tgz
npm http 200 https://registry.npmjs.org/wintersmith-sassy/-/wintersmith-sassy-1.1.0.tgz
npm http 200 https://registry.npmjs.org/ngx-uploader/-/ngx-uploader-2.2.5.tgz
npm http 200 https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.7.0.tgz
npm http 200 https://registry.npmjs.org/karma/-/karma-1.4.1.tgz
npm http 404 https://registry.npmjs.org/ngx-translate/http-loader
npm http 200 https://registry.npmjs.org/typescript/-/typescript-2.3.2.tgz
npm http 200 https://registry.npmjs.org/jasmine-spec-reporter/-/jasmine-spec-reporter-3.2.0.tgz
npm http 200 https://registry.npmjs.org/jquery/-/jquery-3.2.1.tgz
npm http 404 https://registry.npmjs.org/angular/http
npm http 404 https://registry.npmjs.org/angular/forms
The authenticity of host 'github.com (192.30.255.113)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
'yes' 
Please type 'yes' or 'no': yes
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/avinashmishra/Desktop/projects1/npm-debug.log
npm ERR! not ok code 0

**Comment by codingtwinky** [comment]
Hi, I'm not sure this is an ungit problem and it rather seems to be a npm problem.  It seems like something related to routing to registry.  Does any other npm installs work?
