### ISSUE TITLE
Feature suggestions: auto updating

### ISSUE THREAD

**Issue by refaelsh** [FredrikNoren/ungit#936]
Hi,

I have a feature suggestion.
Whenever a new version is available it should notify the user and propose to update.

Thanks.

**Comment by lfx** [comment]
Is it not?
I have an older version and it shows this - http://imgur.com/a/0TTct

**Comment by refaelsh** [comment]
Ooppss... Sorry my bad :-) I will close the issue.
I was checking this functionality while being on the latest version!
Sorry for the bother!
