### ISSUE TITLE
Deleting remote branch should pop a more eye-catching warning?

### ISSUE THREAD

**Issue by wonson** [FredrikNoren/ungit#947]
I think deleting remote branch is a rather dangereous operation, maybe it should have a more eye-catching warning to warn the user? 
For example, bright red text, bold, capital case, [ ! ] symbol icon, etc...?

Today i nearly deleted a remote branch, but what i want is to delete a local branch tracking that branch only. Its quite frightening :(

**Comment by refaelsh** [comment]
+1

**Comment by jmfgdev** [comment]
I hope you didn't lose any/much progress :/
