### ISSUE TITLE
Using Ungit commercially?

### ISSUE THREAD

**Issue by ARDivekar** [FredrikNoren/ungit#958]
Is it possible to use Ungit in a commercial setting? Does it send *any* sort of user creds/account info/usage data/logs/ etc. to any remote server?

**Comment by codingtwinky** [comment]
Ungit does have some crash reports and some usage report tracking for debugging purposes, but I'm not sure if it is being used or monitored as it seems to be broken from my side.

But one can disable all tracking via having below `.ungitrc` file in the home dir manually and it is disabled by default.  However, it may ask you if you want to enable it in first few usages.

```
{
  bugtracking: false,
  sendUsageStatistics: false
}
```

**Comment by tofran** [comment]
If you are looking forward to use Ungit in a company you should also have a look at the [LICENSE](https://github.com/FredrikNoren/ungit/blob/master/LICENSE.md) and their  [faircode page](https://faircode.io/product/Ungit).
Also, there's an in depth discussion in #974

**Comment by ajostergaard** [comment]
@ARDivekar soooo many open issues - fancy closing this one?

**Comment by ARDivekar** [comment]
@ajostergaard Sure but one last question. What was the commit ID before which ungit switched to Faircode? I want to recommend the software to some of my peers but don't want them to have potential conflict if they use it in their workplace.

**Comment by ajostergaard** [comment]
It's back to [MIT](https://github.com/FredrikNoren/ungit/blob/master/LICENSE.md).

**Comment by ARDivekar** [comment]
Oh awesome. Now I can upgrade it again haha.
