### ISSUE TITLE
[Feature Request] List of remote branches?

### ISSUE THREAD

**Issue by wonson** [FredrikNoren/ungit#966]
I hope ungit can show a list of remote branches(&tags). If i hvnt checkout a remote branch, and the branch has sunk for a period of time. It seems that I need to scroll and scroll down to find that remote branch from the tree now :(

**Comment by LukeDWood** [comment]
This is something I'd like to see also. 
The large amount of scrolling can take a while due to the UI refreshing /updating with every page and a list/search function (similar to #984?) would alleviate this.

**Comment by codingtwinky** [comment]
I do think this is definitely a feature that is needed.  However I'm having some hard time envisioning UI for this feature though.

Perhaps, remotes branches can simply be included in current 'branch dropdown' menu with scroll bar and allow `checkout` of that branch.  But my main point of contention is a case where local branch with same name as remote branch already exists and can't simply just create and check out.

From there, my thoughts went into allowing other git operations from the drop down menu and things got overwhelming quite quickly.


I'm going to think about this little more but please feel free to make any and all suggestions

**Comment by LukeDWood** [comment]
I'd imagine another tab on the upper right would work well, you already have this feature (minus the search) for local branches.

![image](https://user-images.githubusercontent.com/13216206/34668749-a9162220-f466-11e7-89bc-6a9eb6d67fcd.png)

**Comment by jung-kim** [comment]
I'm currently working on it right now but as I have shared my main point of contention before.  There are some complications with this feature, it is bit tricky to support remote branch checkout feature on click as it is for the local branch.  

We could do branchless, or headless, checkout.  But than that would break Ungit's operation rule, which is "all operations are done with branch".  Any subsequent cherry pick, push or other operations will break the UI.  Which is what I'm seeing right now.

We cannot alway create a branch with same name as remote as if local branch with same name exists it cause conflicts.  

Right now, my thought is that on remote branch checkout, try to create a local branch with same name at the remote branch location.  If that fails, create temporary branch.  It's bit expansive, round about and not ideal but I think that is the best way for this feature.



<img width="997" alt="screen shot 2018-01-15 at 13 46 02" src="https://user-images.githubusercontent.com/5281068/34962885-82d8a88c-f9fa-11e7-9e85-3fbed1075f83.png">

**Comment by LukeDWood** [comment]
@jung-kim Thanks for adding this in, it looks like it'll be a great help. 
Instead of creating temp branches have you considered stashing changes before force moving the branch?

**Comment by jung-kim** [comment]
These are already committed commits.  Nonetheless, I'm not sure storing changes as stash would help in this case.
