### ISSUE TITLE
UI support for tons of tags on the same commit

### ISSUE THREAD

**Issue by bakkerthehacker** [FredrikNoren/ungit#973]
Some of the repos I use ungit in have automated systems that will attach a lot of tags to commits.  Some of these commits can end up with 10-100 tags on them, each 50 to 100 characters long.  

The ungit UI puts the commit buttons (merge, checkout, move, rebase) on the far right side of all of these tags.  Scrolling over very very far, or zooming out, is a huge hassle when dealing with these commits and makes ungit essentially unusable.  

Some solutions may be to:
- have a customizable filter for tags
- limit the number of tags on a commit
- move the commit-buttons to some other location that is not dependant on the tags

**Comment by Thatkookooguy** [comment]
@bakkerthehacker is there an example of a project that has this problem? I might look into this a little and a test case would help greatly

**Comment by campersau** [comment]
@Thatkookooguy for your information @codingtwinky is already working on this see #984
Or is this related to https://github.com/FredrikNoren/ungit/issues/974#issuecomment-341961804 ?
