### ISSUE TITLE
express-session memory leak

### ISSUE THREAD

**Issue by roccomuso** [FredrikNoren/ungit#977]
The default "memory" storage for sessions suffer a well known memory leak. As pointed out on the `express-session` documentation. The usage is discouraged in production.

Consider switching to a leak-proof in-memory store: [memorystore](https://github.com/roccomuso/memorystore)

**Comment by codingtwinky** [comment]
That warning documentation line in `express-session` needs be more catch... May I should contact my middle school friend who used to do crazy myspace css effects for them...

**Comment by codingtwinky** [comment]
fixed in #979
