### ISSUE TITLE
Subsequent `ungit` invocations don't open browser in 1.2.0

### ISSUE THREAD

**Issue by gigstada** [FredrikNoren/ungit#986]
This could be an issue with how I use ungit, so please recommend alternatives if I'm not using the tool right. 

In ungit@1.1.33, my workflow during a single day can involve 50+ repositories that I have cloned in the same directory. I usually start ungit in a terminal in my home directory just to get the ungit server running and then immediately close the browser tab it opens because I don't need it (I know there is a command-line option to not even open it). Then, as I'm jumping around in the repos I'm working on in the terminal, I just do a quick `ungit` in the repo I care about, and the ungit page for that repo pops in the browser on the ungit server instance I always have running.

In ungit@1.2.0, this workflow no longer works. I start up my ungit instance as usual and then try to run ungit in the actual repositories I'm working on. When I do that, I just get the message "Ungit server already running" and a new browser tab does not open.

Was this an intended change? Is there a way I can toggle the former behavior back on in 1.2.0?

**Comment by codingtwinky** [comment]
Yap, I know why and will give you a fix soon.  this is entirely on me.

**Comment by wormeyman** [comment]
I believe this issue has been resolved and can be closed now.

**Comment by campersau** [comment]
Fixed in ungit version 1.2.1 with #987
