### ISSUE TITLE
Update CONTRIBUTINg.md

### ISSUE THREAD

**Issue by codingtwinky** [FredrikNoren/ungit#996]
@FredrikNoren As license change, can we update with additional infos around contribution?  Mainly for me is that assurance of the possibly alleviated fee with contribution to one and one's company and more wording around what exactly it means to become a contributor.

Perhaps, faircode.io should have one and link to it.

https://github.com/FredrikNoren/ungit/blob/master/CONTRIBUTING.md

**Comment by FredrikNoren** [comment]
Closing this since we're reverting to MIT anyway (see #997 )
