### ISSUE TITLE
Revert license to MIT

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#997]
Hi all,

I've been thinking a lot about Faircode and Ungit, and how this experiment has progressed so far. The tldr is that, after consulting with @codingtwinky, we've decided to revert the license to MIT.

The original hypothesis with Faircode was that it would be an easier and more effective approach to funding "Open Source"; by charging a license fee from big companies (though as detailed in #974 this would not technically be Open Source as defined by OSI, but something else).

To try this idea, we changed Ungit from MIT to the Faircode license, and I built a simple platform for accepting license payments.

Simply changing the license text had very little effect though, as most people don’t follow exactly what happens on the repo from day to day. No companies came forward to pay for the license fee at this time.

But it didn't seem fair to stop the experiment there; how can people pay the license fee if they’re not aware of the license change? So I implemented a small dismissable panel at the top of the Ungit UI that informed people about the new license and who needed to pay for it. It read:

    "Ungit is Faircode Licensed. See the full License text here: Ungit at Faircode.io.
    Note: If you're using Ungit at work, make sure your company has a license subscription!"

997 users saw and dismissed this panel (actually more probably saw it but that’s the number of dismisses). A lot of debate emerged in #974, which eventually was followed by an even bigger discussion at [Hacker News](https://news.ycombinator.com/item?id=15628786). But once again no companies actually paid for a license subscription.

However, there were two problems at this time; 1) The panel was very discreet and I wasn’t sure people actually read it or if they just closed it instantly 2) The pricing model was completely off, which I thought might have put a lot of people off. So I implemented a new pricing model (per-seat) and a replacement for the panel which forced people to actively choose if they were using the “free” version or the “commercial” version (a basic paywall).

That was released almost 4 weeks ago. To date, 1256 users have seen the paywall. 807 have clicked “Continue with Free”, 265 have clicked “skip for now” and 1 have purchased a subscription (for 10 seats).

This is where I think it's useful to back to the original hypothesis. The theory was that this would be an easier and more effective way to fund Open Source. With the evidence from above I feel that it’s safe to conclude that, for Ungit at least, the hypothesis was proven wrong.

There could be a number of factors behind this for Ungit. Uncertainty of the license text, an unwillingness to pay, “competition” from other paid git clients, or perhaps no one actually used Ungit at work (I find that one hard to believe though). I'm not sure which of these factors mattered, or if there were others (feel free to contribute ideas).

Ungit was the primary experiment for the Faircode model, and as that experiment seems to be coming out negative I don’t think it would be fair to continue the Faircode platform. faircode.io will go offline today as well.

Even though this is the end for Faircode, I do hope others will try other things. Getting Open Source developers paid is still something I think is a worthy pursuit, and I'm sure that there are better solutions out there than what we've tried here. Perhaps there are tweaks to the Faircode model, or perhaps at a different time and a different project the conclusion would be different.

I do want to say thank you to everyone for a good and insightful discussion, and for patiently letting me run this experiment. I've certainly learned a lot, and I hope others have as well.

(I'll leave this issue open for a month for visibility)

Edit: For those who suggested I should try patreon: https://www.patreon.com/fredriknoren

**Comment by gigstada** [comment]
What a journey. I think my company had either already ordered 10 seats or was preparing to. I was involved in many discussions with our management as the experiment evolved. They were very supportive, but I'm sure they will be glad to see the license stabilize.

I've been using ungit for quite a few years now and I promote it as a learning tool for new git users and a great visual experience for any users. Huge thanks to you and other contributors for your work on this.

I'll be curious to see how the Patreon situation goes. I wonder how users would feel about a little plug for it in the ungit UI.

**Comment by waldyrious** [comment]
@FredrikNoren I just wanted to commend you for the admirable way you handled the discussion at #974, responding in a respectful and neutral way to all inputs (even those that took a more aggressive tone) and in multiple occasions managing to gracefully nudge the discussion back into a positive, constructive trail. Well done! :clap:

**Comment by ryantheleach** [comment]
I think the main reason I was dissenting, is it seemed like the project was changing.

Had it been under the Faircode license from the start, I would have had many less objections.

I think a modified Faircode license could work for new projects.

**Comment by FredrikNoren** [comment]
@waldyrious Thank you!
